// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/comprehensive/v1/comprehensive.proto (package ai.comprehensive.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_jev_v1_options } from "../../../jev/v1/options_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/comprehensive/v1/comprehensive.proto.
 */
export const file_ai_comprehensive_v1_comprehensive: GenFile = /*@__PURE__*/
  fileDesc("CidhaS9jb21wcmVoZW5zaXZlL3YxL2NvbXByZWhlbnNpdmUucHJvdG8SE2FpLmNvbXByZWhlbnNpdmUudjEiKwoITWV0YWRhdGESDgoGc291cmNlGAEgASgJEg8KB3ZlcnNpb24YAiABKAUizAcKE0NvbXByZWhlbnNpdmVSZWNvcmQSFAoMdGV4dF9ib3VuZGVkGAEgASgJEhUKDWVtYWlsX2FkZHJlc3MYAiABKAkSEwoLd2Vic2l0ZV91cmwYAyABKAkSFgoOY3VzdG9tX3BhdHRlcm4YBCABKAkSFQoNcHJlZml4ZWRfY29kZRgFIAEoCRJnCglzY29yZV9pbnQYBiABKAVCVKqpI1AiTgoYCQAAAAAAAPA/Eg1NaW5pbXVtIHNjb3JlChgJAAAAAAAASUASDUF2ZXJhZ2Ugc2NvcmUKGAkAAAAAAABZQBINTWF4aW11bSBzY29yZRIRCgliaWdfY291bnQYByABKAMSUQoFcmF0aW8YCCABKAJCQqqpIz4iPAoMEgpaZXJvIHJhdGlvChUJAAAAAAAA4D8SCkhhbGYgcmF0aW8KFQkAAAAAAADwPxIKRnVsbCByYXRpbxJRCghsYXRpdHVkZRgJIAEoAUI/qqkjOyI5ChUJAAAAAACAVsASClNvdXRoIFBvbGUKCRIHRXF1YXRvcgoVCQAAAAAAgFZAEgpOb3J0aCBQb2xlEhIKCmlzX2VuYWJsZWQYCiABKAgSKwoGc3RhdHVzGAsgASgOMhsuYWkuY29tcHJlaGVuc2l2ZS52MS5TdGF0dXMSDAoEdGFncxgMIAMoCRIvCghtZXRhZGF0YRgNIAEoCzIdLmFpLmNvbXByZWhlbnNpdmUudjEuTWV0YWRhdGESEgoFbm90ZXMYDiABKAlIAYgBARJMCgphdHRyaWJ1dGVzGA8gAygLMjguYWkuY29tcHJlaGVuc2l2ZS52MS5Db21wcmVoZW5zaXZlUmVjb3JkLkF0dHJpYnV0ZXNFbnRyeRIWCgx0ZXh0X3BheWxvYWQYECABKAlIABIYCg5iaW5hcnlfcGF5bG9hZBgRIAEoDEgAElUKCmNodXJuX3Jpc2sYEiABKAhCQaqpIz0KO0N1c3RvbSBKZXYgaW5zdHJ1Y3Rpb246IGFzc2VzcyBjdXN0b21lciBjYW5jZWxsYXRpb24gaW50ZW50EiMKE2ludGVybmFsX2RlYnVnX2luZm8YEyABKAlCBqqpIwIQARJKCgxhY2NvdW50X3RpZXIYFCABKAlCNKqpIzAaLgoNVElFUl9TVEFOREFSRAoMVElFUl9QUkVNSVVNCg9USUVSX0VOVEVSUFJJU0UaMQoPQXR0cmlidXRlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCCQoHcGF5bG9hZEIICgZfbm90ZXMqWwoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEhEKDVNUQVRVU19BQ1RJVkUQARIRCg1TVEFUVVNfUEFVU0VEEAISEwoPU1RBVFVTX0FSQ0hJVkVEEANCJVojYWkvY29tcHJlaGVuc2l2ZS92MTtjb21wcmVoZW5zaXZldjFiBnByb3RvMw", [file_jev_v1_options]);

/**
 * A nested message for testing object properties.
 *
 * @generated from message ai.comprehensive.v1.Metadata
 */
export type Metadata = Message<"ai.comprehensive.v1.Metadata"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;

  /**
   * @generated from field: int32 version = 2;
   */
  version: number;
};

/**
 * Describes the message ai.comprehensive.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_ai_comprehensive_v1_comprehensive, 0);

/**
 * Comprehensive test message exercising every option and rule combination.
 *
 * @generated from message ai.comprehensive.v1.ComprehensiveRecord
 */
export type ComprehensiveRecord = Message<"ai.comprehensive.v1.ComprehensiveRecord"> & {
  /**
   * --- String validation variants ---
   *
   * @generated from field: string text_bounded = 1;
   */
  textBounded: string;

  /**
   * @generated from field: string email_address = 2;
   */
  emailAddress: string;

  /**
   * @generated from field: string website_url = 3;
   */
  websiteUrl: string;

  /**
   * @generated from field: string custom_pattern = 4;
   */
  customPattern: string;

  /**
   * @generated from field: string prefixed_code = 5;
   */
  prefixedCode: string;

  /**
   * --- Numeric validation variants ---
   *
   * @generated from field: int32 score_int = 6;
   */
  scoreInt: number;

  /**
   * @generated from field: int64 big_count = 7;
   */
  bigCount: bigint;

  /**
   * @generated from field: float ratio = 8;
   */
  ratio: number;

  /**
   * @generated from field: double latitude = 9;
   */
  latitude: number;

  /**
   * --- Boolean & Enum ---
   *
   * @generated from field: bool is_enabled = 10;
   */
  isEnabled: boolean;

  /**
   * @generated from field: ai.comprehensive.v1.Status status = 11;
   */
  status: Status;

  /**
   * --- Repeated / Arrays ---
   *
   * @generated from field: repeated string tags = 12;
   */
  tags: string[];

  /**
   * --- Nested message ---
   *
   * @generated from field: ai.comprehensive.v1.Metadata metadata = 13;
   */
  metadata?: Metadata | undefined;

  /**
   * --- Optional field ---
   *
   * @generated from field: optional string notes = 14;
   */
  notes?: string | undefined;

  /**
   * --- Map ---
   *
   * @generated from field: map<string, string> attributes = 15;
   */
  attributes: { [key: string]: string };

  /**
   * --- Oneof ---
   *
   * @generated from oneof ai.comprehensive.v1.ComprehensiveRecord.payload
   */
  payload: {
    /**
     * @generated from field: string text_payload = 16;
     */
    value: string;
    case: "textPayload";
  } | {
    /**
     * @generated from field: bytes binary_payload = 17;
     */
    value: Uint8Array;
    case: "binaryPayload";
  } | { case: undefined; value?: undefined };

  /**
   * --- Jev custom options testing ---
   *
   * @generated from field: bool churn_risk = 18;
   */
  churnRisk: boolean;

  /**
   * @generated from field: string internal_debug_info = 19;
   */
  internalDebugInfo: string;

  /**
   * Discrete string choices via Jev options
   *
   * @generated from field: string account_tier = 20;
   */
  accountTier: string;
};

/**
 * Describes the message ai.comprehensive.v1.ComprehensiveRecord.
 * Use `create(ComprehensiveRecordSchema)` to create a new message.
 */
export const ComprehensiveRecordSchema: GenMessage<ComprehensiveRecord> = /*@__PURE__*/
  messageDesc(file_ai_comprehensive_v1_comprehensive, 1);

/**
 * An enum demonstrating valid options.
 *
 * @generated from enum ai.comprehensive.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: STATUS_PAUSED = 2;
   */
  PAUSED = 2,

  /**
   * @generated from enum value: STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * Describes the enum ai.comprehensive.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_ai_comprehensive_v1_comprehensive, 0);

