"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score

class MetadataJevClient:
    """Typed Jev client for evaluating Metadata."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "version": Score(
                instructions="Evaluate version",
                criteria=["1", "2", "3", "4", "5"],
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "version" in resp.scores:
            out["version"] = resp.scores["version"].score
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class ComprehensiveRecordJevClient:
    """Typed Jev client for evaluating ComprehensiveRecord."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "scoreInt": Score(
                instructions="--- Numeric validation variants ---",
                criteria=["1", "26", "51", "75", "100"],
            ),
            "bigCount": Score(
                instructions="Evaluate bigCount",
                criteria=["1", "2", "3", "4", "5"],
            ),
            "ratio": Score(
                instructions="Evaluate ratio",
                criteria=["0.0", "0.25", "0.5", "0.75", "1.0"],
            ),
            "latitude": Score(
                instructions="Evaluate latitude",
                criteria=["-90.0", "-45.0", "0.0", "45.0", "90.0"],
            ),
            "isEnabled": Noul(
                instructions="--- Boolean & Enum ---",
            ),
            "status": Choice(
                instructions="Evaluate status",
                criteria={"STATUS_ACTIVE": None, "STATUS_ARCHIVED": None, "STATUS_PAUSED": None},
            ),
            "payload": Choice(
                instructions="--- Oneof ---",
                criteria={"binary_payload": None, "text_payload": None},
            ),
            "churnRisk": Noul(
                instructions="Custom Jev instruction: assess customer cancellation intent",
            ),
            "accountTier": Choice(
                instructions="Discrete string choices via Jev options",
                criteria={"TIER_ENTERPRISE": None, "TIER_PREMIUM": None, "TIER_STANDARD": None},
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "scoreInt" in resp.scores:
            out["score_int"] = resp.scores["scoreInt"].score
        if "bigCount" in resp.scores:
            out["big_count"] = resp.scores["bigCount"].score
        if "ratio" in resp.scores:
            out["ratio"] = resp.scores["ratio"].score
        if "latitude" in resp.scores:
            out["latitude"] = resp.scores["latitude"].score
        if "isEnabled" in resp.nouls:
            _item = resp.nouls["isEnabled"]
            out["is_enabled"] = getattr(_item, "result", getattr(_item, "noul", False))
        if "status" in resp.choices:
            out["status"] = resp.choices["status"].choice
        if "payload" in resp.choices:
            out["payload"] = resp.choices["payload"].choice
        if "churnRisk" in resp.nouls:
            _item = resp.nouls["churnRisk"]
            out["churn_risk"] = getattr(_item, "result", getattr(_item, "noul", False))
        if "accountTier" in resp.choices:
            out["account_tier"] = resp.choices["accountTier"].choice
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

