// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/comprehensive/v1/comprehensive.proto

package comprehensivev1

import (
	_ "github.com/sudorandom/protoc-gen-jev/pkg/jev/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An enum demonstrating valid options.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_PAUSED      Status = 2
	Status_STATUS_ARCHIVED    Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_PAUSED",
		3: "STATUS_ARCHIVED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_PAUSED":      2,
		"STATUS_ARCHIVED":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_comprehensive_v1_comprehensive_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_ai_comprehensive_v1_comprehensive_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_ai_comprehensive_v1_comprehensive_proto_rawDescGZIP(), []int{0}
}

// A nested message for testing object properties.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_ai_comprehensive_v1_comprehensive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_ai_comprehensive_v1_comprehensive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_ai_comprehensive_v1_comprehensive_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Comprehensive test message exercising every option and rule combination.
type ComprehensiveRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- String validation variants ---
	TextBounded   string `protobuf:"bytes,1,opt,name=text_bounded,json=textBounded,proto3" json:"text_bounded,omitempty"`
	EmailAddress  string `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	WebsiteUrl    string `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	CustomPattern string `protobuf:"bytes,4,opt,name=custom_pattern,json=customPattern,proto3" json:"custom_pattern,omitempty"`
	PrefixedCode  string `protobuf:"bytes,5,opt,name=prefixed_code,json=prefixedCode,proto3" json:"prefixed_code,omitempty"`
	// --- Numeric validation variants ---
	ScoreInt int32   `protobuf:"varint,6,opt,name=score_int,json=scoreInt,proto3" json:"score_int,omitempty"`
	BigCount int64   `protobuf:"varint,7,opt,name=big_count,json=bigCount,proto3" json:"big_count,omitempty"`
	Ratio    float32 `protobuf:"fixed32,8,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Latitude float64 `protobuf:"fixed64,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// --- Boolean & Enum ---
	IsEnabled bool   `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	Status    Status `protobuf:"varint,11,opt,name=status,proto3,enum=ai.comprehensive.v1.Status" json:"status,omitempty"`
	// --- Repeated / Arrays ---
	Tags []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// --- Nested message ---
	Metadata *Metadata `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// --- Optional field ---
	Notes *string `protobuf:"bytes,14,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	// --- Map ---
	Attributes map[string]string `protobuf:"bytes,15,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// --- Oneof ---
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ComprehensiveRecord_TextPayload
	//	*ComprehensiveRecord_BinaryPayload
	Payload isComprehensiveRecord_Payload `protobuf_oneof:"payload"`
	// --- Jev custom options testing ---
	ChurnRisk         bool   `protobuf:"varint,18,opt,name=churn_risk,json=churnRisk,proto3" json:"churn_risk,omitempty"`
	InternalDebugInfo string `protobuf:"bytes,19,opt,name=internal_debug_info,json=internalDebugInfo,proto3" json:"internal_debug_info,omitempty"`
	// Discrete string choices via Jev options
	AccountTier   string `protobuf:"bytes,20,opt,name=account_tier,json=accountTier,proto3" json:"account_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComprehensiveRecord) Reset() {
	*x = ComprehensiveRecord{}
	mi := &file_ai_comprehensive_v1_comprehensive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComprehensiveRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComprehensiveRecord) ProtoMessage() {}

func (x *ComprehensiveRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ai_comprehensive_v1_comprehensive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComprehensiveRecord.ProtoReflect.Descriptor instead.
func (*ComprehensiveRecord) Descriptor() ([]byte, []int) {
	return file_ai_comprehensive_v1_comprehensive_proto_rawDescGZIP(), []int{1}
}

func (x *ComprehensiveRecord) GetTextBounded() string {
	if x != nil {
		return x.TextBounded
	}
	return ""
}

func (x *ComprehensiveRecord) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *ComprehensiveRecord) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *ComprehensiveRecord) GetCustomPattern() string {
	if x != nil {
		return x.CustomPattern
	}
	return ""
}

func (x *ComprehensiveRecord) GetPrefixedCode() string {
	if x != nil {
		return x.PrefixedCode
	}
	return ""
}

func (x *ComprehensiveRecord) GetScoreInt() int32 {
	if x != nil {
		return x.ScoreInt
	}
	return 0
}

func (x *ComprehensiveRecord) GetBigCount() int64 {
	if x != nil {
		return x.BigCount
	}
	return 0
}

func (x *ComprehensiveRecord) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *ComprehensiveRecord) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ComprehensiveRecord) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *ComprehensiveRecord) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ComprehensiveRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ComprehensiveRecord) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ComprehensiveRecord) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *ComprehensiveRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ComprehensiveRecord) GetPayload() isComprehensiveRecord_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ComprehensiveRecord) GetTextPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*ComprehensiveRecord_TextPayload); ok {
			return x.TextPayload
		}
	}
	return ""
}

func (x *ComprehensiveRecord) GetBinaryPayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ComprehensiveRecord_BinaryPayload); ok {
			return x.BinaryPayload
		}
	}
	return nil
}

func (x *ComprehensiveRecord) GetChurnRisk() bool {
	if x != nil {
		return x.ChurnRisk
	}
	return false
}

func (x *ComprehensiveRecord) GetInternalDebugInfo() string {
	if x != nil {
		return x.InternalDebugInfo
	}
	return ""
}

func (x *ComprehensiveRecord) GetAccountTier() string {
	if x != nil {
		return x.AccountTier
	}
	return ""
}

type isComprehensiveRecord_Payload interface {
	isComprehensiveRecord_Payload()
}

type ComprehensiveRecord_TextPayload struct {
	TextPayload string `protobuf:"bytes,16,opt,name=text_payload,json=textPayload,proto3,oneof"`
}

type ComprehensiveRecord_BinaryPayload struct {
	BinaryPayload []byte `protobuf:"bytes,17,opt,name=binary_payload,json=binaryPayload,proto3,oneof"`
}

func (*ComprehensiveRecord_TextPayload) isComprehensiveRecord_Payload() {}

func (*ComprehensiveRecord_BinaryPayload) isComprehensiveRecord_Payload() {}

var File_ai_comprehensive_v1_comprehensive_proto protoreflect.FileDescriptor

const file_ai_comprehensive_v1_comprehensive_proto_rawDesc = "" +
	"\n" +
	"'ai/comprehensive/v1/comprehensive.proto\x12\x13ai.comprehensive.v1\x1a\x14jev/v1/options.proto\"<\n" +
	"\bMetadata\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\xbe\t\n" +
	"\x13ComprehensiveRecord\x12!\n" +
	"\ftext_bounded\x18\x01 \x01(\tR\vtextBounded\x12#\n" +
	"\remail_address\x18\x02 \x01(\tR\femailAddress\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12%\n" +
	"\x0ecustom_pattern\x18\x04 \x01(\tR\rcustomPattern\x12#\n" +
	"\rprefixed_code\x18\x05 \x01(\tR\fprefixedCode\x12q\n" +
	"\tscore_int\x18\x06 \x01(\x05BT\xaa\xa9#P\"N\n" +
	"\x18\t\x00\x00\x00\x00\x00\x00\xf0?\x12\rMinimum score\n" +
	"\x18\t\x00\x00\x00\x00\x00\x00I@\x12\rAverage score\n" +
	"\x18\t\x00\x00\x00\x00\x00\x00Y@\x12\rMaximum scoreR\bscoreInt\x12\x1b\n" +
	"\tbig_count\x18\a \x01(\x03R\bbigCount\x12X\n" +
	"\x05ratio\x18\b \x01(\x02BB\xaa\xa9#>\"<\n" +
	"\f\x12\n" +
	"Zero ratio\n" +
	"\x15\t\x00\x00\x00\x00\x00\x00\xe0?\x12\n" +
	"Half ratio\n" +
	"\x15\t\x00\x00\x00\x00\x00\x00\xf0?\x12\n" +
	"Full ratioR\x05ratio\x12[\n" +
	"\blatitude\x18\t \x01(\x01B?\xaa\xa9#;\"9\n" +
	"\x15\t\x00\x00\x00\x00\x00\x80V\xc0\x12\n" +
	"South Pole\n" +
	"\t\x12\aEquator\n" +
	"\x15\t\x00\x00\x00\x00\x00\x80V@\x12\n" +
	"North PoleR\blatitude\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\n" +
	" \x01(\bR\tisEnabled\x123\n" +
	"\x06status\x18\v \x01(\x0e2\x1b.ai.comprehensive.v1.StatusR\x06status\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x129\n" +
	"\bmetadata\x18\r \x01(\v2\x1d.ai.comprehensive.v1.MetadataR\bmetadata\x12\x19\n" +
	"\x05notes\x18\x0e \x01(\tH\x01R\x05notes\x88\x01\x01\x12X\n" +
	"\n" +
	"attributes\x18\x0f \x03(\v28.ai.comprehensive.v1.ComprehensiveRecord.AttributesEntryR\n" +
	"attributes\x12#\n" +
	"\ftext_payload\x18\x10 \x01(\tH\x00R\vtextPayload\x12'\n" +
	"\x0ebinary_payload\x18\x11 \x01(\fH\x00R\rbinaryPayload\x12`\n" +
	"\n" +
	"churn_risk\x18\x12 \x01(\bBA\xaa\xa9#=\n" +
	";Custom Jev instruction: assess customer cancellation intentR\tchurnRisk\x126\n" +
	"\x13internal_debug_info\x18\x13 \x01(\tB\x06\xaa\xa9#\x02\x10\x01R\x11internalDebugInfo\x12W\n" +
	"\faccount_tier\x18\x14 \x01(\tB4\xaa\xa9#0\x1a.\n" +
	"\rTIER_STANDARD\n" +
	"\fTIER_PREMIUM\n" +
	"\x0fTIER_ENTERPRISER\vaccountTier\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayloadB\b\n" +
	"\x06_notes*[\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x11\n" +
	"\rSTATUS_PAUSED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ARCHIVED\x10\x03B%Z#ai/comprehensive/v1;comprehensivev1b\x06proto3"

var (
	file_ai_comprehensive_v1_comprehensive_proto_rawDescOnce sync.Once
	file_ai_comprehensive_v1_comprehensive_proto_rawDescData []byte
)

func file_ai_comprehensive_v1_comprehensive_proto_rawDescGZIP() []byte {
	file_ai_comprehensive_v1_comprehensive_proto_rawDescOnce.Do(func() {
		file_ai_comprehensive_v1_comprehensive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_comprehensive_v1_comprehensive_proto_rawDesc), len(file_ai_comprehensive_v1_comprehensive_proto_rawDesc)))
	})
	return file_ai_comprehensive_v1_comprehensive_proto_rawDescData
}

var file_ai_comprehensive_v1_comprehensive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_comprehensive_v1_comprehensive_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ai_comprehensive_v1_comprehensive_proto_goTypes = []any{
	(Status)(0),                 // 0: ai.comprehensive.v1.Status
	(*Metadata)(nil),            // 1: ai.comprehensive.v1.Metadata
	(*ComprehensiveRecord)(nil), // 2: ai.comprehensive.v1.ComprehensiveRecord
	nil,                         // 3: ai.comprehensive.v1.ComprehensiveRecord.AttributesEntry
}
var file_ai_comprehensive_v1_comprehensive_proto_depIdxs = []int32{
	0, // 0: ai.comprehensive.v1.ComprehensiveRecord.status:type_name -> ai.comprehensive.v1.Status
	1, // 1: ai.comprehensive.v1.ComprehensiveRecord.metadata:type_name -> ai.comprehensive.v1.Metadata
	3, // 2: ai.comprehensive.v1.ComprehensiveRecord.attributes:type_name -> ai.comprehensive.v1.ComprehensiveRecord.AttributesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_comprehensive_v1_comprehensive_proto_init() }
func file_ai_comprehensive_v1_comprehensive_proto_init() {
	if File_ai_comprehensive_v1_comprehensive_proto != nil {
		return
	}
	file_ai_comprehensive_v1_comprehensive_proto_msgTypes[1].OneofWrappers = []any{
		(*ComprehensiveRecord_TextPayload)(nil),
		(*ComprehensiveRecord_BinaryPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_comprehensive_v1_comprehensive_proto_rawDesc), len(file_ai_comprehensive_v1_comprehensive_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_comprehensive_v1_comprehensive_proto_goTypes,
		DependencyIndexes: file_ai_comprehensive_v1_comprehensive_proto_depIdxs,
		EnumInfos:         file_ai_comprehensive_v1_comprehensive_proto_enumTypes,
		MessageInfos:      file_ai_comprehensive_v1_comprehensive_proto_msgTypes,
	}.Build()
	File_ai_comprehensive_v1_comprehensive_proto = out.File
	file_ai_comprehensive_v1_comprehensive_proto_goTypes = nil
	file_ai_comprehensive_v1_comprehensive_proto_depIdxs = nil
}
