// Code generated by protoc-gen-jev. DO NOT EDIT.
package comprehensivev1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

const DefaultJevEndpoint = "https://api.typesafe.ai/v1/systemone"

// MetadataJevDecisions holds structured decisions returned by Jev for Metadata.
type MetadataJevDecisions struct {
	Version float64 `json:"version"`
}

// MetadataJevClient is a typed client for evaluating Metadata decisions via Jev.
type MetadataJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewMetadataJevClient(apiKey string) *MetadataJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &MetadataJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *MetadataJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"version": map[string]any{
			"type":         "score",
			"instructions": "Evaluate version",
			"criteria":     []string{"1", "2", "3", "4", "5"},
		},
	}
}

func (c *MetadataJevClient) Evaluate(ctx context.Context, state any) (*MetadataJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &MetadataJevDecisions{}
	if item, ok := rawResp.Scores["version"]; ok {
		decisions.Version = item.Score
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *MetadataJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*MetadataJevDecisions, error) {
	results := make([]*MetadataJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// ComprehensiveRecordJevDecisions holds structured decisions returned by Jev for ComprehensiveRecord.
type ComprehensiveRecordJevDecisions struct {
	ScoreInt    float64 `json:"scoreInt"`
	BigCount    float64 `json:"bigCount"`
	Ratio       float64 `json:"ratio"`
	Latitude    float64 `json:"latitude"`
	IsEnabled   bool    `json:"isEnabled"`
	Status      string  `json:"status"`
	Payload     string  `json:"payload"`
	ChurnRisk   bool    `json:"churnRisk"`
	AccountTier string  `json:"accountTier"`
}

// ComprehensiveRecordJevClient is a typed client for evaluating ComprehensiveRecord decisions via Jev.
type ComprehensiveRecordJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewComprehensiveRecordJevClient(apiKey string) *ComprehensiveRecordJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &ComprehensiveRecordJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *ComprehensiveRecordJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"scoreInt": map[string]any{
			"type":         "score",
			"instructions": "--- Numeric validation variants ---",
			"criteria":     []string{"1", "26", "51", "75", "100"},
		},
		"bigCount": map[string]any{
			"type":         "score",
			"instructions": "Evaluate bigCount",
			"criteria":     []string{"1", "2", "3", "4", "5"},
		},
		"ratio": map[string]any{
			"type":         "score",
			"instructions": "Evaluate ratio",
			"criteria":     []string{"0.0", "0.25", "0.5", "0.75", "1.0"},
		},
		"latitude": map[string]any{
			"type":         "score",
			"instructions": "Evaluate latitude",
			"criteria":     []string{"-90.0", "-45.0", "0.0", "45.0", "90.0"},
		},
		"isEnabled": map[string]any{
			"type":         "noul",
			"instructions": "--- Boolean & Enum ---",
		},
		"status": map[string]any{
			"type":         "choice",
			"instructions": "Evaluate status",
			"criteria":     map[string]any{"STATUS_ACTIVE": nil, "STATUS_ARCHIVED": nil, "STATUS_PAUSED": nil},
		},
		"payload": map[string]any{
			"type":         "choice",
			"instructions": "--- Oneof ---",
			"criteria":     map[string]any{"binary_payload": nil, "text_payload": nil},
		},
		"churnRisk": map[string]any{
			"type":         "noul",
			"instructions": "Custom Jev instruction: assess customer cancellation intent",
		},
		"accountTier": map[string]any{
			"type":         "choice",
			"instructions": "Discrete string choices via Jev options",
			"criteria":     map[string]any{"TIER_ENTERPRISE": nil, "TIER_PREMIUM": nil, "TIER_STANDARD": nil},
		},
	}
}

func (c *ComprehensiveRecordJevClient) Evaluate(ctx context.Context, state any) (*ComprehensiveRecordJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &ComprehensiveRecordJevDecisions{}
	if item, ok := rawResp.Scores["scoreInt"]; ok {
		decisions.ScoreInt = item.Score
	}
	if item, ok := rawResp.Scores["bigCount"]; ok {
		decisions.BigCount = item.Score
	}
	if item, ok := rawResp.Scores["ratio"]; ok {
		decisions.Ratio = item.Score
	}
	if item, ok := rawResp.Scores["latitude"]; ok {
		decisions.Latitude = item.Score
	}
	if item, ok := rawResp.Nouls["isEnabled"]; ok {
		decisions.IsEnabled = item.Result
	}
	if item, ok := rawResp.Choices["status"]; ok {
		decisions.Status = item.Choice
	}
	if item, ok := rawResp.Choices["payload"]; ok {
		decisions.Payload = item.Choice
	}
	if item, ok := rawResp.Nouls["churnRisk"]; ok {
		decisions.ChurnRisk = item.Result
	}
	if item, ok := rawResp.Choices["accountTier"]; ok {
		decisions.AccountTier = item.Choice
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *ComprehensiveRecordJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*ComprehensiveRecordJevDecisions, error) {
	results := make([]*ComprehensiveRecordJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}
