"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from google.protobuf.json_format import MessageToDict
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score
from .comprehensive_pb2 import (
    ComprehensiveRecord,
    Metadata,
)

def _interpolate_score(s: float, levels: List[float]) -> float:
    if not levels:
        return s
    if s <= 0:
        return levels[0]
    if s >= len(levels) - 1:
        return levels[-1]
    idx = int(s)
    frac = s - idx
    return levels[idx] + frac * (levels[idx + 1] - levels[idx])

class MetadataJevClient:
    """Typed Jev client for evaluating Metadata."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "version": Score(
                instructions="Evaluate version",
                criteria=["1", "2", "3", "4", "5"],
            ),
        }

    def evaluate(self, state: Metadata | Dict[str, Any] | str) -> Metadata:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = Metadata()
        score_version = None
        if hasattr(resp, "answers") and "version" in resp.answers:
            score_version = getattr(resp.answers["version"], "score", None)
        elif "version" in resp.scores:
            score_version = resp.scores["version"].score
        if score_version is not None:
            _s_val = _interpolate_score(score_version, [1, 2, 3, 4, 5])
            out.version = int(round(_s_val))
        return out

    def batch_evaluate(self, states: List[Metadata | Dict[str, Any] | str]) -> List[Metadata]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class ComprehensiveRecordJevClient:
    """Typed Jev client for evaluating ComprehensiveRecord."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "scoreInt": Score(
                instructions="--- Numeric validation variants ---",
                criteria=["Minimum score", "Average score", "Maximum score"],
            ),
            "bigCount": Score(
                instructions="Evaluate bigCount",
                criteria=["1", "2", "3", "4", "5"],
            ),
            "ratio": Score(
                instructions="Evaluate ratio",
                criteria=["Zero ratio", "Half ratio", "Full ratio"],
            ),
            "latitude": Score(
                instructions="Evaluate latitude",
                criteria=["South Pole", "Equator", "North Pole"],
            ),
            "isEnabled": Noul(
                instructions="--- Boolean & Enum ---",
            ),
            "status": Choice(
                instructions="Evaluate status",
                criteria={"STATUS_ACTIVE": "", "STATUS_ARCHIVED": "", "STATUS_PAUSED": ""},
            ),
            "payload": Choice(
                instructions="--- Oneof ---",
                criteria={"binary_payload": "binary_payload", "text_payload": "text_payload"},
            ),
            "churnRisk": Noul(
                instructions="Custom Jev instruction: assess customer cancellation intent",
            ),
            "accountTier": Choice(
                instructions="Discrete string choices via Jev options",
                criteria={"TIER_ENTERPRISE": "", "TIER_PREMIUM": "", "TIER_STANDARD": ""},
            ),
        }

    def evaluate(self, state: ComprehensiveRecord | Dict[str, Any] | str) -> ComprehensiveRecord:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = ComprehensiveRecord()
        score_scoreInt = None
        if hasattr(resp, "answers") and "scoreInt" in resp.answers:
            score_scoreInt = getattr(resp.answers["scoreInt"], "score", None)
        elif "scoreInt" in resp.scores:
            score_scoreInt = resp.scores["scoreInt"].score
        if score_scoreInt is not None:
            _s_val = _interpolate_score(score_scoreInt, [1, 50, 100])
            out.score_int = int(round(_s_val))
        score_bigCount = None
        if hasattr(resp, "answers") and "bigCount" in resp.answers:
            score_bigCount = getattr(resp.answers["bigCount"], "score", None)
        elif "bigCount" in resp.scores:
            score_bigCount = resp.scores["bigCount"].score
        if score_bigCount is not None:
            _s_val = _interpolate_score(score_bigCount, [1, 2, 3, 4, 5])
            out.big_count = int(round(_s_val))
        score_ratio = None
        if hasattr(resp, "answers") and "ratio" in resp.answers:
            score_ratio = getattr(resp.answers["ratio"], "score", None)
        elif "ratio" in resp.scores:
            score_ratio = resp.scores["ratio"].score
        if score_ratio is not None:
            _s_val = _interpolate_score(score_ratio, [0, 0.5, 1])
            out.ratio = _s_val
        score_latitude = None
        if hasattr(resp, "answers") and "latitude" in resp.answers:
            score_latitude = getattr(resp.answers["latitude"], "score", None)
        elif "latitude" in resp.scores:
            score_latitude = resp.scores["latitude"].score
        if score_latitude is not None:
            _s_val = _interpolate_score(score_latitude, [-90, 0, 90])
            out.latitude = _s_val
        noul_isEnabled = None
        if hasattr(resp, "answers") and "isEnabled" in resp.answers:
            noul_isEnabled = getattr(resp.answers["isEnabled"], "noul", None)
        elif "isEnabled" in resp.nouls:
            _item = resp.nouls["isEnabled"]
            noul_isEnabled = getattr(_item, "result", getattr(_item, "noul", False))
        if noul_isEnabled is not None:
            out.is_enabled = noul_isEnabled if isinstance(noul_isEnabled, bool) else (noul_isEnabled >= 0.5 if isinstance(noul_isEnabled, (int, float)) else False)
        choice_status = None
        if hasattr(resp, "answers") and "status" in resp.answers:
            choice_status = getattr(resp.answers["status"], "choice", None)
        elif "status" in resp.choices:
            choice_status = resp.choices["status"].choice
        if choice_status:
            enum_desc = out.DESCRIPTOR.fields_by_name["status"].enum_type
            if enum_desc and choice_status in enum_desc.values_by_name:
                setattr(out, "status", enum_desc.values_by_name[choice_status].number)
            else:
                try:
                    setattr(out, "status", int(choice_status))
                except (ValueError, TypeError):
                    pass
        choice_payload = None
        if hasattr(resp, "answers") and "payload" in resp.answers:
            choice_payload = getattr(resp.answers["payload"], "choice", None)
        elif "payload" in resp.choices:
            choice_payload = resp.choices["payload"].choice
        if choice_payload:
            _f_desc = out.DESCRIPTOR.fields_by_name.get(choice_payload)
            if _f_desc and _f_desc.type == 12:
                setattr(out, choice_payload, choice_payload.encode("utf-8"))
            else:
                setattr(out, choice_payload, choice_payload)
        noul_churnRisk = None
        if hasattr(resp, "answers") and "churnRisk" in resp.answers:
            noul_churnRisk = getattr(resp.answers["churnRisk"], "noul", None)
        elif "churnRisk" in resp.nouls:
            _item = resp.nouls["churnRisk"]
            noul_churnRisk = getattr(_item, "result", getattr(_item, "noul", False))
        if noul_churnRisk is not None:
            out.churn_risk = noul_churnRisk if isinstance(noul_churnRisk, bool) else (noul_churnRisk >= 0.5 if isinstance(noul_churnRisk, (int, float)) else False)
        choice_accountTier = None
        if hasattr(resp, "answers") and "accountTier" in resp.answers:
            choice_accountTier = getattr(resp.answers["accountTier"], "choice", None)
        elif "accountTier" in resp.choices:
            choice_accountTier = resp.choices["accountTier"].choice
        if choice_accountTier:
            setattr(out, "account_tier", choice_accountTier)
        return out

    def batch_evaluate(self, states: List[ComprehensiveRecord | Dict[str, Any] | str]) -> List[ComprehensiveRecord]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

