version: 2

builds:
  - binary: protoc-gen-jev
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
