// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/analysis/v1/analysis.proto

package analysisv1

import (
	_ "github.com/sudorandom/protoc-gen-jev/pkg/jev/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sentiment classification for the analyzed text.
type Sentiment int32

const (
	Sentiment_SENTIMENT_UNSPECIFIED Sentiment = 0
	Sentiment_SENTIMENT_POSITIVE    Sentiment = 1
	Sentiment_SENTIMENT_NEUTRAL     Sentiment = 2
	Sentiment_SENTIMENT_NEGATIVE    Sentiment = 3
)

// Enum value maps for Sentiment.
var (
	Sentiment_name = map[int32]string{
		0: "SENTIMENT_UNSPECIFIED",
		1: "SENTIMENT_POSITIVE",
		2: "SENTIMENT_NEUTRAL",
		3: "SENTIMENT_NEGATIVE",
	}
	Sentiment_value = map[string]int32{
		"SENTIMENT_UNSPECIFIED": 0,
		"SENTIMENT_POSITIVE":    1,
		"SENTIMENT_NEUTRAL":     2,
		"SENTIMENT_NEGATIVE":    3,
	}
)

func (x Sentiment) Enum() *Sentiment {
	p := new(Sentiment)
	*p = x
	return p
}

func (x Sentiment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sentiment) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_analysis_v1_analysis_proto_enumTypes[0].Descriptor()
}

func (Sentiment) Type() protoreflect.EnumType {
	return &file_ai_analysis_v1_analysis_proto_enumTypes[0]
}

func (x Sentiment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sentiment.Descriptor instead.
func (Sentiment) EnumDescriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

// Priority level for identified action items.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_MEDIUM      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_analysis_v1_analysis_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_ai_analysis_v1_analysis_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

// An entity extracted from the analyzed content.
type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name or title of the extracted entity.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Category of entity (e.g. Person, Organization, Location, Technology).
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Relevance score from 0.0 to 1.0.
	Relevance     float32 `protobuf:"fixed32,3,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Entity) GetRelevance() float32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

// A notification action demonstrating protobuf oneof.
type Notification struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Recipient string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Types that are valid to be assigned to Channel:
	//
	//	*Notification_Email
	//	*Notification_SlackChannel
	//	*Notification_WebhookUrl
	Channel       isNotification_Channel `protobuf_oneof:"channel"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Notification) GetChannel() isNotification_Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Notification) GetEmail() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Notification) GetSlackChannel() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_SlackChannel); ok {
			return x.SlackChannel
		}
	}
	return ""
}

func (x *Notification) GetWebhookUrl() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_WebhookUrl); ok {
			return x.WebhookUrl
		}
	}
	return ""
}

type isNotification_Channel interface {
	isNotification_Channel()
}

type Notification_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type Notification_SlackChannel struct {
	SlackChannel string `protobuf:"bytes,3,opt,name=slack_channel,json=slackChannel,proto3,oneof"`
}

type Notification_WebhookUrl struct {
	WebhookUrl string `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3,oneof"`
}

func (*Notification_Email) isNotification_Channel() {}

func (*Notification_SlackChannel) isNotification_Channel() {}

func (*Notification_WebhookUrl) isNotification_Channel() {}

// A suggested action item derived from the text.
type ActionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clear actionable description of the task.
	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// Urgency and priority level of the task.
	Priority Priority `protobuf:"varint,2,opt,name=priority,proto3,enum=ai.analysis.v1.Priority" json:"priority,omitempty"`
	// Optional suggested owner or role to handle this task.
	Assignee *string `protobuf:"bytes,3,opt,name=assignee,proto3,oneof" json:"assignee,omitempty"`
	// Optional notification channel to alert.
	Notification *Notification `protobuf:"bytes,4,opt,name=notification,proto3" json:"notification,omitempty"`
	// Whether this task requires immediate escalation or intervention.
	RequiresImmediateAction bool `protobuf:"varint,5,opt,name=requires_immediate_action,json=requiresImmediateAction,proto3" json:"requires_immediate_action,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActionItem) Reset() {
	*x = ActionItem{}
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionItem) ProtoMessage() {}

func (x *ActionItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionItem.ProtoReflect.Descriptor instead.
func (*ActionItem) Descriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *ActionItem) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ActionItem) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ActionItem) GetAssignee() string {
	if x != nil && x.Assignee != nil {
		return *x.Assignee
	}
	return ""
}

func (x *ActionItem) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *ActionItem) GetRequiresImmediateAction() bool {
	if x != nil {
		return x.RequiresImmediateAction
	}
	return false
}

// Comprehensive analysis report generated by an AI model.
type AnalysisReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concise title summarizing the topic.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// High-level executive summary of the content.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Overall sentiment detected in the text.
	Sentiment Sentiment `protobuf:"varint,3,opt,name=sentiment,proto3,enum=ai.analysis.v1.Sentiment" json:"sentiment,omitempty"`
	// Confidence score of the overall analysis between 0.0 and 1.0.
	ConfidenceScore float32 `protobuf:"fixed32,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	// Key takeaways and findings extracted from the text.
	KeyFindings []string `protobuf:"bytes,5,rep,name=key_findings,json=keyFindings,proto3" json:"key_findings,omitempty"`
	// Named entities mentioned in the input text.
	Entities []*Entity `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	// Recommended next steps or action items.
	ActionItems   []*ActionItem `protobuf:"bytes,7,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisReport) Reset() {
	*x = AnalysisReport{}
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisReport) ProtoMessage() {}

func (x *AnalysisReport) ProtoReflect() protoreflect.Message {
	mi := &file_ai_analysis_v1_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisReport.ProtoReflect.Descriptor instead.
func (*AnalysisReport) Descriptor() ([]byte, []int) {
	return file_ai_analysis_v1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisReport) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnalysisReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisReport) GetSentiment() Sentiment {
	if x != nil {
		return x.Sentiment
	}
	return Sentiment_SENTIMENT_UNSPECIFIED
}

func (x *AnalysisReport) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AnalysisReport) GetKeyFindings() []string {
	if x != nil {
		return x.KeyFindings
	}
	return nil
}

func (x *AnalysisReport) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *AnalysisReport) GetActionItems() []*ActionItem {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

var File_ai_analysis_v1_analysis_proto protoreflect.FileDescriptor

const file_ai_analysis_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1dai/analysis/v1/analysis.proto\x12\x0eai.analysis.v1\x1a\x14jev/v1/options.proto\"\xaa\x01\n" +
	"\x06Entity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12p\n" +
	"\trelevance\x18\x03 \x01(\x02BR\xaa\xa9#N\"L\n" +
	"\x0e\x12\fNot relevant\n" +
	"\x1e\t\x00\x00\x00\x00\x00\x00\xe0?\x12\x13Moderately relevant\n" +
	"\x1a\t\x00\x00\x00\x00\x00\x00\xf0?\x12\x0fHighly relevantR\trelevance\"\x99\x01\n" +
	"\fNotification\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12%\n" +
	"\rslack_channel\x18\x03 \x01(\tH\x00R\fslackChannel\x12!\n" +
	"\vwebhook_url\x18\x04 \x01(\tH\x00R\n" +
	"webhookUrlB\t\n" +
	"\achannel\"\x82\x02\n" +
	"\n" +
	"ActionItem\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x124\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x18.ai.analysis.v1.PriorityR\bpriority\x12\x1f\n" +
	"\bassignee\x18\x03 \x01(\tH\x00R\bassignee\x88\x01\x01\x12@\n" +
	"\fnotification\x18\x04 \x01(\v2\x1c.ai.analysis.v1.NotificationR\fnotification\x12:\n" +
	"\x19requires_immediate_action\x18\x05 \x01(\bR\x17requiresImmediateActionB\v\n" +
	"\t_assignee\"\x8e\x03\n" +
	"\x0eAnalysisReport\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x127\n" +
	"\tsentiment\x18\x03 \x01(\x0e2\x19.ai.analysis.v1.SentimentR\tsentiment\x12}\n" +
	"\x10confidence_score\x18\x04 \x01(\x02BR\xaa\xa9#N\"L\n" +
	"\x10\x12\x0eLow confidence\n" +
	"\x1c\t\x00\x00\x00\x00\x00\x00\xe0?\x12\x11Medium confidence\n" +
	"\x1a\t\x00\x00\x00\x00\x00\x00\xf0?\x12\x0fHigh confidenceR\x0fconfidenceScore\x12!\n" +
	"\fkey_findings\x18\x05 \x03(\tR\vkeyFindings\x122\n" +
	"\bentities\x18\x06 \x03(\v2\x16.ai.analysis.v1.EntityR\bentities\x12=\n" +
	"\faction_items\x18\a \x03(\v2\x1a.ai.analysis.v1.ActionItemR\vactionItems*m\n" +
	"\tSentiment\x12\x19\n" +
	"\x15SENTIMENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SENTIMENT_POSITIVE\x10\x01\x12\x15\n" +
	"\x11SENTIMENT_NEUTRAL\x10\x02\x12\x16\n" +
	"\x12SENTIMENT_NEGATIVE\x10\x03*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04B\x1bZ\x19ai/analysis/v1;analysisv1b\x06proto3"

var (
	file_ai_analysis_v1_analysis_proto_rawDescOnce sync.Once
	file_ai_analysis_v1_analysis_proto_rawDescData []byte
)

func file_ai_analysis_v1_analysis_proto_rawDescGZIP() []byte {
	file_ai_analysis_v1_analysis_proto_rawDescOnce.Do(func() {
		file_ai_analysis_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_analysis_v1_analysis_proto_rawDesc), len(file_ai_analysis_v1_analysis_proto_rawDesc)))
	})
	return file_ai_analysis_v1_analysis_proto_rawDescData
}

var file_ai_analysis_v1_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_analysis_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_analysis_v1_analysis_proto_goTypes = []any{
	(Sentiment)(0),         // 0: ai.analysis.v1.Sentiment
	(Priority)(0),          // 1: ai.analysis.v1.Priority
	(*Entity)(nil),         // 2: ai.analysis.v1.Entity
	(*Notification)(nil),   // 3: ai.analysis.v1.Notification
	(*ActionItem)(nil),     // 4: ai.analysis.v1.ActionItem
	(*AnalysisReport)(nil), // 5: ai.analysis.v1.AnalysisReport
}
var file_ai_analysis_v1_analysis_proto_depIdxs = []int32{
	1, // 0: ai.analysis.v1.ActionItem.priority:type_name -> ai.analysis.v1.Priority
	3, // 1: ai.analysis.v1.ActionItem.notification:type_name -> ai.analysis.v1.Notification
	0, // 2: ai.analysis.v1.AnalysisReport.sentiment:type_name -> ai.analysis.v1.Sentiment
	2, // 3: ai.analysis.v1.AnalysisReport.entities:type_name -> ai.analysis.v1.Entity
	4, // 4: ai.analysis.v1.AnalysisReport.action_items:type_name -> ai.analysis.v1.ActionItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ai_analysis_v1_analysis_proto_init() }
func file_ai_analysis_v1_analysis_proto_init() {
	if File_ai_analysis_v1_analysis_proto != nil {
		return
	}
	file_ai_analysis_v1_analysis_proto_msgTypes[1].OneofWrappers = []any{
		(*Notification_Email)(nil),
		(*Notification_SlackChannel)(nil),
		(*Notification_WebhookUrl)(nil),
	}
	file_ai_analysis_v1_analysis_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_analysis_v1_analysis_proto_rawDesc), len(file_ai_analysis_v1_analysis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_analysis_v1_analysis_proto_goTypes,
		DependencyIndexes: file_ai_analysis_v1_analysis_proto_depIdxs,
		EnumInfos:         file_ai_analysis_v1_analysis_proto_enumTypes,
		MessageInfos:      file_ai_analysis_v1_analysis_proto_msgTypes,
	}.Build()
	File_ai_analysis_v1_analysis_proto = out.File
	file_ai_analysis_v1_analysis_proto_goTypes = nil
	file_ai_analysis_v1_analysis_proto_depIdxs = nil
}
