// Code generated by protoc-gen-jev. DO NOT EDIT.
import { TypeSafeClient, choice, score, noul, type EntryType } from "@typesafe-ai/sdk";
import { fromJson, toJson, type JsonObject, type JsonValue, type MessageShape } from "@bufbuild/protobuf";
import { EntitySchema as JevSchema0 } from "./analysis_pb.js";
import { NotificationSchema as JevSchema1 } from "./analysis_pb.js";
import { ActionItemSchema as JevSchema2 } from "./analysis_pb.js";
import { AnalysisReportSchema as JevSchema3 } from "./analysis_pb.js";
interface Rule {
  name: string;
  type: "choice" | "noul" | "score";
  instructions: string;
  field: string;
  kind: string;
  choices?: Record<string, string>;
  levels?: { value: number; description: string }[];
  threshold: number;
  oneof?: Record<string, string>;
}

export interface Evaluation<T> {
  value: T;
  /** Complete SDK response, including answers, probabilities, confidence, model and usage. */
  response: Record<string, unknown>;
}

function object(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label}: expected an object`);
  }
  return value as Record<string, unknown>;
}

function scoreQuestion(q: Rule) {
  const descriptions = (q.levels ?? []).map(l => l.description);
  if (descriptions.length < 2) throw new Error(`${q.name}: at least two score levels are required`);
  return score(q.instructions, [descriptions[0], descriptions[1], ...descriptions.slice(2)]);
}

function questions(rules: readonly Rule[]) {
  return Object.fromEntries(rules.map(q => [q.name,
    q.type === "choice" ? choice(q.instructions, q.choices ?? {}) :
    q.type === "score" ? scoreQuestion(q) :
    noul(q.instructions)
  ]));
}

function mapResponse(response: Record<string, unknown>, rules: readonly Rule[]): JsonObject {
  const values: JsonObject = Object.create(null) as JsonObject;
  const canonical = Object.hasOwn(response, "answers");
  for (const q of rules) {
    const group = object(response[canonical ? "answers" : {choice:"choices", noul:"nouls", score:"scores"}[q.type]], q.name);
    if (!Object.hasOwn(group, q.name)) throw new Error(`Missing answer for ${q.name}`);
    const item = object(group[q.name], q.name);
    if ((canonical || Object.hasOwn(item, "type")) && item.type !== q.type) {
      throw new Error(`${q.name}: expected answer type ${q.type}`);
    }
    if (q.type === "choice") {
      const label = item.choice;
      if (typeof label !== "string" || !Object.hasOwn(q.choices ?? {}, label)) {
        throw new Error(`${q.name}: invalid choice`);
      }
      if (q.oneof) {
        if (q.oneof[label] === "bytes") {
          // Protobuf field identifiers are ASCII, so the selected label needs no Unicode conversion.
          values[label] = btoa(label);
        } else { values[label] = label; }
      } else { values[q.field] = label; }
    } else if (q.type === "noul") {
      const value = Object.hasOwn(item, "noul") ? item.noul : item.result;
      if (typeof value === "boolean") { values[q.field] = value; }
      else if (typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 1) {
        values[q.field] = value >= q.threshold;
      } else { throw new Error(`${q.name}: invalid noul`); }
    } else {
      const pos = item.score;
      const levels = q.levels ?? [];
      if (typeof pos !== "number" || !Number.isFinite(pos) || levels.length < 2 || pos < 0 || pos > levels.length - 1) {
        throw new Error(`${q.name}: invalid score`);
      }
      const i = Math.floor(pos);
      let value = levels[i].value;
      if (i + 1 < levels.length) value = (1 - (pos - i)) * value + (pos - i) * levels[i + 1].value;
      if (q.kind.startsWith("int") || q.kind.startsWith("uint")) {
        const magnitude = Math.abs(value);
        const whole = Math.floor(magnitude);
        value = Math.sign(value) * (whole + (magnitude - whole >= 0.5 ? 1 : 0));
      }
      if (!Number.isFinite(value)) throw new Error(`${q.name}: non-finite domain value`);
      values[q.field] = q.kind === "int64" || q.kind === "uint64" ? value.toFixed(0) : q.kind === "float32" ? Math.fround(value) : value;
    }
  }
  return values;
}

export class EntityJevClient {
  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}
  buildQuestions() { return questions([{"name":"relevance","type":"score","instructions":"Relevance score from 0.0 to 1.0.","field":"relevance","kind":"float32","levels":[{"value":0,"description":"Not relevant"},{"value":0.5,"description":"Moderately relevant"},{"value":1,"description":"Highly relevant"}],"threshold":0}]); }
  async evaluate(req: EntryType): Promise<MessageShape<typeof JevSchema0>> { return (await this.evaluateDetailed(req)).value; }
  async evaluateDetailed(req: EntryType): Promise<Evaluation<MessageShape<typeof JevSchema0>>> {
    const rules: Rule[] = [{"name":"relevance","type":"score","instructions":"Relevance score from 0.0 to 1.0.","field":"relevance","kind":"float32","levels":[{"value":0,"description":"Not relevant"},{"value":0.5,"description":"Moderately relevant"},{"value":1,"description":"Highly relevant"}],"threshold":0}];
    const response = object(await this.client.systemOne({state: req, questions: questions(rules)}), "response");
    return { value: fromJson(JevSchema0, mapResponse(response, rules)), response };
  }
  // Sequential execution; stops at the first error without starting later requests.
  async batchEvaluate(reqs: EntryType[]): Promise<MessageShape<typeof JevSchema0>[]> {
    const results: MessageShape<typeof JevSchema0>[] = []; for (const req of reqs) results.push(await this.evaluate(req)); return results;
  }
}
export class NotificationJevClient {
  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}
  buildQuestions() { return questions([{"name":"channel","type":"choice","instructions":"Select channel variant","field":"channel","kind":"oneof","choices":{"email":"email","slack_channel":"slack_channel","webhook_url":"webhook_url"},"threshold":0,"oneof":{"email":"string","slack_channel":"string","webhook_url":"string"}}]); }
  async evaluate(req: EntryType): Promise<MessageShape<typeof JevSchema1>> { return (await this.evaluateDetailed(req)).value; }
  async evaluateDetailed(req: EntryType): Promise<Evaluation<MessageShape<typeof JevSchema1>>> {
    const rules: Rule[] = [{"name":"channel","type":"choice","instructions":"Select channel variant","field":"channel","kind":"oneof","choices":{"email":"email","slack_channel":"slack_channel","webhook_url":"webhook_url"},"threshold":0,"oneof":{"email":"string","slack_channel":"string","webhook_url":"string"}}];
    const response = object(await this.client.systemOne({state: req, questions: questions(rules)}), "response");
    return { value: fromJson(JevSchema1, mapResponse(response, rules)), response };
  }
  // Sequential execution; stops at the first error without starting later requests.
  async batchEvaluate(reqs: EntryType[]): Promise<MessageShape<typeof JevSchema1>[]> {
    const results: MessageShape<typeof JevSchema1>[] = []; for (const req of reqs) results.push(await this.evaluate(req)); return results;
  }
}
export class ActionItemJevClient {
  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}
  buildQuestions() { return questions([{"name":"priority","type":"choice","instructions":"Urgency and priority level of the task.","field":"priority","kind":"enum","choices":{"PRIORITY_HIGH":"","PRIORITY_LOW":"","PRIORITY_MEDIUM":"","PRIORITY_URGENT":""},"threshold":0},{"name":"requiresImmediateAction","type":"noul","instructions":"Whether this task requires immediate escalation or intervention.","field":"requires_immediate_action","kind":"bool","threshold":0.5}]); }
  async evaluate(req: EntryType): Promise<MessageShape<typeof JevSchema2>> { return (await this.evaluateDetailed(req)).value; }
  async evaluateDetailed(req: EntryType): Promise<Evaluation<MessageShape<typeof JevSchema2>>> {
    const rules: Rule[] = [{"name":"priority","type":"choice","instructions":"Urgency and priority level of the task.","field":"priority","kind":"enum","choices":{"PRIORITY_HIGH":"","PRIORITY_LOW":"","PRIORITY_MEDIUM":"","PRIORITY_URGENT":""},"threshold":0},{"name":"requiresImmediateAction","type":"noul","instructions":"Whether this task requires immediate escalation or intervention.","field":"requires_immediate_action","kind":"bool","threshold":0.5}];
    const response = object(await this.client.systemOne({state: req, questions: questions(rules)}), "response");
    return { value: fromJson(JevSchema2, mapResponse(response, rules)), response };
  }
  // Sequential execution; stops at the first error without starting later requests.
  async batchEvaluate(reqs: EntryType[]): Promise<MessageShape<typeof JevSchema2>[]> {
    const results: MessageShape<typeof JevSchema2>[] = []; for (const req of reqs) results.push(await this.evaluate(req)); return results;
  }
}
export class AnalysisReportJevClient {
  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}
  buildQuestions() { return questions([{"name":"sentiment","type":"choice","instructions":"Overall sentiment detected in the text.","field":"sentiment","kind":"enum","choices":{"SENTIMENT_NEGATIVE":"","SENTIMENT_NEUTRAL":"","SENTIMENT_POSITIVE":""},"threshold":0},{"name":"confidenceScore","type":"score","instructions":"Confidence score of the overall analysis between 0.0 and 1.0.","field":"confidence_score","kind":"float32","levels":[{"value":0,"description":"Low confidence"},{"value":0.5,"description":"Medium confidence"},{"value":1,"description":"High confidence"}],"threshold":0}]); }
  async evaluate(req: EntryType): Promise<MessageShape<typeof JevSchema3>> { return (await this.evaluateDetailed(req)).value; }
  async evaluateDetailed(req: EntryType): Promise<Evaluation<MessageShape<typeof JevSchema3>>> {
    const rules: Rule[] = [{"name":"sentiment","type":"choice","instructions":"Overall sentiment detected in the text.","field":"sentiment","kind":"enum","choices":{"SENTIMENT_NEGATIVE":"","SENTIMENT_NEUTRAL":"","SENTIMENT_POSITIVE":""},"threshold":0},{"name":"confidenceScore","type":"score","instructions":"Confidence score of the overall analysis between 0.0 and 1.0.","field":"confidence_score","kind":"float32","levels":[{"value":0,"description":"Low confidence"},{"value":0.5,"description":"Medium confidence"},{"value":1,"description":"High confidence"}],"threshold":0}];
    const response = object(await this.client.systemOne({state: req, questions: questions(rules)}), "response");
    return { value: fromJson(JevSchema3, mapResponse(response, rules)), response };
  }
  // Sequential execution; stops at the first error without starting later requests.
  async batchEvaluate(reqs: EntryType[]): Promise<MessageShape<typeof JevSchema3>[]> {
    const results: MessageShape<typeof JevSchema3>[] = []; for (const req of reqs) results.push(await this.evaluate(req)); return results;
  }
}
