"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score

class EntityJevClient:
    """Typed Jev client for evaluating Entity."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "relevance": Score(
                instructions="Relevance score from 0.0 to 1.0.",
                criteria=["0.0", "0.25", "0.5", "0.75", "1.0"],
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "relevance" in resp.scores:
            out["relevance"] = resp.scores["relevance"].score
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class NotificationJevClient:
    """Typed Jev client for evaluating Notification."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "channel": Choice(
                instructions="Select channel variant",
                criteria={"email": None, "slack_channel": None, "webhook_url": None},
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "channel" in resp.choices:
            out["channel"] = resp.choices["channel"].choice
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class ActionItemJevClient:
    """Typed Jev client for evaluating ActionItem."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "priority": Choice(
                instructions="Urgency and priority level of the task.",
                criteria={"PRIORITY_HIGH": None, "PRIORITY_LOW": None, "PRIORITY_MEDIUM": None, "PRIORITY_URGENT": None},
            ),
            "requiresImmediateAction": Noul(
                instructions="Whether this task requires immediate escalation or intervention.",
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "priority" in resp.choices:
            out["priority"] = resp.choices["priority"].choice
        if "requiresImmediateAction" in resp.nouls:
            out["requires_immediate_action"] = resp.nouls["requiresImmediateAction"].result
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class AnalysisReportJevClient:
    """Typed Jev client for evaluating AnalysisReport."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "sentiment": Choice(
                instructions="Overall sentiment detected in the text.",
                criteria={"SENTIMENT_NEGATIVE": None, "SENTIMENT_NEUTRAL": None, "SENTIMENT_POSITIVE": None},
            ),
            "confidenceScore": Score(
                instructions="Confidence score of the overall analysis between 0.0 and 1.0.",
                criteria=["0.0", "0.25", "0.5", "0.75", "1.0"],
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "sentiment" in resp.choices:
            out["sentiment"] = resp.choices["sentiment"].choice
        if "confidenceScore" in resp.scores:
            out["confidence_score"] = resp.scores["confidenceScore"].score
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

