// Code generated by protoc-gen-jev. DO NOT EDIT.
package analysisv1

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"time"
	"github.com/sudorandom/protoc-gen-jev/pkg/jev"
)

type EntityJevClient struct{ jev.Client }

func NewEntityJevClient(apiKey string) *EntityJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &EntityJevClient{Client: jev.Client{APIKey: apiKey, Endpoint: "https://api.typesafe.ai/v1/systemone", Model: "jev-latest", HTTPClient: &http.Client{Timeout: 30 * time.Second}}}
}
func (c *EntityJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "relevance", Type: "score", Instructions: "Relevance score from 0.0 to 1.0.", Field: "relevance", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Not relevant"}, {Value: 0.5, Description: "Moderately relevant"}, {Value: 1, Description: "Highly relevant"}}, Oneof: map[string]string{}}})
}
func (c *EntityJevClient) Evaluate(ctx context.Context, req any) (*Entity, error) {
	result, err := c.EvaluateDetailed(ctx, req)
	if err != nil {
		return nil, err
	}
	return result.Value, nil
}
func (c *EntityJevClient) EvaluateDetailed(ctx context.Context, req any) (*jev.Evaluation[*Entity], error) {
	out := &Entity{}
	response, err := c.Client.Evaluate(ctx, req, []jev.Question{{Name: "relevance", Type: "score", Instructions: "Relevance score from 0.0 to 1.0.", Field: "relevance", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Not relevant"}, {Value: 0.5, Description: "Moderately relevant"}, {Value: 1, Description: "Highly relevant"}}, Oneof: map[string]string{}}}, out)
	if err != nil {
		return nil, err
	}
	return &jev.Evaluation[*Entity]{Value: out, Response: response}, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *EntityJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*Entity, error) {
	results := make([]*Entity, len(reqs))
	for i, req := range reqs {
		value, err := c.Evaluate(ctx, req)
		if err != nil {
			return nil, fmt.Errorf("batch item %d: %w", i, err)
		}
		results[i] = value
	}
	return results, nil
}

type NotificationJevClient struct{ jev.Client }

func NewNotificationJevClient(apiKey string) *NotificationJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &NotificationJevClient{Client: jev.Client{APIKey: apiKey, Endpoint: "https://api.typesafe.ai/v1/systemone", Model: "jev-latest", HTTPClient: &http.Client{Timeout: 30 * time.Second}}}
}
func (c *NotificationJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "channel", Type: "choice", Instructions: "Select channel variant", Field: "channel", Kind: "oneof", Threshold: 0, Choices: map[string]string{"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"}, Levels: []jev.Level{}, Oneof: map[string]string{"email": "string", "slack_channel": "string", "webhook_url": "string"}}})
}
func (c *NotificationJevClient) Evaluate(ctx context.Context, req any) (*Notification, error) {
	result, err := c.EvaluateDetailed(ctx, req)
	if err != nil {
		return nil, err
	}
	return result.Value, nil
}
func (c *NotificationJevClient) EvaluateDetailed(ctx context.Context, req any) (*jev.Evaluation[*Notification], error) {
	out := &Notification{}
	response, err := c.Client.Evaluate(ctx, req, []jev.Question{{Name: "channel", Type: "choice", Instructions: "Select channel variant", Field: "channel", Kind: "oneof", Threshold: 0, Choices: map[string]string{"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"}, Levels: []jev.Level{}, Oneof: map[string]string{"email": "string", "slack_channel": "string", "webhook_url": "string"}}}, out)
	if err != nil {
		return nil, err
	}
	return &jev.Evaluation[*Notification]{Value: out, Response: response}, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *NotificationJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*Notification, error) {
	results := make([]*Notification, len(reqs))
	for i, req := range reqs {
		value, err := c.Evaluate(ctx, req)
		if err != nil {
			return nil, fmt.Errorf("batch item %d: %w", i, err)
		}
		results[i] = value
	}
	return results, nil
}

type ActionItemJevClient struct{ jev.Client }

func NewActionItemJevClient(apiKey string) *ActionItemJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &ActionItemJevClient{Client: jev.Client{APIKey: apiKey, Endpoint: "https://api.typesafe.ai/v1/systemone", Model: "jev-latest", HTTPClient: &http.Client{Timeout: 30 * time.Second}}}
}
func (c *ActionItemJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "priority", Type: "choice", Instructions: "Urgency and priority level of the task.", Field: "priority", Kind: "enum", Threshold: 0, Choices: map[string]string{"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""}, Levels: []jev.Level{}, Oneof: map[string]string{}}, {Name: "requiresImmediateAction", Type: "noul", Instructions: "Whether this task requires immediate escalation or intervention.", Field: "requires_immediate_action", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}, Oneof: map[string]string{}}})
}
func (c *ActionItemJevClient) Evaluate(ctx context.Context, req any) (*ActionItem, error) {
	result, err := c.EvaluateDetailed(ctx, req)
	if err != nil {
		return nil, err
	}
	return result.Value, nil
}
func (c *ActionItemJevClient) EvaluateDetailed(ctx context.Context, req any) (*jev.Evaluation[*ActionItem], error) {
	out := &ActionItem{}
	response, err := c.Client.Evaluate(ctx, req, []jev.Question{{Name: "priority", Type: "choice", Instructions: "Urgency and priority level of the task.", Field: "priority", Kind: "enum", Threshold: 0, Choices: map[string]string{"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""}, Levels: []jev.Level{}, Oneof: map[string]string{}}, {Name: "requiresImmediateAction", Type: "noul", Instructions: "Whether this task requires immediate escalation or intervention.", Field: "requires_immediate_action", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}, Oneof: map[string]string{}}}, out)
	if err != nil {
		return nil, err
	}
	return &jev.Evaluation[*ActionItem]{Value: out, Response: response}, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *ActionItemJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*ActionItem, error) {
	results := make([]*ActionItem, len(reqs))
	for i, req := range reqs {
		value, err := c.Evaluate(ctx, req)
		if err != nil {
			return nil, fmt.Errorf("batch item %d: %w", i, err)
		}
		results[i] = value
	}
	return results, nil
}

type AnalysisReportJevClient struct{ jev.Client }

func NewAnalysisReportJevClient(apiKey string) *AnalysisReportJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &AnalysisReportJevClient{Client: jev.Client{APIKey: apiKey, Endpoint: "https://api.typesafe.ai/v1/systemone", Model: "jev-latest", HTTPClient: &http.Client{Timeout: 30 * time.Second}}}
}
func (c *AnalysisReportJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "sentiment", Type: "choice", Instructions: "Overall sentiment detected in the text.", Field: "sentiment", Kind: "enum", Threshold: 0, Choices: map[string]string{"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""}, Levels: []jev.Level{}, Oneof: map[string]string{}}, {Name: "confidenceScore", Type: "score", Instructions: "Confidence score of the overall analysis between 0.0 and 1.0.", Field: "confidence_score", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Low confidence"}, {Value: 0.5, Description: "Medium confidence"}, {Value: 1, Description: "High confidence"}}, Oneof: map[string]string{}}})
}
func (c *AnalysisReportJevClient) Evaluate(ctx context.Context, req any) (*AnalysisReport, error) {
	result, err := c.EvaluateDetailed(ctx, req)
	if err != nil {
		return nil, err
	}
	return result.Value, nil
}
func (c *AnalysisReportJevClient) EvaluateDetailed(ctx context.Context, req any) (*jev.Evaluation[*AnalysisReport], error) {
	out := &AnalysisReport{}
	response, err := c.Client.Evaluate(ctx, req, []jev.Question{{Name: "sentiment", Type: "choice", Instructions: "Overall sentiment detected in the text.", Field: "sentiment", Kind: "enum", Threshold: 0, Choices: map[string]string{"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""}, Levels: []jev.Level{}, Oneof: map[string]string{}}, {Name: "confidenceScore", Type: "score", Instructions: "Confidence score of the overall analysis between 0.0 and 1.0.", Field: "confidence_score", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Low confidence"}, {Value: 0.5, Description: "Medium confidence"}, {Value: 1, Description: "High confidence"}}, Oneof: map[string]string{}}}, out)
	if err != nil {
		return nil, err
	}
	return &jev.Evaluation[*AnalysisReport]{Value: out, Response: response}, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *AnalysisReportJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*AnalysisReport, error) {
	results := make([]*AnalysisReport, len(reqs))
	for i, req := range reqs {
		value, err := c.Evaluate(ctx, req)
		if err != nil {
			return nil, fmt.Errorf("batch item %d: %w", i, err)
		}
		results[i] = value
	}
	return results, nil
}
