"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from google.protobuf.json_format import MessageToDict
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score
from .analysis_pb2 import (
    ActionItem,
    AnalysisReport,
    Entity,
    Notification,
)

def _interpolate_score(s: float, levels: List[float]) -> float:
    if not levels:
        return s
    if s <= 0:
        return levels[0]
    if s >= len(levels) - 1:
        return levels[-1]
    idx = int(s)
    frac = s - idx
    return levels[idx] + frac * (levels[idx + 1] - levels[idx])

class EntityJevClient:
    """Typed Jev client for evaluating Entity."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "relevance": Score(
                instructions="Relevance score from 0.0 to 1.0.",
                criteria=["Not relevant", "Moderately relevant", "Highly relevant"],
            ),
        }

    def evaluate(self, state: Entity | Dict[str, Any] | str) -> Entity:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = Entity()
        score_relevance = None
        if hasattr(resp, "answers") and "relevance" in resp.answers:
            score_relevance = getattr(resp.answers["relevance"], "score", None)
        elif "relevance" in resp.scores:
            score_relevance = resp.scores["relevance"].score
        if score_relevance is not None:
            _s_val = _interpolate_score(score_relevance, [0, 0.5, 1])
            out.relevance = _s_val
        return out

    def batch_evaluate(self, states: List[Entity | Dict[str, Any] | str]) -> List[Entity]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class NotificationJevClient:
    """Typed Jev client for evaluating Notification."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "channel": Choice(
                instructions="Select channel variant",
                criteria={"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"},
            ),
        }

    def evaluate(self, state: Notification | Dict[str, Any] | str) -> Notification:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = Notification()
        choice_channel = None
        if hasattr(resp, "answers") and "channel" in resp.answers:
            choice_channel = getattr(resp.answers["channel"], "choice", None)
        elif "channel" in resp.choices:
            choice_channel = resp.choices["channel"].choice
        if choice_channel:
            _f_desc = out.DESCRIPTOR.fields_by_name.get(choice_channel)
            if _f_desc and _f_desc.type == 12:
                setattr(out, choice_channel, choice_channel.encode("utf-8"))
            else:
                setattr(out, choice_channel, choice_channel)
        return out

    def batch_evaluate(self, states: List[Notification | Dict[str, Any] | str]) -> List[Notification]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class ActionItemJevClient:
    """Typed Jev client for evaluating ActionItem."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "priority": Choice(
                instructions="Urgency and priority level of the task.",
                criteria={"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""},
            ),
            "requiresImmediateAction": Noul(
                instructions="Whether this task requires immediate escalation or intervention.",
            ),
        }

    def evaluate(self, state: ActionItem | Dict[str, Any] | str) -> ActionItem:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = ActionItem()
        choice_priority = None
        if hasattr(resp, "answers") and "priority" in resp.answers:
            choice_priority = getattr(resp.answers["priority"], "choice", None)
        elif "priority" in resp.choices:
            choice_priority = resp.choices["priority"].choice
        if choice_priority:
            enum_desc = out.DESCRIPTOR.fields_by_name["priority"].enum_type
            if enum_desc and choice_priority in enum_desc.values_by_name:
                setattr(out, "priority", enum_desc.values_by_name[choice_priority].number)
            else:
                try:
                    setattr(out, "priority", int(choice_priority))
                except (ValueError, TypeError):
                    pass
        noul_requiresImmediateAction = None
        if hasattr(resp, "answers") and "requiresImmediateAction" in resp.answers:
            noul_requiresImmediateAction = getattr(resp.answers["requiresImmediateAction"], "noul", None)
        elif "requiresImmediateAction" in resp.nouls:
            _item = resp.nouls["requiresImmediateAction"]
            noul_requiresImmediateAction = getattr(_item, "result", getattr(_item, "noul", False))
        if noul_requiresImmediateAction is not None:
            out.requires_immediate_action = noul_requiresImmediateAction if isinstance(noul_requiresImmediateAction, bool) else (noul_requiresImmediateAction >= 0.5 if isinstance(noul_requiresImmediateAction, (int, float)) else False)
        return out

    def batch_evaluate(self, states: List[ActionItem | Dict[str, Any] | str]) -> List[ActionItem]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

class AnalysisReportJevClient:
    """Typed Jev client for evaluating AnalysisReport."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "sentiment": Choice(
                instructions="Overall sentiment detected in the text.",
                criteria={"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""},
            ),
            "confidenceScore": Score(
                instructions="Confidence score of the overall analysis between 0.0 and 1.0.",
                criteria=["Low confidence", "Medium confidence", "High confidence"],
            ),
        }

    def evaluate(self, state: AnalysisReport | Dict[str, Any] | str) -> AnalysisReport:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = AnalysisReport()
        choice_sentiment = None
        if hasattr(resp, "answers") and "sentiment" in resp.answers:
            choice_sentiment = getattr(resp.answers["sentiment"], "choice", None)
        elif "sentiment" in resp.choices:
            choice_sentiment = resp.choices["sentiment"].choice
        if choice_sentiment:
            enum_desc = out.DESCRIPTOR.fields_by_name["sentiment"].enum_type
            if enum_desc and choice_sentiment in enum_desc.values_by_name:
                setattr(out, "sentiment", enum_desc.values_by_name[choice_sentiment].number)
            else:
                try:
                    setattr(out, "sentiment", int(choice_sentiment))
                except (ValueError, TypeError):
                    pass
        score_confidenceScore = None
        if hasattr(resp, "answers") and "confidenceScore" in resp.answers:
            score_confidenceScore = getattr(resp.answers["confidenceScore"], "score", None)
        elif "confidenceScore" in resp.scores:
            score_confidenceScore = resp.scores["confidenceScore"].score
        if score_confidenceScore is not None:
            _s_val = _interpolate_score(score_confidenceScore, [0, 0.5, 1])
            out.confidence_score = _s_val
        return out

    def batch_evaluate(self, states: List[AnalysisReport | Dict[str, Any] | str]) -> List[AnalysisReport]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

