// Code generated by protoc-gen-jev. DO NOT EDIT.
import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";
import { create, toJson, enumFromJson } from "@bufbuild/protobuf";
import {
  ActionItem,
  ActionItemSchema,
  AnalysisReport,
  AnalysisReportSchema,
  Entity,
  EntitySchema,
  Notification,
  NotificationSchema,
  PrioritySchema,
  SentimentSchema,
} from "./analysis_pb.js";

function interpolateScore(s: number, levels: number[]): number {
  if (levels.length === 0) return s;
  if (s <= 0) return levels[0];
  if (s >= levels.length - 1) return levels[levels.length - 1];
  const idx = Math.floor(s);
  const frac = s - idx;
  return levels[idx] + frac * (levels[idx + 1] - levels[idx]);
}

export class EntityJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      relevance: score(
        "Relevance score from 0.0 to 1.0.",
        ["Not relevant", "Moderately relevant", "Highly relevant"],
      ),
    };
  }

  async evaluate(state: Entity | Record<string, any> | string): Promise<Entity> {
    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(EntitySchema, state as any) : (typeof state === "string" ? { text: state } : state);
    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });
    const anyResp = resp as any;
    const result: Record<string, any> = {};
    const score_relevance = anyResp.answers?.["relevance"]?.score ?? anyResp.scores?.["relevance"]?.score;
    if (score_relevance !== undefined) {
      const sVal_relevance = interpolateScore(score_relevance, [0, 0.5, 1]);
      result["relevance"] = sVal_relevance;
    }
    return create(EntitySchema, result as any) as Entity;
  }

  async batchEvaluate(states: Array<Entity | Record<string, any> | string>): Promise<Entity[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export class NotificationJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      channel: choice(
        "Select channel variant",
        { "email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url" },
      ),
    };
  }

  async evaluate(state: Notification | Record<string, any> | string): Promise<Notification> {
    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(NotificationSchema, state as any) : (typeof state === "string" ? { text: state } : state);
    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });
    const anyResp = resp as any;
    const result: Record<string, any> = {};
    const choice_channel = anyResp.answers?.["channel"]?.choice ?? anyResp.choices?.["channel"]?.choice;
    if (choice_channel) {
      switch (choice_channel) {
        case "email":
          result["channel"] = { case: "email", value: choice_channel };
          break;
        case "slack_channel":
          result["channel"] = { case: "slackChannel", value: choice_channel };
          break;
        case "webhook_url":
          result["channel"] = { case: "webhookUrl", value: choice_channel };
          break;
      }
    }
    return create(NotificationSchema, result as any) as Notification;
  }

  async batchEvaluate(states: Array<Notification | Record<string, any> | string>): Promise<Notification[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export class ActionItemJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      priority: choice(
        "Urgency and priority level of the task.",
        { "PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": "" },
      ),
      requiresImmediateAction: noul(
        "Whether this task requires immediate escalation or intervention.",
      ),
    };
  }

  async evaluate(state: ActionItem | Record<string, any> | string): Promise<ActionItem> {
    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(ActionItemSchema, state as any) : (typeof state === "string" ? { text: state } : state);
    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });
    const anyResp = resp as any;
    const result: Record<string, any> = {};
    const choice_priority = anyResp.answers?.["priority"]?.choice ?? anyResp.choices?.["priority"]?.choice;
    if (choice_priority) {
      try { result["priority"] = enumFromJson(PrioritySchema, choice_priority); } catch { /* ignore */ }
    }
    const noul_requiresImmediateAction = anyResp.answers?.["requiresImmediateAction"]?.noul ?? anyResp.nouls?.["requiresImmediateAction"]?.result ?? anyResp.nouls?.["requiresImmediateAction"]?.noul;
    if (noul_requiresImmediateAction !== undefined) {
      result["requiresImmediateAction"] = typeof noul_requiresImmediateAction === "boolean" ? noul_requiresImmediateAction : (typeof noul_requiresImmediateAction === "number" ? noul_requiresImmediateAction >= 0.5 : false);
    }
    return create(ActionItemSchema, result as any) as ActionItem;
  }

  async batchEvaluate(states: Array<ActionItem | Record<string, any> | string>): Promise<ActionItem[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export class AnalysisReportJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      sentiment: choice(
        "Overall sentiment detected in the text.",
        { "SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": "" },
      ),
      confidenceScore: score(
        "Confidence score of the overall analysis between 0.0 and 1.0.",
        ["Low confidence", "Medium confidence", "High confidence"],
      ),
    };
  }

  async evaluate(state: AnalysisReport | Record<string, any> | string): Promise<AnalysisReport> {
    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(AnalysisReportSchema, state as any) : (typeof state === "string" ? { text: state } : state);
    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });
    const anyResp = resp as any;
    const result: Record<string, any> = {};
    const choice_sentiment = anyResp.answers?.["sentiment"]?.choice ?? anyResp.choices?.["sentiment"]?.choice;
    if (choice_sentiment) {
      try { result["sentiment"] = enumFromJson(SentimentSchema, choice_sentiment); } catch { /* ignore */ }
    }
    const score_confidenceScore = anyResp.answers?.["confidenceScore"]?.score ?? anyResp.scores?.["confidenceScore"]?.score;
    if (score_confidenceScore !== undefined) {
      const sVal_confidenceScore = interpolateScore(score_confidenceScore, [0, 0.5, 1]);
      result["confidenceScore"] = sVal_confidenceScore;
    }
    return create(AnalysisReportSchema, result as any) as AnalysisReport;
  }

  async batchEvaluate(states: Array<AnalysisReport | Record<string, any> | string>): Promise<AnalysisReport[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

