// Code generated by protoc-gen-jev. DO NOT EDIT.
package analysisv1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

const DefaultJevEndpoint = "https://api.typesafe.ai/v1/systemone"

// EntityJevDecisions holds structured decisions returned by Jev for Entity.
type EntityJevDecisions struct {
	Relevance float64 `json:"relevance"`
}

// EntityJevClient is a typed client for evaluating Entity decisions via Jev.
type EntityJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewEntityJevClient(apiKey string) *EntityJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &EntityJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *EntityJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"relevance": map[string]any{
			"type":         "score",
			"instructions": "Relevance score from 0.0 to 1.0.",
			"criteria":     []string{"0.0", "0.25", "0.5", "0.75", "1.0"},
		},
	}
}

func (c *EntityJevClient) Evaluate(ctx context.Context, state any) (*EntityJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &EntityJevDecisions{}
	if item, ok := rawResp.Answers["relevance"]; ok && item.Score != 0 {
		decisions.Relevance = item.Score
	} else if item, ok := rawResp.Scores["relevance"]; ok {
		decisions.Relevance = item.Score
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *EntityJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*EntityJevDecisions, error) {
	results := make([]*EntityJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// NotificationJevDecisions holds structured decisions returned by Jev for Notification.
type NotificationJevDecisions struct {
	Channel string `json:"channel"`
}

// NotificationJevClient is a typed client for evaluating Notification decisions via Jev.
type NotificationJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewNotificationJevClient(apiKey string) *NotificationJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &NotificationJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *NotificationJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"channel": map[string]any{
			"type":         "choice",
			"instructions": "Select channel variant",
			"criteria":     map[string]any{"email": nil, "slack_channel": nil, "webhook_url": nil},
		},
	}
}

func (c *NotificationJevClient) Evaluate(ctx context.Context, state any) (*NotificationJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &NotificationJevDecisions{}
	if item, ok := rawResp.Answers["channel"]; ok && item.Choice != "" {
		decisions.Channel = item.Choice
	} else if item, ok := rawResp.Choices["channel"]; ok {
		decisions.Channel = item.Choice
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *NotificationJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*NotificationJevDecisions, error) {
	results := make([]*NotificationJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// ActionItemJevDecisions holds structured decisions returned by Jev for ActionItem.
type ActionItemJevDecisions struct {
	Priority                string `json:"priority"`
	RequiresImmediateAction bool   `json:"requiresImmediateAction"`
}

// ActionItemJevClient is a typed client for evaluating ActionItem decisions via Jev.
type ActionItemJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewActionItemJevClient(apiKey string) *ActionItemJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &ActionItemJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *ActionItemJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"priority": map[string]any{
			"type":         "choice",
			"instructions": "Urgency and priority level of the task.",
			"criteria":     map[string]any{"PRIORITY_HIGH": nil, "PRIORITY_LOW": nil, "PRIORITY_MEDIUM": nil, "PRIORITY_URGENT": nil},
		},
		"requiresImmediateAction": map[string]any{
			"type":         "noul",
			"instructions": "Whether this task requires immediate escalation or intervention.",
		},
	}
}

func (c *ActionItemJevClient) Evaluate(ctx context.Context, state any) (*ActionItemJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &ActionItemJevDecisions{}
	if item, ok := rawResp.Answers["priority"]; ok && item.Choice != "" {
		decisions.Priority = item.Choice
	} else if item, ok := rawResp.Choices["priority"]; ok {
		decisions.Priority = item.Choice
	}
	if item, ok := rawResp.Answers["requiresImmediateAction"]; ok && item.Noul != nil {
		switch v := item.Noul.(type) {
		case bool:
			decisions.RequiresImmediateAction = v
		case float64:
			decisions.RequiresImmediateAction = v >= 0.5
		}
	} else if item, ok := rawResp.Nouls["requiresImmediateAction"]; ok {
		decisions.RequiresImmediateAction = item.Result
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *ActionItemJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*ActionItemJevDecisions, error) {
	results := make([]*ActionItemJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// AnalysisReportJevDecisions holds structured decisions returned by Jev for AnalysisReport.
type AnalysisReportJevDecisions struct {
	Sentiment       string  `json:"sentiment"`
	ConfidenceScore float64 `json:"confidenceScore"`
}

// AnalysisReportJevClient is a typed client for evaluating AnalysisReport decisions via Jev.
type AnalysisReportJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewAnalysisReportJevClient(apiKey string) *AnalysisReportJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &AnalysisReportJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *AnalysisReportJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"sentiment": map[string]any{
			"type":         "choice",
			"instructions": "Overall sentiment detected in the text.",
			"criteria":     map[string]any{"SENTIMENT_NEGATIVE": nil, "SENTIMENT_NEUTRAL": nil, "SENTIMENT_POSITIVE": nil},
		},
		"confidenceScore": map[string]any{
			"type":         "score",
			"instructions": "Confidence score of the overall analysis between 0.0 and 1.0.",
			"criteria":     []string{"0.0", "0.25", "0.5", "0.75", "1.0"},
		},
	}
}

func (c *AnalysisReportJevClient) Evaluate(ctx context.Context, state any) (*AnalysisReportJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &AnalysisReportJevDecisions{}
	if item, ok := rawResp.Answers["sentiment"]; ok && item.Choice != "" {
		decisions.Sentiment = item.Choice
	} else if item, ok := rawResp.Choices["sentiment"]; ok {
		decisions.Sentiment = item.Choice
	}
	if item, ok := rawResp.Answers["confidenceScore"]; ok && item.Score != 0 {
		decisions.ConfidenceScore = item.Score
	} else if item, ok := rawResp.Scores["confidenceScore"]; ok {
		decisions.ConfidenceScore = item.Score
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *AnalysisReportJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*AnalysisReportJevDecisions, error) {
	results := make([]*AnalysisReportJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}
