// Code generated by protoc-gen-jev. DO NOT EDIT.
package analysisv1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var (
	_ = math.Inf
	_ = proto.Marshal
)

const DefaultJevEndpoint = "https://api.typesafe.ai/v1/systemone"
const DefaultJevModel = "jev-latest"

func interpolateScore(s float64, levels []float64) float64 {
	if len(levels) == 0 {
		return s
	}
	if s <= 0 {
		return levels[0]
	}
	n := len(levels)
	if s >= float64(n-1) {
		return levels[n-1]
	}
	idx := int(s)
	frac := s - float64(idx)
	return levels[idx] + frac*(levels[idx+1]-levels[idx])
}

// EntityJevClient is a typed client for evaluating Entity decisions via Jev.
type EntityJevClient struct {
	APIKey     string
	Endpoint   string
	Model      string
	HTTPClient *http.Client
}

func NewEntityJevClient(apiKey string) *EntityJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &EntityJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		Model:      DefaultJevModel,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
	}
}

func (c *EntityJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"relevance": map[string]any{
			"type":         "score",
			"instructions": "Relevance score from 0.0 to 1.0.",
			"criteria":     []string{"Not relevant", "Moderately relevant", "Highly relevant"},
		},
	}
}

func (c *EntityJevClient) Evaluate(ctx context.Context, state any) (*Entity, error) {
	var stateJSON any
	if pm, ok := state.(proto.Message); ok {
		b, err := protojson.Marshal(pm)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal proto state: %w", err)
		}
		if err := json.Unmarshal(b, &stateJSON); err != nil {
			return nil, fmt.Errorf("failed to parse proto json state: %w", err)
		}
	} else {
		stateJSON = state
	}
	payload := map[string]any{
		"state":     stateJSON,
		"model":     c.Model,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool    `json:"result"`
			Noul   float64 `json:"noul"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &Entity{}
	var scorePos_relevance float64
	var hasScore_relevance bool
	if item, ok := rawResp.Answers["relevance"]; ok {
		scorePos_relevance = item.Score
		hasScore_relevance = true
	} else if item, ok := rawResp.Scores["relevance"]; ok {
		scorePos_relevance = item.Score
		hasScore_relevance = true
	}
	if hasScore_relevance {
		sVal := interpolateScore(scorePos_relevance, []float64{0, 0.5, 1})
		decisions.Relevance = float32(sVal)
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *EntityJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*Entity, error) {
	results := make([]*Entity, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// NotificationJevClient is a typed client for evaluating Notification decisions via Jev.
type NotificationJevClient struct {
	APIKey     string
	Endpoint   string
	Model      string
	HTTPClient *http.Client
}

func NewNotificationJevClient(apiKey string) *NotificationJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &NotificationJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		Model:      DefaultJevModel,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
	}
}

func (c *NotificationJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"channel": map[string]any{
			"type":         "choice",
			"instructions": "Select channel variant",
			"criteria":     map[string]any{"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"},
		},
	}
}

func (c *NotificationJevClient) Evaluate(ctx context.Context, state any) (*Notification, error) {
	var stateJSON any
	if pm, ok := state.(proto.Message); ok {
		b, err := protojson.Marshal(pm)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal proto state: %w", err)
		}
		if err := json.Unmarshal(b, &stateJSON); err != nil {
			return nil, fmt.Errorf("failed to parse proto json state: %w", err)
		}
	} else {
		stateJSON = state
	}
	payload := map[string]any{
		"state":     stateJSON,
		"model":     c.Model,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool    `json:"result"`
			Noul   float64 `json:"noul"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &Notification{}
	var choice_channel string
	if item, ok := rawResp.Answers["channel"]; ok && item.Choice != "" {
		choice_channel = item.Choice
	} else if item, ok := rawResp.Choices["channel"]; ok {
		choice_channel = item.Choice
	}
	if choice_channel != "" {
		switch choice_channel {
		case "email":
			decisions.Channel = &Notification_Email{Email: choice_channel}
		case "slack_channel":
			decisions.Channel = &Notification_SlackChannel{SlackChannel: choice_channel}
		case "webhook_url":
			decisions.Channel = &Notification_WebhookUrl{WebhookUrl: choice_channel}
		}
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *NotificationJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*Notification, error) {
	results := make([]*Notification, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// ActionItemJevClient is a typed client for evaluating ActionItem decisions via Jev.
type ActionItemJevClient struct {
	APIKey     string
	Endpoint   string
	Model      string
	HTTPClient *http.Client
}

func NewActionItemJevClient(apiKey string) *ActionItemJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &ActionItemJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		Model:      DefaultJevModel,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
	}
}

func (c *ActionItemJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"priority": map[string]any{
			"type":         "choice",
			"instructions": "Urgency and priority level of the task.",
			"criteria":     map[string]any{"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""},
		},
		"requiresImmediateAction": map[string]any{
			"type":         "noul",
			"instructions": "Whether this task requires immediate escalation or intervention.",
		},
	}
}

func (c *ActionItemJevClient) Evaluate(ctx context.Context, state any) (*ActionItem, error) {
	var stateJSON any
	if pm, ok := state.(proto.Message); ok {
		b, err := protojson.Marshal(pm)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal proto state: %w", err)
		}
		if err := json.Unmarshal(b, &stateJSON); err != nil {
			return nil, fmt.Errorf("failed to parse proto json state: %w", err)
		}
	} else {
		stateJSON = state
	}
	payload := map[string]any{
		"state":     stateJSON,
		"model":     c.Model,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool    `json:"result"`
			Noul   float64 `json:"noul"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &ActionItem{}
	var choice_priority string
	if item, ok := rawResp.Answers["priority"]; ok && item.Choice != "" {
		choice_priority = item.Choice
	} else if item, ok := rawResp.Choices["priority"]; ok {
		choice_priority = item.Choice
	}
	if choice_priority != "" {
		if val, ok := Priority_value[choice_priority]; ok {
			decisions.Priority = Priority(val)
		}
	}
	if item, ok := rawResp.Answers["requiresImmediateAction"]; ok && item.Noul != nil {
		switch v := item.Noul.(type) {
		case bool:
			decisions.RequiresImmediateAction = v
		case float64:
			decisions.RequiresImmediateAction = v >= 0.5
		}
	} else if item, ok := rawResp.Nouls["requiresImmediateAction"]; ok {
		if item.Noul != 0 {
			decisions.RequiresImmediateAction = item.Noul >= 0.5
		} else {
			decisions.RequiresImmediateAction = item.Result
		}
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *ActionItemJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*ActionItem, error) {
	results := make([]*ActionItem, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}

// AnalysisReportJevClient is a typed client for evaluating AnalysisReport decisions via Jev.
type AnalysisReportJevClient struct {
	APIKey     string
	Endpoint   string
	Model      string
	HTTPClient *http.Client
}

func NewAnalysisReportJevClient(apiKey string) *AnalysisReportJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &AnalysisReportJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		Model:      DefaultJevModel,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
	}
}

func (c *AnalysisReportJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"sentiment": map[string]any{
			"type":         "choice",
			"instructions": "Overall sentiment detected in the text.",
			"criteria":     map[string]any{"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""},
		},
		"confidenceScore": map[string]any{
			"type":         "score",
			"instructions": "Confidence score of the overall analysis between 0.0 and 1.0.",
			"criteria":     []string{"Low confidence", "Medium confidence", "High confidence"},
		},
	}
}

func (c *AnalysisReportJevClient) Evaluate(ctx context.Context, state any) (*AnalysisReport, error) {
	var stateJSON any
	if pm, ok := state.(proto.Message); ok {
		b, err := protojson.Marshal(pm)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal proto state: %w", err)
		}
		if err := json.Unmarshal(b, &stateJSON); err != nil {
			return nil, fmt.Errorf("failed to parse proto json state: %w", err)
		}
	} else {
		stateJSON = state
	}
	payload := map[string]any{
		"state":     stateJSON,
		"model":     c.Model,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Answers map[string]struct {
			Choice string  `json:"choice"`
			Noul   any     `json:"noul"`
			Score  float64 `json:"score"`
		} `json:"answers"`
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool    `json:"result"`
			Noul   float64 `json:"noul"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &AnalysisReport{}
	var choice_sentiment string
	if item, ok := rawResp.Answers["sentiment"]; ok && item.Choice != "" {
		choice_sentiment = item.Choice
	} else if item, ok := rawResp.Choices["sentiment"]; ok {
		choice_sentiment = item.Choice
	}
	if choice_sentiment != "" {
		if val, ok := Sentiment_value[choice_sentiment]; ok {
			decisions.Sentiment = Sentiment(val)
		}
	}
	var scorePos_confidenceScore float64
	var hasScore_confidenceScore bool
	if item, ok := rawResp.Answers["confidenceScore"]; ok {
		scorePos_confidenceScore = item.Score
		hasScore_confidenceScore = true
	} else if item, ok := rawResp.Scores["confidenceScore"]; ok {
		scorePos_confidenceScore = item.Score
		hasScore_confidenceScore = true
	}
	if hasScore_confidenceScore {
		sVal := interpolateScore(scorePos_confidenceScore, []float64{0, 0.5, 1})
		decisions.ConfidenceScore = float32(sVal)
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *AnalysisReportJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*AnalysisReport, error) {
	results := make([]*AnalysisReport, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}
