// Code generated by protoc-gen-jev. DO NOT EDIT.
import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";

export interface EntityJevDecisions {
  relevance?: number;
}

export class EntityJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      relevance: score(
        "Relevance score from 0.0 to 1.0.",
        ["0.0", "0.25", "0.5", "0.75", "1.0"],
      ),
    };
  }

  async evaluate(state: Record<string, any> | string): Promise<EntityJevDecisions> {
    const payloadState = typeof state === "string" ? { text: state } : state;
    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });
    const anyResp = resp as any;
    return {
      relevance: anyResp.answers?.["relevance"]?.score ?? anyResp.scores?.["relevance"]?.score,
    };
  }

  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<EntityJevDecisions[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export interface NotificationJevDecisions {
  channel?: string;
}

export class NotificationJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      channel: choice(
        "Select channel variant",
        { "email": null, "slack_channel": null, "webhook_url": null },
      ),
    };
  }

  async evaluate(state: Record<string, any> | string): Promise<NotificationJevDecisions> {
    const payloadState = typeof state === "string" ? { text: state } : state;
    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });
    const anyResp = resp as any;
    return {
      channel: anyResp.answers?.["channel"]?.choice ?? anyResp.choices?.["channel"]?.choice,
    };
  }

  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<NotificationJevDecisions[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export interface ActionItemJevDecisions {
  priority?: string;
  requiresImmediateAction?: boolean;
}

export class ActionItemJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      priority: choice(
        "Urgency and priority level of the task.",
        { "PRIORITY_HIGH": null, "PRIORITY_LOW": null, "PRIORITY_MEDIUM": null, "PRIORITY_URGENT": null },
      ),
      requiresImmediateAction: noul(
        "Whether this task requires immediate escalation or intervention.",
      ),
    };
  }

  async evaluate(state: Record<string, any> | string): Promise<ActionItemJevDecisions> {
    const payloadState = typeof state === "string" ? { text: state } : state;
    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });
    const anyResp = resp as any;
    return {
      priority: anyResp.answers?.["priority"]?.choice ?? anyResp.choices?.["priority"]?.choice,
      requiresImmediateAction: anyResp.answers?.["requiresImmediateAction"]?.noul ?? anyResp.nouls?.["requiresImmediateAction"]?.result,
    };
  }

  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<ActionItemJevDecisions[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

export interface AnalysisReportJevDecisions {
  sentiment?: string;
  confidenceScore?: number;
}

export class AnalysisReportJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      sentiment: choice(
        "Overall sentiment detected in the text.",
        { "SENTIMENT_NEGATIVE": null, "SENTIMENT_NEUTRAL": null, "SENTIMENT_POSITIVE": null },
      ),
      confidenceScore: score(
        "Confidence score of the overall analysis between 0.0 and 1.0.",
        ["0.0", "0.25", "0.5", "0.75", "1.0"],
      ),
    };
  }

  async evaluate(state: Record<string, any> | string): Promise<AnalysisReportJevDecisions> {
    const payloadState = typeof state === "string" ? { text: state } : state;
    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });
    const anyResp = resp as any;
    return {
      sentiment: anyResp.answers?.["sentiment"]?.choice ?? anyResp.choices?.["sentiment"]?.choice,
      confidenceScore: anyResp.answers?.["confidenceScore"]?.score ?? anyResp.scores?.["confidenceScore"]?.score,
    };
  }

  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<AnalysisReportJevDecisions[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

