package codegen

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
)

func GenerateGo(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.pb.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-jev. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P(`import ("context"; "fmt"; "net/http"; "os"; "time"; "github.com/sudorandom/protoc-gen-jev/pkg/jev")`)
	constructor := func(name string) {
		g.P("type ", name, " struct { jev.Client }")
		g.P("func New", name, "(apiKey string) *", name, " {")
		g.P(`if apiKey == "" { apiKey = os.Getenv("TYPESAFE_API_KEY") }`)
		g.P("return &", name, `{Client: jev.Client{APIKey:apiKey, Endpoint:"https://api.typesafe.ai/v1/systemone", Model:"jev-latest", HTTPClient:&http.Client{Timeout:30*time.Second}}}`)
		g.P("}")
	}
	emit := func(client, method, build, input string, spec model.MessageSpec) {
		output := g.QualifiedGoIdent(spec.Ref.GoIdent)
		g.P("func(c *", client, ") ", build, "() map[string]any { return jev.Questions(", goRules(spec), ") }")
		g.P("func(c *", client, ") ", method, "(ctx context.Context, req ", input, ") (*", output, ",error) {")
		g.P("result,err:=c.", method, "Detailed(ctx,req); if err!=nil {return nil,err}; return result.Value,nil }")
		g.P("func(c *", client, ") ", method, "Detailed(ctx context.Context, req ", input, ") (*jev.Evaluation[*", output, "],error) {")
		g.P("out:= &", output, "{}")
		g.P("response,err:=c.Client.Evaluate(ctx,req,", goRules(spec), ",out); if err!=nil{return nil,err}")
		g.P("return &jev.Evaluation[*", output, "]{Value:out,Response:response},nil }")
		g.P("// Batch", method, " evaluates requests sequentially and stops at the first error.")
		g.P("func(c *", client, ") Batch", method, "(ctx context.Context, reqs []", input, ") ([]*", output, ",error) {")
		g.P("results:=make([]*", output, ",len(reqs)); for i,req:=range reqs { value,err:=c.", method, "(ctx,req); if err!=nil{return nil,fmt.Errorf(\"batch item %d: %w\",i,err)};results[i]=value };return results,nil }")
	}
	for _, spec := range specs {
		name := spec.MessageName + "JevClient"
		constructor(name)
		emit(name, "Evaluate", "BuildQuestions", "any", spec)
	}
	for _, svc := range services {
		name := svc.ServiceName + "Client"
		constructor(name)
		for _, m := range svc.Methods {
			emit(name, m.Name, "Build"+m.Name+"Questions", "*"+g.QualifiedGoIdent(m.Input.GoIdent), m.QuestionSpec)
		}
	}
}

func goRules(spec model.MessageSpec) string {
	var items []string
	for _, q := range runtimeRules(spec) {
		var choices, levels, cases []string
		for _, key := range sortedKeys(q.Choices) {
			choices = append(choices, fmt.Sprintf("%q:%q", key, q.Choices[key]))
		}
		for _, key := range sortedKeys(q.Oneof) {
			cases = append(cases, fmt.Sprintf("%q:%q", key, q.Oneof[key]))
		}
		for _, l := range q.Levels {
			levels = append(levels, fmt.Sprintf("{Value:%s,Description:%q}", strconv.FormatFloat(l.Value, 'g', -1, 64), l.Description))
		}
		items = append(items, fmt.Sprintf("{Name:%q,Type:%q,Instructions:%q,Field:%q,Kind:%q,Threshold:%v,Choices:map[string]string{%s},Levels:[]jev.Level{%s},Oneof:map[string]string{%s}}", q.Name, q.Type, q.Instructions, q.Field, q.Kind, q.Threshold, strings.Join(choices, ","), strings.Join(levels, ","), strings.Join(cases, ",")))
	}
	return "[]jev.Question{" + strings.Join(items, ",") + "}"
}
