package codegen

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
)

// GeneratePython writes Python client classes into <file>_jev.py.
func GeneratePython(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, serviceSpecs []model.ServiceSpec) {
	filename := fmt.Sprintf("%s_jev.py", file.GeneratedFilenamePrefix)
	g := gen.NewGeneratedFile(filename, "")

	fileBase := strings.TrimSuffix(file.Desc.Path(), ".proto")
	if idx := strings.LastIndex(fileBase, "/"); idx != -1 {
		fileBase = fileBase[idx+1:]
	}

	g.P(`"""Generated by protoc-gen-jev. DO NOT EDIT."""`)
	g.P(`from typing import Any, Dict, List, Optional`)
	g.P(`from google.protobuf.json_format import MessageToDict`)
	g.P(`from typesafe_sdk import TypeSafeClient, Choice, Noul, Score`)

	// Collect unique proto classes to import
	importedClasses := make(map[string]bool)
	for _, spec := range specs {
		importedClasses[spec.MessageName] = true
	}
	for _, svc := range serviceSpecs {
		for _, m := range svc.Methods {
			importedClasses[m.InputType] = true
			importedClasses[m.OutputType] = true
		}
	}
	var classList []string
	for c := range importedClasses {
		classList = append(classList, c)
	}
	sort.Strings(classList)

	if len(classList) > 0 {
		g.P(fmt.Sprintf("from .%s_pb2 import (", fileBase))
		for _, c := range classList {
			g.P(fmt.Sprintf("    %s,", c))
		}
		g.P(")")
	}
	g.P()

	g.P(`def _interpolate_score(s: float, levels: List[float]) -> float:`)
	g.P(`    if not levels:`)
	g.P(`        return s`)
	g.P(`    if s <= 0:`)
	g.P(`        return levels[0]`)
	g.P(`    if s >= len(levels) - 1:`)
	g.P(`        return levels[-1]`)
	g.P(`    idx = int(s)`)
	g.P(`    frac = s - idx`)
	g.P(`    return levels[idx] + frac * (levels[idx + 1] - levels[idx])`)
	g.P()

	for _, spec := range specs {
		clientName := fmt.Sprintf("%sJevClient", spec.MessageName)
		outputType := spec.MessageName

		g.P(fmt.Sprintf(`class %s:`, clientName))
		g.P(fmt.Sprintf(`    """Typed Jev client for evaluating %s."""`, spec.MessageName))
		g.P()
		g.P(`    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):`)
		g.P(`        if client is not None:`)
		g.P(`            self._client = client`)
		g.P(`        elif api_key is not None:`)
		g.P(`            self._client = TypeSafeClient(api_key=api_key)`)
		g.P(`        else:`)
		g.P(`            self._client = None`)
		g.P()
		g.P(`    @property`)
		g.P(`    def client(self) -> TypeSafeClient:`)
		g.P(`        if self._client is None:`)
		g.P(`            self._client = TypeSafeClient()`)
		g.P(`        return self._client`)
		g.P()
		g.P(`    def build_questions(self) -> Dict[str, Any]:`)
		g.P(`        """Constructs the native Jev question primitives from the Protobuf schema."""`)
		g.P(`        return {`)
		for _, jsonName := range spec.Order {
			q := spec.Questions[jsonName]
			emitPyQuestion(g, jsonName, q)
		}
		g.P(`        }`)
		g.P()
		g.P(fmt.Sprintf(`    def evaluate(self, state: %s | Dict[str, Any] | str) -> %s:`, outputType, outputType))
		g.P(`        """Evaluates state against Jev System One questions and returns typed decisions."""`)
		g.P(`        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)`)
		g.P(`        questions = self.build_questions()`)
		g.P(`        resp = self.client.system_one(state=payload_state, questions=questions)`)
		emitPyResponseMapping(g, outputType, spec.Order, spec.Questions)
		g.P(`        return out`)
		g.P()
		g.P(fmt.Sprintf(`    def batch_evaluate(self, states: List[%s | Dict[str, Any] | str]) -> List[%s]:`, outputType, outputType))
		g.P(`        """Evaluates a batch of states against Jev."""`)
		g.P(`        return [self.evaluate(s) for s in states]`)
		g.P()
	}

	for _, svc := range serviceSpecs {
		clientName := fmt.Sprintf("%sClient", svc.ServiceName)
		g.P(fmt.Sprintf(`class %s:`, clientName))
		g.P(fmt.Sprintf(`    """Typed Jev client for %s."""`, svc.ServiceName))
		g.P()
		g.P(`    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):`)
		g.P(`        if client is not None:`)
		g.P(`            self._client = client`)
		g.P(`        elif api_key is not None:`)
		g.P(`            self._client = TypeSafeClient(api_key=api_key)`)
		g.P(`        else:`)
		g.P(`            self._client = None`)
		g.P()
		g.P(`    @property`)
		g.P(`    def client(self) -> TypeSafeClient:`)
		g.P(`        if self._client is None:`)
		g.P(`            self._client = TypeSafeClient()`)
		g.P(`        return self._client`)
		g.P()

		for _, m := range svc.Methods {
			pyMethodName := ToSnakeCase(m.Name)
			buildMethodName := fmt.Sprintf("build_%s_questions", pyMethodName)

			g.P(fmt.Sprintf(`    def %s(self) -> Dict[str, Any]:`, buildMethodName))
			g.P(`        """Constructs the native Jev question primitives from the Protobuf schema."""`)
			g.P(`        return {`)
			for _, jsonName := range m.QuestionSpec.Order {
				q := m.QuestionSpec.Questions[jsonName]
				emitPyQuestion(g, jsonName, q)
			}
			g.P(`        }`)
			g.P()

			g.P(fmt.Sprintf(`    def %s(self, req: %s | Dict[str, Any]) -> %s:`, pyMethodName, m.InputType, m.OutputType))
			g.P(fmt.Sprintf(`        """Evaluates %s against Jev and returns a typed %s."""`, m.InputType, m.OutputType))
			g.P(`        payload_state = MessageToDict(req, preserving_proto_field_name=True) if hasattr(req, "DESCRIPTOR") else req`)
			g.P(fmt.Sprintf(`        questions = self.%s()`, buildMethodName))
			g.P(`        resp = self.client.system_one(state=payload_state, questions=questions)`)
			emitPyResponseMapping(g, m.OutputType, m.QuestionSpec.Order, m.QuestionSpec.Questions)
			g.P(`        return out`)
			g.P()

			batchMethodName := fmt.Sprintf("batch_%s", pyMethodName)
			g.P(fmt.Sprintf(`    def %s(self, reqs: List[%s | Dict[str, Any]]) -> List[%s]:`, batchMethodName, m.InputType, m.OutputType))
			g.P(fmt.Sprintf(`        """Evaluates a batch of %s items against Jev."""`, m.InputType))
			g.P(fmt.Sprintf(`        return [self.%s(r) for r in reqs]`, pyMethodName))
			g.P()
		}
	}
}

func emitPyQuestion(g *protogen.GeneratedFile, jsonName string, q model.Question) {
	switch q.Type {
	case model.TypeChoice:
		var critKeys []string
		if m, ok := q.Criteria.(map[string]any); ok {
			var keys []string
			for k := range m {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val := fmt.Sprintf("%v", m[k])
				critKeys = append(critKeys, fmt.Sprintf("%q: %q", k, val))
			}
		}
		g.P(fmt.Sprintf(`            %q: Choice(`, jsonName))
		g.P(fmt.Sprintf(`                instructions=%q,`, q.Instructions))
		g.P(fmt.Sprintf(`                criteria={%s},`, strings.Join(critKeys, ", ")))
		g.P(`            ),`)
	case model.TypeNoul:
		g.P(fmt.Sprintf(`            %q: Noul(`, jsonName))
		g.P(fmt.Sprintf(`                instructions=%q,`, q.Instructions))
		g.P(`            ),`)
	case model.TypeScore:
		var critItems []string
		if arr, ok := q.Criteria.([]string); ok {
			for _, item := range arr {
				critItems = append(critItems, fmt.Sprintf("%q", item))
			}
		}
		g.P(fmt.Sprintf(`            %q: Score(`, jsonName))
		g.P(fmt.Sprintf(`                instructions=%q,`, q.Instructions))
		g.P(fmt.Sprintf(`                criteria=[%s],`, strings.Join(critItems, ", ")))
		g.P(`            ),`)
	}
}

func emitPyResponseMapping(g *protogen.GeneratedFile, outputType string, order []string, questions map[string]model.Question) {
	g.P(fmt.Sprintf(`        out = %s()`, outputType))
	for _, name := range order {
		q := questions[name]
		switch q.Type {
		case model.TypeChoice:
			g.P(fmt.Sprintf(`        choice_%s = None`, q.JSONField))
			g.P(fmt.Sprintf(`        if hasattr(resp, "answers") and %q in resp.answers:`, q.JSONField))
			g.P(fmt.Sprintf(`            choice_%s = getattr(resp.answers[%q], "choice", None)`, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf(`        elif %q in resp.choices:`, q.JSONField))
			g.P(fmt.Sprintf(`            choice_%s = resp.choices[%q].choice`, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf(`        if choice_%s:`, q.JSONField))
			if q.IsOneof {
				g.P(fmt.Sprintf(`            _f_desc = out.DESCRIPTOR.fields_by_name.get(choice_%s)`, q.JSONField))
				g.P(`            if _f_desc and _f_desc.type == 12:`) // 12 is FieldDescriptor.TYPE_BYTES
				g.P(fmt.Sprintf(`                setattr(out, choice_%s, choice_%s.encode("utf-8"))`, q.JSONField, q.JSONField))
				g.P(`            else:`)
				g.P(fmt.Sprintf(`                setattr(out, choice_%s, choice_%s)`, q.JSONField, q.JSONField))
			} else if q.IsEnum {
				g.P(fmt.Sprintf(`            enum_desc = out.DESCRIPTOR.fields_by_name[%q].enum_type`, q.ProtoField))
				g.P(fmt.Sprintf(`            if enum_desc and choice_%s in enum_desc.values_by_name:`, q.JSONField))
				g.P(fmt.Sprintf(`                setattr(out, %q, enum_desc.values_by_name[choice_%s].number)`, q.ProtoField, q.JSONField))
				g.P(`            else:`)
				g.P(`                try:`)
				g.P(fmt.Sprintf(`                    setattr(out, %q, int(choice_%s))`, q.ProtoField, q.JSONField))
				g.P(`                except (ValueError, TypeError):`)
				g.P(`                    pass`)
			} else {
				g.P(fmt.Sprintf(`            setattr(out, %q, choice_%s)`, q.ProtoField, q.JSONField))
			}

		case model.TypeNoul:
			threshold := q.Threshold
			if threshold <= 0 {
				threshold = 0.5
			}
			g.P(fmt.Sprintf(`        noul_%s = None`, q.JSONField))
			g.P(fmt.Sprintf(`        if hasattr(resp, "answers") and %q in resp.answers:`, q.JSONField))
			g.P(fmt.Sprintf(`            noul_%s = getattr(resp.answers[%q], "noul", None)`, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf(`        elif %q in resp.nouls:`, q.JSONField))
			g.P(fmt.Sprintf(`            _item = resp.nouls[%q]`, q.JSONField))
			g.P(fmt.Sprintf(`            noul_%s = getattr(_item, "result", getattr(_item, "noul", False))`, q.JSONField))
			g.P(fmt.Sprintf(`        if noul_%s is not None:`, q.JSONField))
			g.P(fmt.Sprintf(`            out.%s = noul_%s if isinstance(noul_%s, bool) else (noul_%s >= %v if isinstance(noul_%s, (int, float)) else False)`, q.ProtoField, q.JSONField, q.JSONField, q.JSONField, threshold, q.JSONField))

		case model.TypeScore:
			var levelVals []string
			for _, l := range q.ScoreLevels {
				levelVals = append(levelVals, fmt.Sprintf("%v", l.Value))
			}
			levelsLiteral := fmt.Sprintf("[%s]", strings.Join(levelVals, ", "))

			g.P(fmt.Sprintf(`        score_%s = None`, q.JSONField))
			g.P(fmt.Sprintf(`        if hasattr(resp, "answers") and %q in resp.answers:`, q.JSONField))
			g.P(fmt.Sprintf(`            score_%s = getattr(resp.answers[%q], "score", None)`, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf(`        elif %q in resp.scores:`, q.JSONField))
			g.P(fmt.Sprintf(`            score_%s = resp.scores[%q].score`, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf(`        if score_%s is not None:`, q.JSONField))
			g.P(fmt.Sprintf(`            _s_val = _interpolate_score(score_%s, %s)`, q.JSONField, levelsLiteral))
			if q.FieldType == "int32" || q.FieldType == "int64" || q.FieldType == "uint32" || q.FieldType == "uint64" {
				g.P(fmt.Sprintf(`            out.%s = int(round(_s_val))`, q.ProtoField))
			} else {
				g.P(fmt.Sprintf(`            out.%s = _s_val`, q.ProtoField))
			}
		}
	}
}

// ToSnakeCase converts camelCase or PascalCase to snake_case.
func ToSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
