package codegen

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
	"google.golang.org/protobuf/compiler/protogen"
)

//go:embed templates/runtime.py
var pyRuntime string

func GeneratePython(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.py", "")
	g.P(`"""Generated by protoc-gen-jev. DO NOT EDIT."""`)
	g.P("from __future__ import annotations")
	g.P("import base64\nimport json\nimport math\nfrom dataclasses import dataclass\nfrom typing import Any, Generic, TypeVar, cast")
	g.P("from google.protobuf.message import Message\nfrom google.protobuf.json_format import MessageToDict, ParseDict")
	g.P("from typesafe_sdk import TypeSafeClient, Choice, Noul, Score")
	aliases := map[*protogen.Message]string{}
	for i, m := range messages(specs, services) {
		alias := fmt.Sprintf("_pb%d", i)
		module := strings.ReplaceAll(strings.TrimSuffix(m.Desc.ParentFile().Path(), ".proto"), "/", ".") + "_pb2"
		g.P("import ", module, " as ", alias)
		aliases[m] = alias + "." + strings.Join(messagePath(m), ".")
	}
	g.P(pyRuntime)
	constructor := func(name string) {
		g.P("class ", name, ":")
		g.P("    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):")
		g.P("        self._client = client\n        self._api_key = api_key")
		g.P("    @property\n    def client(self) -> TypeSafeClient:\n        if self._client is None:\n            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()\n        return self._client")
	}
	emit := func(method, build, input, state string, spec model.MessageSpec) {
		output := aliases[spec.Ref]
		rules := "json.loads(" + strconv.Quote(rulesJSON(spec)) + ")"
		g.P("    def ", build, "(self) -> dict[str, Any]:\n        return _questions(", rules, ")")
		g.P("    def ", method, "(self, req: ", input, ") -> ", output, ":\n        return self.", method, "_detailed(req).value")
		g.P("    def ", method, "_detailed(self, req: ", input, ") -> Evaluation[", output, "]:")
		g.P("        rules = ", rules)
		g.P("        response = self.client.system_one(state=", state, ", questions=_questions(rules))")
		g.P("        value = cast(", output, ", ParseDict(_map_response(response, rules), ", output, "()))")
		g.P("        return Evaluation(value=value, response=response)")
		g.P("    def batch_", method, "(self, reqs: list[", input, "]) -> list[", output, "]:\n        return [self.", method, "(req) for req in reqs]")
	}
	for _, spec := range specs {
		constructor(spec.MessageName + "JevClient")
		emit("evaluate", "build_questions", "Message | dict[str, Any] | list[Any] | str", "MessageToDict(req) if isinstance(req, Message) else req", spec)
		g.P()
	}
	for _, svc := range services {
		constructor(svc.ServiceName + "Client")
		for _, m := range svc.Methods {
			method := ToSnakeCase(m.Name)
			emit(method, "build_"+method+"_questions", aliases[m.Input], "MessageToDict(req)", m.QuestionSpec)
		}
		g.P()
	}
}

func ToSnakeCase(s string) string {
	var out strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			out.WriteByte('_')
		}
		out.WriteRune(r)
	}
	return strings.ToLower(out.String())
}
