package codegen

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
)

// GenerateTypeScript writes TypeScript client classes into <file>_jev.ts.
func GenerateTypeScript(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, serviceSpecs []model.ServiceSpec) {
	filename := fmt.Sprintf("%s_jev.ts", file.GeneratedFilenamePrefix)
	g := gen.NewGeneratedFile(filename, "")

	fileBase := strings.TrimSuffix(file.Desc.Path(), ".proto")
	if idx := strings.LastIndex(fileBase, "/"); idx != -1 {
		fileBase = fileBase[idx+1:]
	}

	g.P(`// Code generated by protoc-gen-jev. DO NOT EDIT.`)
	g.P(`import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";`)
	g.P(`import { create, toJson, enumFromJson } from "@bufbuild/protobuf";`)

	// Collect unique types to import from ./<fileBase>_pb.js
	importedTypes := make(map[string]bool)
	for _, spec := range specs {
		importedTypes[spec.MessageName] = true
		importedTypes[fmt.Sprintf("%sSchema", spec.MessageName)] = true
		for _, q := range spec.Questions {
			if q.IsEnum && q.EnumTypeName != "" {
				importedTypes[fmt.Sprintf("%sSchema", q.EnumTypeName)] = true
			}
		}
	}
	for _, svc := range serviceSpecs {
		for _, m := range svc.Methods {
			importedTypes[m.InputType] = true
			importedTypes[fmt.Sprintf("%sSchema", m.InputType)] = true
			importedTypes[m.OutputType] = true
			importedTypes[fmt.Sprintf("%sSchema", m.OutputType)] = true
			for _, q := range m.QuestionSpec.Questions {
				if q.IsEnum && q.EnumTypeName != "" {
					importedTypes[fmt.Sprintf("%sSchema", q.EnumTypeName)] = true
				}
			}
		}
	}

	var typeList []string
	for t := range importedTypes {
		typeList = append(typeList, t)
	}
	sort.Strings(typeList)

	if len(typeList) > 0 {
		g.P(fmt.Sprintf("import {\n  %s,\n} from \"./%s_pb.js\";", strings.Join(typeList, ",\n  "), fileBase))
	}
	g.P()

	g.P(`function interpolateScore(s: number, levels: number[]): number {`)
	g.P(`  if (levels.length === 0) return s;`)
	g.P(`  if (s <= 0) return levels[0];`)
	g.P(`  if (s >= levels.length - 1) return levels[levels.length - 1];`)
	g.P(`  const idx = Math.floor(s);`)
	g.P(`  const frac = s - idx;`)
	g.P(`  return levels[idx] + frac * (levels[idx + 1] - levels[idx]);`)
	g.P(`}`)
	g.P()

	for _, spec := range specs {
		clientName := fmt.Sprintf("%sJevClient", spec.MessageName)
		outputType := spec.MessageName

		g.P(fmt.Sprintf("export class %s {", clientName))
		g.P("  private client: TypeSafeClient;")
		g.P()
		g.P("  constructor(client?: TypeSafeClient) {")
		g.P("    this.client = client ?? new TypeSafeClient();")
		g.P("  }")
		g.P()
		g.P("  buildQuestions() {")
		g.P("    return {")
		for _, jsonName := range spec.Order {
			q := spec.Questions[jsonName]
			emitTSQuestion(g, jsonName, q)
		}
		g.P("    };")
		g.P("  }")
		g.P()
		g.P(fmt.Sprintf("  async evaluate(state: %s | Record<string, any> | string): Promise<%s> {", outputType, outputType))
		g.P(fmt.Sprintf(`    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(%sSchema, state as any) : (typeof state === "string" ? { text: state } : state);`, outputType))
		g.P("    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });")
		g.P("    const anyResp = resp as any;")
		emitTSResponseMapping(g, outputType, spec.Order, spec.Questions)
		g.P("  }")
		g.P()
		g.P(fmt.Sprintf("  async batchEvaluate(states: Array<%s | Record<string, any> | string>): Promise<%s[]> {", outputType, outputType))
		g.P("    return Promise.all(states.map(state => this.evaluate(state)));")
		g.P("  }")
		g.P("}")
		g.P()
	}

	for _, svc := range serviceSpecs {
		clientName := fmt.Sprintf("%sClient", svc.ServiceName)
		g.P(fmt.Sprintf("export class %s {", clientName))
		g.P("  private client: TypeSafeClient;")
		g.P()
		g.P("  constructor(client?: TypeSafeClient) {")
		g.P("    this.client = client ?? new TypeSafeClient();")
		g.P("  }")
		g.P()

		for _, m := range svc.Methods {
			tsMethodName := m.Name
			if len(tsMethodName) > 0 {
				tsMethodName = strings.ToLower(tsMethodName[:1]) + tsMethodName[1:]
			}
			buildMethodName := fmt.Sprintf("build%sQuestions", m.Name)
			g.P(fmt.Sprintf("  %s() {", buildMethodName))
			g.P("    return {")
			for _, jsonName := range m.QuestionSpec.Order {
				q := m.QuestionSpec.Questions[jsonName]
				emitTSQuestion(g, jsonName, q)
			}
			g.P("    };")
			g.P("  }")
			g.P()

			g.P(fmt.Sprintf("  async %s(req: %s): Promise<%s> {", tsMethodName, m.InputType, m.OutputType))
			g.P(fmt.Sprintf(`    const payloadState = (req && typeof req === "object" && "$typeName" in (req as any)) ? toJson(%sSchema, req) : req;`, m.InputType))
			g.P(fmt.Sprintf("    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.%s() });", buildMethodName))
			g.P("    const anyResp = resp as any;")
			emitTSResponseMapping(g, m.OutputType, m.QuestionSpec.Order, m.QuestionSpec.Questions)
			g.P("  }")
			g.P()

			batchMethodName := fmt.Sprintf("batch%s", m.Name)
			g.P(fmt.Sprintf("  async %s(reqs: %s[]): Promise<%s[]> {", batchMethodName, m.InputType, m.OutputType))
			g.P(fmt.Sprintf("    return Promise.all(reqs.map(r => this.%s(r)));", tsMethodName))
			g.P("  }")
			g.P()
		}
		g.P("}")
		g.P()
	}
}

func emitTSQuestion(g *protogen.GeneratedFile, jsonName string, q model.Question) {
	switch q.Type {
	case model.TypeChoice:
		var critKeys []string
		if m, ok := q.Criteria.(map[string]any); ok {
			var keys []string
			for k := range m {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val := fmt.Sprintf("%v", m[k])
				critKeys = append(critKeys, fmt.Sprintf("%q: %q", k, val))
			}
		}
		g.P(fmt.Sprintf("      %s: choice(", jsonName))
		g.P(fmt.Sprintf("        %q,", q.Instructions))
		g.P(fmt.Sprintf("        { %s },", strings.Join(critKeys, ", ")))
		g.P("      ),")
	case model.TypeNoul:
		g.P(fmt.Sprintf("      %s: noul(", jsonName))
		g.P(fmt.Sprintf("        %q,", q.Instructions))
		g.P("      ),")
	case model.TypeScore:
		var critItems []string
		if arr, ok := q.Criteria.([]string); ok {
			for _, item := range arr {
				critItems = append(critItems, fmt.Sprintf("%q", item))
			}
		}
		g.P(fmt.Sprintf("      %s: score(", jsonName))
		g.P(fmt.Sprintf("        %q,", q.Instructions))
		g.P(fmt.Sprintf("        [%s],", strings.Join(critItems, ", ")))
		g.P("      ),")
	}
}

func emitTSResponseMapping(g *protogen.GeneratedFile, outputType string, order []string, questions map[string]model.Question) {
	g.P("    const result: Record<string, any> = {};")
	for _, name := range order {
		q := questions[name]
		switch q.Type {
		case model.TypeChoice:
			g.P(fmt.Sprintf("    const choice_%s = anyResp.answers?.[%q]?.choice ?? anyResp.choices?.[%q]?.choice;", q.JSONField, q.JSONField, q.JSONField))
			if q.IsOneof {
				g.P(fmt.Sprintf("    if (choice_%s) {", q.JSONField))
				g.P(fmt.Sprintf("      switch (choice_%s) {", q.JSONField))
				var oneofKeys []string
				for k := range q.OneofCases {
					oneofKeys = append(oneofKeys, k)
				}
				sort.Strings(oneofKeys)
				for _, k := range oneofKeys {
					tsCase := toCamelCase(k)
					kind := q.OneofCaseKinds[k]
					g.P(fmt.Sprintf("        case %q:", k))
					if kind == "bytes" {
						g.P(fmt.Sprintf("          result[%q] = { case: %q, value: new TextEncoder().encode(choice_%s) };", toCamelCase(q.OneofName), tsCase, q.JSONField))
					} else {
						g.P(fmt.Sprintf("          result[%q] = { case: %q, value: choice_%s };", toCamelCase(q.OneofName), tsCase, q.JSONField))
					}
					g.P("          break;")
				}
				g.P("      }")
				g.P("    }")
			} else if q.IsEnum {
				g.P(fmt.Sprintf("    if (choice_%s) {", q.JSONField))
				g.P(fmt.Sprintf("      try { result[%q] = enumFromJson(%sSchema, choice_%s); } catch { /* ignore */ }", toCamelCase(q.ProtoField), q.EnumTypeName, q.JSONField))
				g.P("    }")
			} else {
				g.P(fmt.Sprintf("    if (choice_%s) {", q.JSONField))
				g.P(fmt.Sprintf("      result[%q] = choice_%s;", toCamelCase(q.ProtoField), q.JSONField))
				g.P("    }")
			}

		case model.TypeNoul:
			threshold := q.Threshold
			if threshold <= 0 {
				threshold = 0.5
			}
			g.P(fmt.Sprintf("    const noul_%s = anyResp.answers?.[%q]?.noul ?? anyResp.nouls?.[%q]?.result ?? anyResp.nouls?.[%q]?.noul;", q.JSONField, q.JSONField, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf("    if (noul_%s !== undefined) {", q.JSONField))
			g.P(fmt.Sprintf("      result[%q] = typeof noul_%s === \"boolean\" ? noul_%s : (typeof noul_%s === \"number\" ? noul_%s >= %v : false);", toCamelCase(q.ProtoField), q.JSONField, q.JSONField, q.JSONField, q.JSONField, threshold))
			g.P("    }")

		case model.TypeScore:
			var levelVals []string
			for _, l := range q.ScoreLevels {
				levelVals = append(levelVals, fmt.Sprintf("%v", l.Value))
			}
			levelsLiteral := fmt.Sprintf("[%s]", strings.Join(levelVals, ", "))

			g.P(fmt.Sprintf("    const score_%s = anyResp.answers?.[%q]?.score ?? anyResp.scores?.[%q]?.score;", q.JSONField, q.JSONField, q.JSONField))
			g.P(fmt.Sprintf("    if (score_%s !== undefined) {", q.JSONField))
			g.P(fmt.Sprintf("      const sVal_%s = interpolateScore(score_%s, %s);", q.JSONField, q.JSONField, levelsLiteral))
			if q.FieldType == "int32" || q.FieldType == "int64" || q.FieldType == "uint32" || q.FieldType == "uint64" {
				g.P(fmt.Sprintf("      result[%q] = Math.round(sVal_%s);", toCamelCase(q.ProtoField), q.JSONField))
			} else {
				g.P(fmt.Sprintf("      result[%q] = sVal_%s;", toCamelCase(q.ProtoField), q.JSONField))
			}
			g.P("    }")
		}
	}
	g.P(fmt.Sprintf("    return create(%sSchema, result as any) as %s;", outputType, outputType))
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	var result string
	for i, p := range parts {
		if i == 0 {
			result += strings.ToLower(p)
		} else if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return result
}
