package codegen

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"protoc-gen-jev/internal/model"
)

// GenerateTypeScript writes TypeScript client classes into <file>_jev.ts.
func GenerateTypeScript(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec) {
	filename := fmt.Sprintf("%s_jev.ts", file.GeneratedFilenamePrefix)
	g := gen.NewGeneratedFile(filename, "")

	g.P(`// Code generated by protoc-gen-jev. DO NOT EDIT.`)
	g.P(`import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";`)
	g.P()

	for _, spec := range specs {
		clientName := fmt.Sprintf("%sJevClient", spec.MessageName)
		decisionsName := fmt.Sprintf("%sJevDecisions", spec.MessageName)

		// 1. Decisions interface
		g.P(fmt.Sprintf("export interface %s {", decisionsName))
		for _, name := range spec.Order {
			q := spec.Questions[name]
			switch q.Type {
			case model.TypeChoice:
				g.P(fmt.Sprintf("  %s?: string;", q.JSONField))
			case model.TypeNoul:
				g.P(fmt.Sprintf("  %s?: boolean;", q.JSONField))
			case model.TypeScore:
				g.P(fmt.Sprintf("  %s?: number;", q.JSONField))
			}
		}
		g.P("}")
		g.P()

		// 2. Client class
		g.P(fmt.Sprintf("export class %s {", clientName))
		g.P("  private client: TypeSafeClient;")
		g.P()
		g.P("  constructor(client?: TypeSafeClient) {")
		g.P("    this.client = client ?? new TypeSafeClient();")
		g.P("  }")
		g.P()
		g.P("  buildQuestions() {")
		g.P("    return {")
		for _, jsonName := range spec.Order {
			q := spec.Questions[jsonName]
			switch q.Type {
			case model.TypeChoice:
				var critKeys []string
				if m, ok := q.Criteria.(map[string]any); ok {
					var keys []string
					for k := range m {
						keys = append(keys, k)
					}
					sort.Strings(keys)
					for _, k := range keys {
						critKeys = append(critKeys, fmt.Sprintf("%q: null", k))
					}
				}
				g.P(fmt.Sprintf("      %s: choice(", jsonName))
				g.P(fmt.Sprintf("        %q,", q.Instructions))
				g.P(fmt.Sprintf("        { %s },", strings.Join(critKeys, ", ")))
				g.P("      ),")
			case model.TypeNoul:
				g.P(fmt.Sprintf("      %s: noul(", jsonName))
				g.P(fmt.Sprintf("        %q,", q.Instructions))
				g.P("      ),")
			case model.TypeScore:
				var critItems []string
				if arr, ok := q.Criteria.([]string); ok {
					for _, item := range arr {
						critItems = append(critItems, fmt.Sprintf("%q", item))
					}
				}
				g.P(fmt.Sprintf("      %s: score(", jsonName))
				g.P(fmt.Sprintf("        %q,", q.Instructions))
				g.P(fmt.Sprintf("        [%s],", strings.Join(critItems, ", ")))
				g.P("      ),")
			}
		}
		g.P("    };")
		g.P("  }")
		g.P()
		g.P(fmt.Sprintf("  async evaluate(state: Record<string, any> | string): Promise<%s> {", decisionsName))
		g.P(`    const payloadState = typeof state === "string" ? { text: state } : state;`)
		g.P("    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });")
		g.P("    const anyResp = resp as any;")
		g.P("    return {")
		for _, jsonName := range spec.Order {
			q := spec.Questions[jsonName]
			switch q.Type {
			case model.TypeChoice:
				g.P(fmt.Sprintf("      %s: anyResp.answers?.[%q]?.choice ?? anyResp.choices?.[%q]?.choice,", q.JSONField, jsonName, jsonName))
			case model.TypeNoul:
				g.P(fmt.Sprintf("      %s: anyResp.answers?.[%q]?.noul ?? anyResp.nouls?.[%q]?.result,", q.JSONField, jsonName, jsonName))
			case model.TypeScore:
				g.P(fmt.Sprintf("      %s: anyResp.answers?.[%q]?.score ?? anyResp.scores?.[%q]?.score,", q.JSONField, jsonName, jsonName))
			}
		}
		g.P("    };")
		g.P("  }")
		g.P()
		g.P(fmt.Sprintf("  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<%s[]> {", decisionsName))
		g.P("    return Promise.all(states.map(state => this.evaluate(state)));")
		g.P("  }")
		g.P("}")
		g.P()
	}
}
