package codegen

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
	"google.golang.org/protobuf/compiler/protogen"
)

//go:embed templates/runtime.ts
var tsRuntime string

func GenerateTypeScript(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.ts", "")
	g.P("// Code generated by protoc-gen-jev. DO NOT EDIT.")
	g.P(`import { TypeSafeClient, choice, score, noul, type EntryType } from "@typesafe-ai/sdk";`)
	g.P(`import { fromJson, toJson, type JsonObject, type JsonValue, type MessageShape } from "@bufbuild/protobuf";`)
	aliases := map[*protogen.Message]string{}
	for i, m := range messages(specs, services) {
		alias := fmt.Sprintf("JevSchema%d", i)
		aliases[m] = alias
		g.P(fmt.Sprintf("import { %sSchema as %s } from %q;", strings.Join(messagePath(m), "_"), alias, relativeModule(gen, file, m)))
	}
	g.P(tsRuntime)
	emit := func(method, build, input, state string, spec model.MessageSpec) {
		output := "MessageShape<typeof " + aliases[spec.Ref] + ">"
		g.P("  ", build, "() { return questions(", rulesJSON(spec), "); }")
		g.P("  async ", method, "(req: ", input, "): Promise<", output, "> { return (await this.", method, "Detailed(req)).value; }")
		g.P("  async ", method, "Detailed(req: ", input, "): Promise<Evaluation<", output, ">> {")
		g.P("    const rules: Rule[] = ", rulesJSON(spec), ";")
		g.P("    const response = object(await this.client.systemOne({state: ", state, ", questions: questions(rules)}), \"response\");")
		g.P("    return { value: fromJson(", aliases[spec.Ref], ", mapResponse(response, rules)), response };")
		g.P("  }")
		batch := "batch" + strings.ToUpper(method[:1]) + method[1:]
		g.P("  // Sequential execution; stops at the first error without starting later requests.")
		g.P("  async ", batch, "(reqs: ", input, "[]): Promise<", output, "[]> {")
		g.P("    const results: ", output, "[] = []; for (const req of reqs) results.push(await this.", method, "(req)); return results;")
		g.P("  }")
	}
	constructor := func(name string) {
		g.P("export class ", name, " {\n  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}")
	}
	for _, spec := range specs {
		constructor(spec.MessageName + "JevClient")
		emit("evaluate", "buildQuestions", "EntryType", "req", spec)
		g.P("}")
	}
	for _, svc := range services {
		constructor(svc.ServiceName + "Client")
		for _, m := range svc.Methods {
			emit(strings.ToLower(m.Name[:1])+m.Name[1:], "build"+m.Name+"Questions", "MessageShape<typeof "+aliases[m.Input]+">", "toJson("+aliases[m.Input]+", req) as EntryType", m.QuestionSpec)
		}
		g.P("}")
	}
}
