// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file jev/v1/options.proto (package jev.v1, syntax proto3)
/* eslint-disable */

// Field options for compiling Protocol Buffer definitions to TypeSafe AI's Jev cognitive model.
//
// By defining your data models and decision questions once in Protobuf, you get type-safe
// decisions directly from Jev. Instead of hand-crafting schema payloads and parsing untyped JSON,
// you can define your decision schemas in Protobuf and consume strongly typed results seamlessly
// across Go, TypeScript, and Python using their native generated types.
//
// Jev is a non-autoregressive "System One" cognitive AI model developed by TypeSafe AI
// (https://typesafe.ai) designed for fast, structured classification and evaluation rather
// than generative text output. Inspired by Daniel Kahneman's dual-process cognitive theory
// ("Thinking, Fast and Slow"), Jev evaluates multiple structured questions in parallel against
// an unstructured input state via Jev System One.
//
// These options annotate Protobuf messages to specify how fields map to Jev's three core primitives:
//   - Choice: Discrete selection among predefined criteria (mapped to enums, oneofs, or string whitelists).
//   - Score:  Numerical evaluation against an ordered scale or rubric (mapped to floats or ints).
//   - Noul:   Binary yes/no classification returning truth probability (mapped to booleans).
//
// For details on TypeSafe AI and Jev System One architecture:
//   - TypeSafe AI: https://typesafe.ai
//   - Documentation: https://docs.typesafe.ai

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions as FieldOptions$1, MethodOptions as MethodOptions$1, ServiceOptions as ServiceOptions$1 } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jev/v1/options.proto.
 */
export const file_jev_v1_options: GenFile = /*@__PURE__*/
  fileDesc("ChRqZXYvdjEvb3B0aW9ucy5wcm90bxIGamV2LnYxIjIKDlNlcnZpY2VPcHRpb25zEhQKB2VuYWJsZWQYASABKAhIAIgBAUIKCghfZW5hYmxlZCIxCg1NZXRob2RPcHRpb25zEhQKB2VuYWJsZWQYASABKAhIAIgBAUIKCghfZW5hYmxlZCKbAQoMRmllbGRPcHRpb25zEhQKDGluc3RydWN0aW9ucxgBIAEoCRIMCgRza2lwGAIgASgIEiMKBmNob2ljZRgDIAEoCzITLmpldi52MS5DaG9pY2VSdWxlcxIhCgVzY29yZRgEIAEoCzISLmpldi52MS5TY29yZVJ1bGVzEh8KBG5vdWwYBSABKAsyES5qZXYudjEuTm91bFJ1bGVzIpQBCgtDaG9pY2VSdWxlcxIPCgdjaG9pY2VzGAEgAygJEg4KBm5vdF9pbhgCIAMoCRIzCghjcml0ZXJpYRgDIAMoCzIhLmpldi52MS5DaG9pY2VSdWxlcy5Dcml0ZXJpYUVudHJ5Gi8KDUNyaXRlcmlhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIwCgpTY29yZUxldmVsEg0KBXZhbHVlGAEgASgBEhMKC2Rlc2NyaXB0aW9uGAIgASgJIjAKClNjb3JlUnVsZXMSIgoGbGV2ZWxzGAEgAygLMhIuamV2LnYxLlNjb3JlTGV2ZWwiMQoJTm91bFJ1bGVzEhYKCXRocmVzaG9sZBgBIAEoAkgAiAEBQgwKCl90aHJlc2hvbGQ6SwoFZmllbGQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGJW1BCABKAsyFC5qZXYudjEuRmllbGRPcHRpb25zUgVmaWVsZDpTCgdzZXJ2aWNlEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGJa1BCABKAsyFi5qZXYudjEuU2VydmljZU9wdGlvbnNSB3NlcnZpY2U6TwoGbWV0aG9kEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYl7UEIAEoCzIVLmpldi52MS5NZXRob2RPcHRpb25zUgZtZXRob2RCN1o1Z2l0aHViLmNvbS9zdWRvcmFuZG9tL3Byb3RvYy1nZW4tamV2L3BrZy9qZXYvdjE7amV2djFiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * ServiceOptions specifies how an entire Protobuf service is processed by Jev.
 *
 * @generated from message jev.v1.ServiceOptions
 */
export type ServiceOptions = Message<"jev.v1.ServiceOptions"> & {
  /**
   * Controls Jev code generation for this service.
   *   - unset (default): Auto-discovers Jev RPCs if request/response types use (jev.v1.field) options.
   *   - true: Force-enables all RPCs in this service as Jev decision services (enables natural type mappings).
   *   - false: Explicitly skips this service during code generation.
   *
   * @generated from field: optional bool enabled = 1;
   */
  enabled?: boolean | undefined;
};

/**
 * Describes the message jev.v1.ServiceOptions.
 * Use `create(ServiceOptionsSchema)` to create a new message.
 */
export const ServiceOptionsSchema: GenMessage<ServiceOptions> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 0);

/**
 * MethodOptions specifies how an individual RPC method is processed by Jev.
 *
 * @generated from message jev.v1.MethodOptions
 */
export type MethodOptions = Message<"jev.v1.MethodOptions"> & {
  /**
   * Controls Jev code generation for this RPC method.
   *   - unset (default): Auto-discovers if request/response types use (jev.v1.field) options.
   *   - true: Force-enables this RPC as a Jev decision RPC (enables natural type mappings).
   *   - false: Explicitly skips this RPC during code generation.
   *
   * @generated from field: optional bool enabled = 1;
   */
  enabled?: boolean | undefined;
};

/**
 * Describes the message jev.v1.MethodOptions.
 * Use `create(MethodOptionsSchema)` to create a new message.
 */
export const MethodOptionsSchema: GenMessage<MethodOptions> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 1);

/**
 * FieldOptions specifies how an individual Protobuf field is evaluated by Jev System One.
 *
 * See: https://docs.typesafe.ai (TypeSafe AI Jev Concept Overview)
 *
 * @generated from message jev.v1.FieldOptions
 */
export type FieldOptions = Message<"jev.v1.FieldOptions"> & {
  /**
   * Explicit prompt instructions for Jev when evaluating this question.
   *
   * Jev uses these instructions as natural language guidance for the cognitive evaluation.
   * If omitted, the field's leading Protobuf doc comment is used as the instructions.
   *
   * See: https://docs.typesafe.ai/primitives (Question Instructions)
   *
   * @generated from field: string instructions = 1;
   */
  instructions: string;

  /**
   * If true, Jev skips this field entirely during question generation.
   * Useful for fields populated by downstream systems, entity IDs, or freeform text.
   *
   * @generated from field: bool skip = 2;
   */
  skip: boolean;

  /**
   * Configuration rules for a [Jev Choice primitive](https://docs.typesafe.ai/primitives/choice) question.
   *
   * A Choice question selects exactly one option from a discrete set of candidates
   * (up to 255 options) and returns the chosen value with associated confidence probabilities.
   *
   * @generated from field: jev.v1.ChoiceRules choice = 3;
   */
  choice?: ChoiceRules | undefined;

  /**
   * Configuration rules for a [Jev Score primitive](https://docs.typesafe.ai/primitives/score) question.
   *
   * A Score question rates the input state against an ordered numerical rubric scale
   * and returns a probability-weighted score.
   *
   * @generated from field: jev.v1.ScoreRules score = 4;
   */
  score?: ScoreRules | undefined;

  /**
   * Configuration rules for a [Jev Noul primitive](https://docs.typesafe.ai/primitives/noul) question.
   *
   * A Noul question performs binary yes/no classification, evaluating whether a statement
   * or condition holds true based on the provided instructions, returning a calibrated probability.
   *
   * @generated from field: jev.v1.NoulRules noul = 5;
   */
  noul?: NoulRules | undefined;
};

/**
 * Describes the message jev.v1.FieldOptions.
 * Use `create(FieldOptionsSchema)` to create a new message.
 */
export const FieldOptionsSchema: GenMessage<FieldOptions> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 2);

/**
 * ChoiceRules configures a Jev Choice question (discrete categorical classification).
 *
 * @generated from message jev.v1.ChoiceRules
 */
export type ChoiceRules = Message<"jev.v1.ChoiceRules"> & {
  /**
   * Explicit whitelist of allowed choice values for string or enum fields.
   * When set on an enum, only listed enum values will be included in the Jev choice criteria.
   *
   * @generated from field: repeated string choices = 1;
   */
  choices: string[];

  /**
   * Blacklist of enum value names to exclude from Jev choice criteria (e.g. legacy or internal variants).
   *
   * @generated from field: repeated string not_in = 2;
   */
  notIn: string[];

  /**
   * [Rubric or descriptive guidance](https://docs.typesafe.ai/primitives) mapped to specific choice options (label -> description).
   *
   * @generated from field: map<string, string> criteria = 3;
   */
  criteria: { [key: string]: string };
};

/**
 * Describes the message jev.v1.ChoiceRules.
 * Use `create(ChoiceRulesSchema)` to create a new message.
 */
export const ChoiceRulesSchema: GenMessage<ChoiceRules> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 3);

/**
 * ScoreLevel defines a discrete point or tier on an evaluation rubric.
 *
 * @generated from message jev.v1.ScoreLevel
 */
export type ScoreLevel = Message<"jev.v1.ScoreLevel"> & {
  /**
   * Target numerical domain value (e.g. 1.0, 5.0, 100.0).
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Semantic description or rubric guidance passed to Jev for this level.
   *
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message jev.v1.ScoreLevel.
 * Use `create(ScoreLevelSchema)` to create a new message.
 */
export const ScoreLevelSchema: GenMessage<ScoreLevel> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 4);

/**
 * ScoreRules configures a Jev Score question (numerical scale / rubric evaluation).
 *
 * Models quantitative ratings and confidence assessments along an ordered scale.
 *
 * See: https://docs.typesafe.ai/primitives/score (Score Question Specification)
 *
 * @generated from message jev.v1.ScoreRules
 */
export type ScoreRules = Message<"jev.v1.ScoreRules"> & {
  /**
   * Explicit ordered rubric levels with domain values and descriptions.
   *
   * @generated from field: repeated jev.v1.ScoreLevel levels = 1;
   */
  levels: ScoreLevel[];
};

/**
 * Describes the message jev.v1.ScoreRules.
 * Use `create(ScoreRulesSchema)` to create a new message.
 */
export const ScoreRulesSchema: GenMessage<ScoreRules> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 5);

/**
 * NoulRules configures a Jev Noul question (binary yes/no condition classification).
 *
 * Models binary boolean assertions, risk flags, and safety gates.
 *
 * See: https://docs.typesafe.ai/primitives/noul (Noul Question Specification)
 *
 * @generated from message jev.v1.NoulRules
 */
export type NoulRules = Message<"jev.v1.NoulRules"> & {
  /**
   * Confidence threshold [0.0 - 1.0] required for the condition to evaluate as true.
   * Default is 0.5.
   *
   * @generated from field: optional float threshold = 1;
   */
  threshold?: number | undefined;
};

/**
 * Describes the message jev.v1.NoulRules.
 * Use `create(NoulRulesSchema)` to create a new message.
 */
export const NoulRulesSchema: GenMessage<NoulRules> = /*@__PURE__*/
  messageDesc(file_jev_v1_options, 6);

/**
 * Annotation extending Protobuf field definitions with Jev evaluation directives.
 *
 * @generated from extension: jev.v1.FieldOptions field = 72341;
 */
export const field: GenExtension<FieldOptions$1, FieldOptions> = /*@__PURE__*/
  extDesc(file_jev_v1_options, 0);

/**
 * Annotation extending Protobuf service definitions with Jev evaluation directives.
 *
 * @generated from extension: jev.v1.ServiceOptions service = 72342;
 */
export const service: GenExtension<ServiceOptions$1, ServiceOptions> = /*@__PURE__*/
  extDesc(file_jev_v1_options, 1);

/**
 * Annotation extending Protobuf method definitions with Jev evaluation directives.
 *
 * @generated from extension: jev.v1.MethodOptions method = 72343;
 */
export const method: GenExtension<MethodOptions$1, MethodOptions> = /*@__PURE__*/
  extDesc(file_jev_v1_options, 2);

