// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/shared/v1/shared.proto (package ai.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/shared/v1/shared.proto.
 */
export const file_ai_shared_v1_shared: GenFile = /*@__PURE__*/
  fileDesc("ChlhaS9zaGFyZWQvdjEvc2hhcmVkLnByb3RvEgxhaS5zaGFyZWQudjEiJQoPRXh0ZXJuYWxSZXF1ZXN0EhIKCmlucHV0X3RleHQYASABKAkiJAoQRXh0ZXJuYWxSZXNwb25zZRIQCghhY2NlcHRlZBgBIAEoCCpGCgZTdGF0dXMSFgoSU1RBVFVTX1VOU1BFQ0lGSUVEEAASEAoMU1RBVFVTX1JFQURZEAESEgoOU1RBVFVTX0JMT0NLRUQQAkJEWkJnaXRodWIuY29tL3N1ZG9yYW5kb20vcHJvdG9jLWdlbi1qZXYvZ2VuL2pldi9haS9zaGFyZWQvdjE7c2hhcmVkdjFiBnByb3RvMw");

/**
 * @generated from message ai.shared.v1.ExternalRequest
 */
export type ExternalRequest = Message<"ai.shared.v1.ExternalRequest"> & {
  /**
   * @generated from field: string input_text = 1;
   */
  inputText: string;
};

/**
 * Describes the message ai.shared.v1.ExternalRequest.
 * Use `create(ExternalRequestSchema)` to create a new message.
 */
export const ExternalRequestSchema: GenMessage<ExternalRequest> = /*@__PURE__*/
  messageDesc(file_ai_shared_v1_shared, 0);

/**
 * @generated from message ai.shared.v1.ExternalResponse
 */
export type ExternalResponse = Message<"ai.shared.v1.ExternalResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;
};

/**
 * Describes the message ai.shared.v1.ExternalResponse.
 * Use `create(ExternalResponseSchema)` to create a new message.
 */
export const ExternalResponseSchema: GenMessage<ExternalResponse> = /*@__PURE__*/
  messageDesc(file_ai_shared_v1_shared, 1);

/**
 * @generated from enum ai.shared.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: STATUS_BLOCKED = 2;
   */
  BLOCKED = 2,
}

/**
 * Describes the enum ai.shared.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_ai_shared_v1_shared, 0);

