"""Generated by protoc-gen-jev. DO NOT EDIT."""
from __future__ import annotations
import base64
import json
import math
from dataclasses import dataclass
from typing import Any, Generic, TypeVar, cast
from google.protobuf.message import Message
from google.protobuf.json_format import MessageToDict, ParseDict
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score
import ai.shared.v1.shared_pb2 as _pb0
_T = TypeVar("_T", bound=Message)

@dataclass(frozen=True)
class Evaluation(Generic[_T]):
    value: _T
    # Original SDK response: answers, probabilities, confidence, model and usage.
    response: Any


def _questions(rules: list[dict[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for q in rules:
        if q["type"] == "choice":
            result[q["name"]] = Choice(instructions=q["instructions"], criteria=q["choices"])
        elif q["type"] == "score":
            result[q["name"]] = Score(instructions=q["instructions"], criteria=[l["description"] for l in q["levels"]])
        else:
            result[q["name"]] = Noul(instructions=q["instructions"])
    return result


def _get(obj: Any, key: str, default: Any = None) -> Any:
    return obj.get(key, default) if isinstance(obj, dict) else getattr(obj, key, default)


def _map_response(response: Any, rules: list[dict[str, Any]]) -> dict[str, Any]:
    values: dict[str, Any] = {}
    sentinel = object()
    answers = _get(response, "answers", sentinel)
    canonical = answers is not sentinel
    for q in rules:
        group = answers if canonical else _get(response, {"choice":"choices", "noul":"nouls", "score":"scores"}[q["type"]])
        if not isinstance(group, dict) or q["name"] not in group:
            raise ValueError(f"Missing answer for {q['name']}")
        item = group[q["name"]]
        kind = _get(item, "type", sentinel)
        if (canonical or kind is not sentinel) and kind != q["type"]:
            raise ValueError(f"{q['name']}: expected answer type {q['type']}")
        if q["type"] == "choice":
            label = _get(item, "choice")
            if not isinstance(label, str) or label not in q["choices"]:
                raise ValueError(f"{q['name']}: invalid choice")
            if q.get("oneof"):
                values[label] = base64.b64encode(label.encode("ascii")).decode("ascii") if q["oneof"][label] == "bytes" else label
            else:
                values[q["field"]] = label
        elif q["type"] == "noul":
            value = _get(item, "noul", sentinel)
            if value is sentinel:
                value = _get(item, "result")
            if isinstance(value, bool):
                values[q["field"]] = value
            elif isinstance(value, (int, float)) and math.isfinite(value) and 0 <= value <= 1:
                values[q["field"]] = value >= q["threshold"]
            else:
                raise ValueError(f"{q['name']}: invalid noul")
        else:
            pos = _get(item, "score")
            levels = q["levels"]
            if isinstance(pos, bool) or not isinstance(pos, (int, float)) or not math.isfinite(pos) or not 0 <= pos <= len(levels)-1:
                raise ValueError(f"{q['name']}: invalid score")
            i = int(pos)
            value = float(levels[i]["value"])
            if i + 1 < len(levels):
                value = (1 - (pos - i)) * value + (pos - i) * levels[i + 1]["value"]
            if not math.isfinite(value):
                raise ValueError(f"{q['name']}: non-finite domain value")
            if q["kind"].startswith(("int", "uint")):
                whole = math.floor(abs(value))
                value = math.copysign(whole + (1 if abs(value) - whole >= 0.5 else 0), value)
            values[q["field"]] = str(int(value)) if q["kind"] in ("int64", "uint64") else value
    return values

class ExternalResponseJevClient:
    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):
        self._client = client
        self._api_key = api_key
    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()
        return self._client
    def build_questions(self) -> dict[str, Any]:
        return _questions(json.loads("[{\"name\":\"accepted\",\"type\":\"noul\",\"instructions\":\"Evaluate accepted\",\"field\":\"accepted\",\"kind\":\"bool\",\"threshold\":0.5}]"))
    def evaluate(self, req: Message | dict[str, Any] | list[Any] | str) -> _pb0.ExternalResponse:
        return self.evaluate_detailed(req).value
    def evaluate_detailed(self, req: Message | dict[str, Any] | list[Any] | str) -> Evaluation[_pb0.ExternalResponse]:
        rules = json.loads("[{\"name\":\"accepted\",\"type\":\"noul\",\"instructions\":\"Evaluate accepted\",\"field\":\"accepted\",\"kind\":\"bool\",\"threshold\":0.5}]")
        response = self.client.system_one(state=MessageToDict(req) if isinstance(req, Message) else req, questions=_questions(rules))
        value = cast(_pb0.ExternalResponse, ParseDict(_map_response(response, rules), _pb0.ExternalResponse()))
        return Evaluation(value=value, response=response)
    def batch_evaluate(self, reqs: list[Message | dict[str, Any] | list[Any] | str]) -> list[_pb0.ExternalResponse]:
        return [self.evaluate(req) for req in reqs]

