# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/shared/v1/shared.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'ai/shared/v1/shared.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61i/shared/v1/shared.proto\x12\x0c\x61i.shared.v1\"0\n\x0f\x45xternalRequest\x12\x1d\n\ninput_text\x18\x01 \x01(\tR\tinputText\".\n\x10\x45xternalResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted*F\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATUS_READY\x10\x01\x12\x12\n\x0eSTATUS_BLOCKED\x10\x02\x42\x44ZBgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/shared/v1;sharedv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.shared.v1.shared_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/shared/v1;sharedv1'
  _globals['_STATUS']._serialized_start=141
  _globals['_STATUS']._serialized_end=211
  _globals['_EXTERNALREQUEST']._serialized_start=43
  _globals['_EXTERNALREQUEST']._serialized_end=91
  _globals['_EXTERNALRESPONSE']._serialized_start=93
  _globals['_EXTERNALRESPONSE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
