# Generated from ai/contract/v1/contract.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.5.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ....jev.v1 import options_pb
from ...shared.v1 import shared_pb

if TYPE_CHECKING:
    from protobuf import DescFile, Oneof

    from ...shared.v1.shared_pb import Status


_EvaluateRequestFields: TypeAlias = Literal["input_text", "input_count"]

class EvaluateRequest(Message[_EvaluateRequestFields]):
    """
    ```proto
    message ai.contract.v1.EvaluateRequest
    ```

    Attributes:
        input_text:
            ```proto
            string input_text = 1;
            ```
        input_count:
            ```proto
            uint64 input_count = 2;
            ```
    """

    __slots__ = ("input_text", "input_count")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            input_text: str = "",
            input_count: int = 0,
        ) -> None:
            pass

        input_text: str
        input_count: int

_EvaluateResponseFields: TypeAlias = Literal["flag", "rating", "count", "big_count", "big_unsigned", "fixed_count", "signed_fixed_count", "risk", "status", "label", "boundary", "email", "binary", "excluded"]

class EvaluateResponse(Message[_EvaluateResponseFields]):
    """
    ```proto
    message ai.contract.v1.EvaluateResponse
    ```

    Attributes:
        flag:
            ```proto
            optional bool flag = 1;
            ```
        rating:
            ```proto
            optional int32 rating = 2;
            ```
        count:
            ```proto
            uint32 count = 3;
            ```
        big_count:
            ```proto
            int64 big_count = 4;
            ```
        big_unsigned:
            ```proto
            uint64 big_unsigned = 5;
            ```
        fixed_count:
            ```proto
            fixed32 fixed_count = 6;
            ```
        signed_fixed_count:
            ```proto
            sfixed64 signed_fixed_count = 7;
            ```
        risk:
            ```proto
            bool risk = 8 [json_name = "risk-flag"];
            ```
        status:
            ```proto
            ai.shared.v1.Status status = 9;
            ```
        label:
            ```proto
            optional string label = 10;
            ```
        boundary:
            ```proto
            int64 boundary = 14;
            ```
        route:
            ```proto
            oneof route
            ```
    """

    __slots__ = ("flag", "rating", "count", "big_count", "big_unsigned", "fixed_count", "signed_fixed_count", "risk", "status", "label", "boundary", "route")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            flag: bool | None = None,
            rating: int | None = None,
            count: int = 0,
            big_count: int = 0,
            big_unsigned: int = 0,
            fixed_count: int = 0,
            signed_fixed_count: int = 0,
            risk: bool = False,
            status: Status | None = None,
            label: str | None = None,
            boundary: int = 0,
            route: Oneof[Literal["email"], str] | Oneof[Literal["binary"], bytes] | Oneof[Literal["excluded"], str] | None = None,
        ) -> None:
            pass

        flag: bool
        rating: int
        count: int
        big_count: int
        big_unsigned: int
        fixed_count: int
        signed_fixed_count: int
        risk: bool
        status: Status
        label: str
        boundary: int
        route: Oneof[Literal["email"], str] | Oneof[Literal["binary"], bytes] | Oneof[Literal["excluded"], str] | None

_ContainerFields: TypeAlias = NoReturn

class Container(Message[_ContainerFields]):
    """
    ```proto
    message ai.contract.v1.Container
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

    _NestedRequestFields: TypeAlias = Literal["input_text"]

    class NestedRequest(Message[_NestedRequestFields]):
        """
        ```proto
        message ai.contract.v1.Container.NestedRequest
        ```

        Attributes:
            input_text:
                ```proto
                string input_text = 1;
                ```
        """

        __slots__ = ("input_text",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                input_text: str = "",
            ) -> None:
                pass

            input_text: str

    _NestedResponseFields: TypeAlias = Literal["accepted"]

    class NestedResponse(Message[_NestedResponseFields]):
        """
        ```proto
        message ai.contract.v1.Container.NestedResponse
        ```

        Attributes:
            accepted:
                ```proto
                optional bool accepted = 1;
                ```
        """

        __slots__ = ("accepted",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                accepted: bool | None = None,
            ) -> None:
                pass

            accepted: bool


_DESC = file_desc(
    b'\n\x1dai/contract/v1/contract.proto\x12\x0eai.contract.v1\x1a\x14jev/v1/options.proto\x1a\x19ai/shared/v1/shared.proto"Q\n\x0fEvaluateRequest\x12\x1d\n\ninput_text\x18\x01 \x01(\tR\tinputText\x12\x1f\n\x0binput_count\x18\x02 \x01(\x04R\ninputCount"\xda\x04\n\x10EvaluateResponse\x12$\n\x04flag\x18\x01 \x01(\x08H\x01R\x04flagB\x0b\xaa\xa9#\x07*\x05\r\x00\x00\x00\x00\x88\x01\x01\x12D\n\x06rating\x18\x02 \x01(\x05H\x02R\x06ratingB\'\xaa\xa9##"!\n\x0e\t\x00\x00\x00\x00\x00\x00\x08\xc0\x12\x03Low\n\x0f\t\x00\x00\x00\x00\x00\x00\x00\xc0\x12\x04High\x88\x01\x01\x12\x14\n\x05count\x18\x03 \x01(\rR\x05count\x12\x1b\n\tbig_count\x18\x04 \x01(\x03R\x08bigCount\x12!\n\x0cbig_unsigned\x18\x05 \x01(\x04R\x0bbigUnsigned\x12\x1f\n\x0bfixed_count\x18\x06 \x01(\x07R\nfixedCount\x12,\n\x12signed_fixed_count\x18\x07 \x01(\x10R\x10signedFixedCount\x12\x17\n\x04risk\x18\x08 \x01(\x08R\trisk-flag\x12,\n\x06status\x18\t \x01(\x0e2\x14.ai.shared.v1.StatusR\x06status\x12*\n\x05label\x18\n \x01(\tH\x03R\x05labelB\x0f\xaa\xa9#\x0b\x1a\t\n\x03YES\n\x02NO\x88\x01\x01\x12C\n\x08boundary\x18\x0e \x01(\x03R\x08boundaryB\'\xaa\xa9##"!\n\x0e\t\xfe\xff\xff\xff\xff\xff?C\x12\x03Low\n\x0f\t\xff\xff\xff\xff\xff\xff?C\x12\x04High\x12\x16\n\x05email\x18\x0b \x01(\tH\x00R\x05email\x12\x18\n\x06binary\x18\x0c \x01(\x0cH\x00R\x06binary\x12$\n\x08excluded\x18\r \x01(\tH\x00R\x08excludedB\x06\xaa\xa9#\x02\x10\x01B\x07\n\x05routeB\x07\n\x05_flagB\t\n\x07_ratingB\x08\n\x06_label"{\n\tContainer\x1a.\n\rNestedRequest\x12\x1d\n\ninput_text\x18\x01 \x01(\tR\tinputText\x1a>\n\x0eNestedResponse\x12\x1f\n\x08accepted\x18\x01 \x01(\x08H\x00R\x08accepted\x88\x01\x01B\x0b\n\t_acceptedBHZFgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/contract/v1;contractv1b\x06proto3',
    [
        options_pb.desc(),
        shared_pb.desc(),
    ],
    {
        "EvaluateRequest": EvaluateRequest,
        "EvaluateResponse": EvaluateResponse,
        "Container": Container,
        "Container.NestedRequest": Container.NestedRequest,
        "Container.NestedResponse": Container.NestedResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `ai/contract/v1/contract.proto`."""
    return _DESC
