// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/contract/v1/contract.proto

package contractv1

import (
	v1 "github.com/sudorandom/protoc-gen-jev/gen/jev/ai/shared/v1"
	_ "github.com/sudorandom/protoc-gen-jev/pkg/jev/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputText     string                 `protobuf:"bytes,1,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	InputCount    uint64                 `protobuf:"varint,2,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_ai_contract_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_contract_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_ai_contract_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

func (x *EvaluateRequest) GetInputCount() uint64 {
	if x != nil {
		return x.InputCount
	}
	return 0
}

type EvaluateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Flag             *bool                  `protobuf:"varint,1,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Rating           *int32                 `protobuf:"varint,2,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Count            uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	BigCount         int64                  `protobuf:"varint,4,opt,name=big_count,json=bigCount,proto3" json:"big_count,omitempty"`
	BigUnsigned      uint64                 `protobuf:"varint,5,opt,name=big_unsigned,json=bigUnsigned,proto3" json:"big_unsigned,omitempty"`
	FixedCount       uint32                 `protobuf:"fixed32,6,opt,name=fixed_count,json=fixedCount,proto3" json:"fixed_count,omitempty"`
	SignedFixedCount int64                  `protobuf:"fixed64,7,opt,name=signed_fixed_count,json=signedFixedCount,proto3" json:"signed_fixed_count,omitempty"`
	Risk             bool                   `protobuf:"varint,8,opt,name=risk,json=risk-flag,proto3" json:"risk,omitempty"`
	Status           v1.Status              `protobuf:"varint,9,opt,name=status,proto3,enum=ai.shared.v1.Status" json:"status,omitempty"`
	Label            *string                `protobuf:"bytes,10,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Boundary         int64                  `protobuf:"varint,14,opt,name=boundary,proto3" json:"boundary,omitempty"`
	// Types that are valid to be assigned to Route:
	//
	//	*EvaluateResponse_Email
	//	*EvaluateResponse_Binary
	//	*EvaluateResponse_Excluded
	Route         isEvaluateResponse_Route `protobuf_oneof:"route"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_ai_contract_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_contract_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_ai_contract_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *EvaluateResponse) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *EvaluateResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EvaluateResponse) GetBigCount() int64 {
	if x != nil {
		return x.BigCount
	}
	return 0
}

func (x *EvaluateResponse) GetBigUnsigned() uint64 {
	if x != nil {
		return x.BigUnsigned
	}
	return 0
}

func (x *EvaluateResponse) GetFixedCount() uint32 {
	if x != nil {
		return x.FixedCount
	}
	return 0
}

func (x *EvaluateResponse) GetSignedFixedCount() int64 {
	if x != nil {
		return x.SignedFixedCount
	}
	return 0
}

func (x *EvaluateResponse) GetRisk() bool {
	if x != nil {
		return x.Risk
	}
	return false
}

func (x *EvaluateResponse) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *EvaluateResponse) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *EvaluateResponse) GetBoundary() int64 {
	if x != nil {
		return x.Boundary
	}
	return 0
}

func (x *EvaluateResponse) GetRoute() isEvaluateResponse_Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *EvaluateResponse) GetEmail() string {
	if x != nil {
		if x, ok := x.Route.(*EvaluateResponse_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *EvaluateResponse) GetBinary() []byte {
	if x != nil {
		if x, ok := x.Route.(*EvaluateResponse_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *EvaluateResponse) GetExcluded() string {
	if x != nil {
		if x, ok := x.Route.(*EvaluateResponse_Excluded); ok {
			return x.Excluded
		}
	}
	return ""
}

type isEvaluateResponse_Route interface {
	isEvaluateResponse_Route()
}

type EvaluateResponse_Email struct {
	Email string `protobuf:"bytes,11,opt,name=email,proto3,oneof"`
}

type EvaluateResponse_Binary struct {
	Binary []byte `protobuf:"bytes,12,opt,name=binary,proto3,oneof"`
}

type EvaluateResponse_Excluded struct {
	Excluded string `protobuf:"bytes,13,opt,name=excluded,proto3,oneof"`
}

func (*EvaluateResponse_Email) isEvaluateResponse_Route() {}

func (*EvaluateResponse_Binary) isEvaluateResponse_Route() {}

func (*EvaluateResponse_Excluded) isEvaluateResponse_Route() {}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_ai_contract_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_ai_contract_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_ai_contract_v1_contract_proto_rawDescGZIP(), []int{2}
}

type Container_NestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputText     string                 `protobuf:"bytes,1,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container_NestedRequest) Reset() {
	*x = Container_NestedRequest{}
	mi := &file_ai_contract_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container_NestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_NestedRequest) ProtoMessage() {}

func (x *Container_NestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_contract_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_NestedRequest.ProtoReflect.Descriptor instead.
func (*Container_NestedRequest) Descriptor() ([]byte, []int) {
	return file_ai_contract_v1_contract_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Container_NestedRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

type Container_NestedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      *bool                  `protobuf:"varint,1,opt,name=accepted,proto3,oneof" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container_NestedResponse) Reset() {
	*x = Container_NestedResponse{}
	mi := &file_ai_contract_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container_NestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_NestedResponse) ProtoMessage() {}

func (x *Container_NestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_contract_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_NestedResponse.ProtoReflect.Descriptor instead.
func (*Container_NestedResponse) Descriptor() ([]byte, []int) {
	return file_ai_contract_v1_contract_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Container_NestedResponse) GetAccepted() bool {
	if x != nil && x.Accepted != nil {
		return *x.Accepted
	}
	return false
}

var File_ai_contract_v1_contract_proto protoreflect.FileDescriptor

const file_ai_contract_v1_contract_proto_rawDesc = "" +
	"\n" +
	"\x1dai/contract/v1/contract.proto\x12\x0eai.contract.v1\x1a\x14jev/v1/options.proto\x1a\x19ai/shared/v1/shared.proto\"Q\n" +
	"\x0fEvaluateRequest\x12\x1d\n" +
	"\n" +
	"input_text\x18\x01 \x01(\tR\tinputText\x12\x1f\n" +
	"\vinput_count\x18\x02 \x01(\x04R\n" +
	"inputCount\"\xda\x04\n" +
	"\x10EvaluateResponse\x12$\n" +
	"\x04flag\x18\x01 \x01(\bB\v\xaa\xa9#\a*\x05\r\x00\x00\x00\x00H\x01R\x04flag\x88\x01\x01\x12D\n" +
	"\x06rating\x18\x02 \x01(\x05B'\xaa\xa9##\"!\n" +
	"\x0e\t\x00\x00\x00\x00\x00\x00\b\xc0\x12\x03Low\n" +
	"\x0f\t\x00\x00\x00\x00\x00\x00\x00\xc0\x12\x04HighH\x02R\x06rating\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x1b\n" +
	"\tbig_count\x18\x04 \x01(\x03R\bbigCount\x12!\n" +
	"\fbig_unsigned\x18\x05 \x01(\x04R\vbigUnsigned\x12\x1f\n" +
	"\vfixed_count\x18\x06 \x01(\aR\n" +
	"fixedCount\x12,\n" +
	"\x12signed_fixed_count\x18\a \x01(\x10R\x10signedFixedCount\x12\x17\n" +
	"\x04risk\x18\b \x01(\bR\trisk-flag\x12,\n" +
	"\x06status\x18\t \x01(\x0e2\x14.ai.shared.v1.StatusR\x06status\x12*\n" +
	"\x05label\x18\n" +
	" \x01(\tB\x0f\xaa\xa9#\v\x1a\t\n" +
	"\x03YES\n" +
	"\x02NOH\x03R\x05label\x88\x01\x01\x12C\n" +
	"\bboundary\x18\x0e \x01(\x03B'\xaa\xa9##\"!\n" +
	"\x0e\t\xfe\xff\xff\xff\xff\xff?C\x12\x03Low\n" +
	"\x0f\t\xff\xff\xff\xff\xff\xff?C\x12\x04HighR\bboundary\x12\x16\n" +
	"\x05email\x18\v \x01(\tH\x00R\x05email\x12\x18\n" +
	"\x06binary\x18\f \x01(\fH\x00R\x06binary\x12$\n" +
	"\bexcluded\x18\r \x01(\tB\x06\xaa\xa9#\x02\x10\x01H\x00R\bexcludedB\a\n" +
	"\x05routeB\a\n" +
	"\x05_flagB\t\n" +
	"\a_ratingB\b\n" +
	"\x06_label\"{\n" +
	"\tContainer\x1a.\n" +
	"\rNestedRequest\x12\x1d\n" +
	"\n" +
	"input_text\x18\x01 \x01(\tR\tinputText\x1a>\n" +
	"\x0eNestedResponse\x12\x1f\n" +
	"\baccepted\x18\x01 \x01(\bH\x00R\baccepted\x88\x01\x01B\v\n" +
	"\t_acceptedBHZFgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/contract/v1;contractv1b\x06proto3"

var (
	file_ai_contract_v1_contract_proto_rawDescOnce sync.Once
	file_ai_contract_v1_contract_proto_rawDescData []byte
)

func file_ai_contract_v1_contract_proto_rawDescGZIP() []byte {
	file_ai_contract_v1_contract_proto_rawDescOnce.Do(func() {
		file_ai_contract_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_contract_v1_contract_proto_rawDesc), len(file_ai_contract_v1_contract_proto_rawDesc)))
	})
	return file_ai_contract_v1_contract_proto_rawDescData
}

var file_ai_contract_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_contract_v1_contract_proto_goTypes = []any{
	(*EvaluateRequest)(nil),          // 0: ai.contract.v1.EvaluateRequest
	(*EvaluateResponse)(nil),         // 1: ai.contract.v1.EvaluateResponse
	(*Container)(nil),                // 2: ai.contract.v1.Container
	(*Container_NestedRequest)(nil),  // 3: ai.contract.v1.Container.NestedRequest
	(*Container_NestedResponse)(nil), // 4: ai.contract.v1.Container.NestedResponse
	(v1.Status)(0),                   // 5: ai.shared.v1.Status
}
var file_ai_contract_v1_contract_proto_depIdxs = []int32{
	5, // 0: ai.contract.v1.EvaluateResponse.status:type_name -> ai.shared.v1.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_contract_v1_contract_proto_init() }
func file_ai_contract_v1_contract_proto_init() {
	if File_ai_contract_v1_contract_proto != nil {
		return
	}
	file_ai_contract_v1_contract_proto_msgTypes[1].OneofWrappers = []any{
		(*EvaluateResponse_Email)(nil),
		(*EvaluateResponse_Binary)(nil),
		(*EvaluateResponse_Excluded)(nil),
	}
	file_ai_contract_v1_contract_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_contract_v1_contract_proto_rawDesc), len(file_ai_contract_v1_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_contract_v1_contract_proto_goTypes,
		DependencyIndexes: file_ai_contract_v1_contract_proto_depIdxs,
		MessageInfos:      file_ai_contract_v1_contract_proto_msgTypes,
	}.Build()
	File_ai_contract_v1_contract_proto = out.File
	file_ai_contract_v1_contract_proto_goTypes = nil
	file_ai_contract_v1_contract_proto_depIdxs = nil
}
