// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/contract/v1/service.proto (package ai.contract.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_jev_v1_options } from "../../../jev/v1/options_pb";
import type { Container_NestedRequestSchema, Container_NestedResponseSchema, EvaluateRequestSchema, EvaluateResponseSchema } from "./contract_pb";
import { file_ai_contract_v1_contract } from "./contract_pb";
import type { ExternalRequestSchema, ExternalResponseSchema } from "../../shared/v1/shared_pb";
import { file_ai_shared_v1_shared } from "../../shared/v1/shared_pb";

/**
 * Describes the file ai/contract/v1/service.proto.
 */
export const file_ai_contract_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChxhaS9jb250cmFjdC92MS9zZXJ2aWNlLnByb3RvEg5haS5jb250cmFjdC52MTKQAgoPQ29udHJhY3RTZXJ2aWNlEk0KCEV2YWx1YXRlEh8uYWkuY29udHJhY3QudjEuRXZhbHVhdGVSZXF1ZXN0GiAuYWkuY29udHJhY3QudjEuRXZhbHVhdGVSZXNwb25zZRJJCghFeHRlcm5hbBIdLmFpLnNoYXJlZC52MS5FeHRlcm5hbFJlcXVlc3QaHi5haS5zaGFyZWQudjEuRXh0ZXJuYWxSZXNwb25zZRJbCgZOZXN0ZWQSJy5haS5jb250cmFjdC52MS5Db250YWluZXIuTmVzdGVkUmVxdWVzdBooLmFpLmNvbnRyYWN0LnYxLkNvbnRhaW5lci5OZXN0ZWRSZXNwb25zZRoGsqkjAggBQkhaRmdpdGh1Yi5jb20vc3Vkb3JhbmRvbS9wcm90b2MtZ2VuLWpldi9nZW4vamV2L2FpL2NvbnRyYWN0L3YxO2NvbnRyYWN0djFiBnByb3RvMw", [file_jev_v1_options, file_ai_contract_v1_contract, file_ai_shared_v1_shared]);

/**
 * @generated from service ai.contract.v1.ContractService
 */
export const ContractService: GenService<{
  /**
   * @generated from rpc ai.contract.v1.ContractService.Evaluate
   */
  evaluate: {
    methodKind: "unary";
    input: typeof EvaluateRequestSchema;
    output: typeof EvaluateResponseSchema;
  },
  /**
   * @generated from rpc ai.contract.v1.ContractService.External
   */
  external: {
    methodKind: "unary";
    input: typeof ExternalRequestSchema;
    output: typeof ExternalResponseSchema;
  },
  /**
   * @generated from rpc ai.contract.v1.ContractService.Nested
   */
  nested: {
    methodKind: "unary";
    input: typeof Container_NestedRequestSchema;
    output: typeof Container_NestedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_contract_v1_service, 0);

