// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/contract/v1/service.proto

package contractv1

import (
	v1 "github.com/sudorandom/protoc-gen-jev/gen/jev/ai/shared/v1"
	_ "github.com/sudorandom/protoc-gen-jev/pkg/jev/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_contract_v1_service_proto protoreflect.FileDescriptor

const file_ai_contract_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1cai/contract/v1/service.proto\x12\x0eai.contract.v1\x1a\x14jev/v1/options.proto\x1a\x1dai/contract/v1/contract.proto\x1a\x19ai/shared/v1/shared.proto2\x90\x02\n" +
	"\x0fContractService\x12M\n" +
	"\bEvaluate\x12\x1f.ai.contract.v1.EvaluateRequest\x1a .ai.contract.v1.EvaluateResponse\x12I\n" +
	"\bExternal\x12\x1d.ai.shared.v1.ExternalRequest\x1a\x1e.ai.shared.v1.ExternalResponse\x12[\n" +
	"\x06Nested\x12'.ai.contract.v1.Container.NestedRequest\x1a(.ai.contract.v1.Container.NestedResponse\x1a\x06\xb2\xa9#\x02\b\x01BHZFgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/contract/v1;contractv1b\x06proto3"

var file_ai_contract_v1_service_proto_goTypes = []any{
	(*EvaluateRequest)(nil),          // 0: ai.contract.v1.EvaluateRequest
	(*v1.ExternalRequest)(nil),       // 1: ai.shared.v1.ExternalRequest
	(*Container_NestedRequest)(nil),  // 2: ai.contract.v1.Container.NestedRequest
	(*EvaluateResponse)(nil),         // 3: ai.contract.v1.EvaluateResponse
	(*v1.ExternalResponse)(nil),      // 4: ai.shared.v1.ExternalResponse
	(*Container_NestedResponse)(nil), // 5: ai.contract.v1.Container.NestedResponse
}
var file_ai_contract_v1_service_proto_depIdxs = []int32{
	0, // 0: ai.contract.v1.ContractService.Evaluate:input_type -> ai.contract.v1.EvaluateRequest
	1, // 1: ai.contract.v1.ContractService.External:input_type -> ai.shared.v1.ExternalRequest
	2, // 2: ai.contract.v1.ContractService.Nested:input_type -> ai.contract.v1.Container.NestedRequest
	3, // 3: ai.contract.v1.ContractService.Evaluate:output_type -> ai.contract.v1.EvaluateResponse
	4, // 4: ai.contract.v1.ContractService.External:output_type -> ai.shared.v1.ExternalResponse
	5, // 5: ai.contract.v1.ContractService.Nested:output_type -> ai.contract.v1.Container.NestedResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_contract_v1_service_proto_init() }
func file_ai_contract_v1_service_proto_init() {
	if File_ai_contract_v1_service_proto != nil {
		return
	}
	file_ai_contract_v1_contract_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_contract_v1_service_proto_rawDesc), len(file_ai_contract_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_contract_v1_service_proto_goTypes,
		DependencyIndexes: file_ai_contract_v1_service_proto_depIdxs,
	}.Build()
	File_ai_contract_v1_service_proto = out.File
	file_ai_contract_v1_service_proto_goTypes = nil
	file_ai_contract_v1_service_proto_depIdxs = nil
}
