# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/contract/v1/service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'ai/contract/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jev.v1 import options_pb2 as jev_dot_v1_dot_options__pb2
from ai.contract.v1 import contract_pb2 as ai_dot_contract_dot_v1_dot_contract__pb2
from ai.shared.v1 import shared_pb2 as ai_dot_shared_dot_v1_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61i/contract/v1/service.proto\x12\x0e\x61i.contract.v1\x1a\x14jev/v1/options.proto\x1a\x1d\x61i/contract/v1/contract.proto\x1a\x19\x61i/shared/v1/shared.proto2\x90\x02\n\x0f\x43ontractService\x12M\n\x08\x45valuate\x12\x1f.ai.contract.v1.EvaluateRequest\x1a .ai.contract.v1.EvaluateResponse\x12I\n\x08\x45xternal\x12\x1d.ai.shared.v1.ExternalRequest\x1a\x1e.ai.shared.v1.ExternalResponse\x12[\n\x06Nested\x12\'.ai.contract.v1.Container.NestedRequest\x1a(.ai.contract.v1.Container.NestedResponse\x1a\x06\xb2\xa9#\x02\x08\x01\x42HZFgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/contract/v1;contractv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.contract.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/sudorandom/protoc-gen-jev/gen/jev/ai/contract/v1;contractv1'
  _globals['_CONTRACTSERVICE']._loaded_options = None
  _globals['_CONTRACTSERVICE']._serialized_options = b'\262\251#\002\010\001'
  _globals['_CONTRACTSERVICE']._serialized_start=129
  _globals['_CONTRACTSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
