// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: jev/v1/options.proto

// Experimental: Field options for mapping Protobuf fields to TypeSafe AI's Jev cognitive questions.

package jevv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit instructions for Jev to evaluate this field.
	// If omitted, the field's Protobuf doc comment is used.
	Instructions string `protobuf:"bytes,1,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// If true, Jev will skip evaluating this field (e.g. for freeform text, IDs, or downstream fields).
	Skip bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// For boolean (Noul): confidence threshold [0.0 - 1.0] to evaluate as true.
	Threshold float32 `protobuf:"fixed32,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// For numeric ranges (Score): minimum value of the evaluation rubric scale (default: 0).
	Min float32 `protobuf:"fixed32,4,opt,name=min,proto3" json:"min,omitempty"`
	// For numeric ranges (Score): maximum value of the evaluation rubric scale (default: 100).
	Max float32 `protobuf:"fixed32,5,opt,name=max,proto3" json:"max,omitempty"`
	// For enums, strings, and choices: guidance/criteria attached to specific options (label -> description).
	// When specified on a string field without 'choices', the map keys define the allowed choices.
	Criteria map[string]string `protobuf:"bytes,6,rep,name=criteria,proto3" json:"criteria,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// For string or enum fields (Choice): explicit whitelist of allowed choice values.
	Choices []string `protobuf:"bytes,7,rep,name=choices,proto3" json:"choices,omitempty"`
	// For enum fields (Choice): blacklist of enum value names to exclude from choices.
	NotIn []string `protobuf:"bytes,8,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// For numeric fields (Score): explicit discrete scale points / rubric tiers (e.g. [1, 2, 3, 4, 5] or [0.2, 0.5, 0.8]).
	Scale         []float32 `protobuf:"fixed32,9,rep,packed,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_jev_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_jev_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *FieldOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *FieldOptions) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *FieldOptions) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *FieldOptions) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *FieldOptions) GetCriteria() map[string]string {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *FieldOptions) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *FieldOptions) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *FieldOptions) GetScale() []float32 {
	if x != nil {
		return x.Scale
	}
	return nil
}

var file_jev_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50001,
		Name:          "jev.v1.field",
		Tag:           "bytes,50001,opt,name=field",
		Filename:      "jev/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional jev.v1.FieldOptions field = 50001;
	E_Field = &file_jev_v1_options_proto_extTypes[0]
)

var File_jev_v1_options_proto protoreflect.FileDescriptor

const file_jev_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x14jev/v1/options.proto\x12\x06jev.v1\x1a google/protobuf/descriptor.proto\"\xcc\x02\n" +
	"\fFieldOptions\x12\"\n" +
	"\finstructions\x18\x01 \x01(\tR\finstructions\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x02R\tthreshold\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x02R\x03max\x12>\n" +
	"\bcriteria\x18\x06 \x03(\v2\".jev.v1.FieldOptions.CriteriaEntryR\bcriteria\x12\x18\n" +
	"\achoices\x18\a \x03(\tR\achoices\x12\x15\n" +
	"\x06not_in\x18\b \x03(\tR\x05notIn\x12\x14\n" +
	"\x05scale\x18\t \x03(\x02R\x05scale\x1a;\n" +
	"\rCriteriaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:K\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x14.jev.v1.FieldOptionsR\x05fieldB7Z5github.com/sudorandom/protoc-gen-jev/pkg/jev/v1;jevv1b\x06proto3"

var (
	file_jev_v1_options_proto_rawDescOnce sync.Once
	file_jev_v1_options_proto_rawDescData []byte
)

func file_jev_v1_options_proto_rawDescGZIP() []byte {
	file_jev_v1_options_proto_rawDescOnce.Do(func() {
		file_jev_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jev_v1_options_proto_rawDesc), len(file_jev_v1_options_proto_rawDesc)))
	})
	return file_jev_v1_options_proto_rawDescData
}

var file_jev_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jev_v1_options_proto_goTypes = []any{
	(*FieldOptions)(nil),              // 0: jev.v1.FieldOptions
	nil,                               // 1: jev.v1.FieldOptions.CriteriaEntry
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_jev_v1_options_proto_depIdxs = []int32{
	1, // 0: jev.v1.FieldOptions.criteria:type_name -> jev.v1.FieldOptions.CriteriaEntry
	2, // 1: jev.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 2: jev.v1.field:type_name -> jev.v1.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jev_v1_options_proto_init() }
func file_jev_v1_options_proto_init() {
	if File_jev_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jev_v1_options_proto_rawDesc), len(file_jev_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_jev_v1_options_proto_goTypes,
		DependencyIndexes: file_jev_v1_options_proto_depIdxs,
		MessageInfos:      file_jev_v1_options_proto_msgTypes,
		ExtensionInfos:    file_jev_v1_options_proto_extTypes,
	}.Build()
	File_jev_v1_options_proto = out.File
	file_jev_v1_options_proto_goTypes = nil
	file_jev_v1_options_proto_depIdxs = nil
}
