// Code generated by protoc-gen-jev. DO NOT EDIT.
import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";

export interface RuleTestRecordJevDecisions {
  delivery_method?: string;
  executionMode?: string;
  filteredMode?: string;
  ratingSmall?: number;
  ratingStrict?: number;
  discreteCode?: number;
  largeScale?: number;
  temperature?: number;
  discreteRatio?: number;
  securityClearance?: string;
  decisionFlag?: string;
  customBoundedScore?: number;
}

export class RuleTestRecordJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      delivery_method: choice(
        "1. Oneof mutual exclusion -> maps to Choice",
        { "email": null, "push_notification": null, "sms": null },
      ),
      executionMode: choice(
        "3. Enum restricted by enum.in -> Choice with only [MODE_FAST, MODE_BALANCED]",
        { "MODE_BALANCED": null, "MODE_FAST": null },
      ),
      filteredMode: choice(
        "4. Enum restricted by enum.not_in -> Choice omitting MODE_DEBUG",
        { "MODE_ACCURATE": null, "MODE_BALANCED": null, "MODE_FAST": null },
      ),
      ratingSmall: score(
        "5. Integer with small range (<= 10) -> exact sequence [1..5]",
        ["1", "2", "3", "4", "5"],
      ),
      ratingStrict: score(
        "6. Integer with strict bounds (gt/lt) -> [1, 2, 3]",
        ["1", "2", "3"],
      ),
      discreteCode: score(
        "7. Integer with discrete allowed values -> [\"10\", \"20\", \"50\", \"100\"]",
        ["10", "20", "50", "100"],
      ),
      largeScale: score(
        "8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]",
        ["0", "250", "500", "750", "1000"],
      ),
      temperature: score(
        "9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]",
        ["-40.0", "-15.0", "10.0", "35.0", "60.0"],
      ),
      discreteRatio: score(
        "10. Float discrete values -> [\"0.2\", \"0.5\", \"0.8\"]",
        ["0.2", "0.5", "0.8"],
      ),
      securityClearance: choice(
        "11. String with allowed set of values -> Choice",
        { "PUBLIC": null, "SECRET": null, "TOP_SECRET": null },
      ),
      decisionFlag: choice(
        "12. String with custom Jev criteria options -> Choice",
        { "APPROVE": null, "REJECT": null },
      ),
      customBoundedScore: score(
        "13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]",
        ["10.0", "20.0", "30.0", "40.0", "50.0"],
      ),
    };
  }

  async evaluate(state: Record<string, any> | string): Promise<RuleTestRecordJevDecisions> {
    const payloadState = typeof state === "string" ? { text: state } : state;
    const resp = await this.client.systemOne({ state: payloadState, questions: this.buildQuestions() });
    const anyResp = resp as any;
    return {
      delivery_method: anyResp.answers?.["delivery_method"]?.choice ?? anyResp.choices?.["delivery_method"]?.choice,
      executionMode: anyResp.answers?.["executionMode"]?.choice ?? anyResp.choices?.["executionMode"]?.choice,
      filteredMode: anyResp.answers?.["filteredMode"]?.choice ?? anyResp.choices?.["filteredMode"]?.choice,
      ratingSmall: anyResp.answers?.["ratingSmall"]?.score ?? anyResp.scores?.["ratingSmall"]?.score,
      ratingStrict: anyResp.answers?.["ratingStrict"]?.score ?? anyResp.scores?.["ratingStrict"]?.score,
      discreteCode: anyResp.answers?.["discreteCode"]?.score ?? anyResp.scores?.["discreteCode"]?.score,
      largeScale: anyResp.answers?.["largeScale"]?.score ?? anyResp.scores?.["largeScale"]?.score,
      temperature: anyResp.answers?.["temperature"]?.score ?? anyResp.scores?.["temperature"]?.score,
      discreteRatio: anyResp.answers?.["discreteRatio"]?.score ?? anyResp.scores?.["discreteRatio"]?.score,
      securityClearance: anyResp.answers?.["securityClearance"]?.choice ?? anyResp.choices?.["securityClearance"]?.choice,
      decisionFlag: anyResp.answers?.["decisionFlag"]?.choice ?? anyResp.choices?.["decisionFlag"]?.choice,
      customBoundedScore: anyResp.answers?.["customBoundedScore"]?.score ?? anyResp.scores?.["customBoundedScore"]?.score,
    };
  }

  async batchEvaluate(states: Array<Record<string, any> | string>): Promise<RuleTestRecordJevDecisions[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

