// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/rules/v1/rules.proto (package ai.rules.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_jev_v1_options } from "../../../jev/v1/options_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/rules/v1/rules.proto.
 */
export const file_ai_rules_v1_rules: GenFile = /*@__PURE__*/
  fileDesc("ChdhaS9ydWxlcy92MS9ydWxlcy5wcm90bxILYWkucnVsZXMudjEimAkKDlJ1bGVUZXN0UmVjb3JkEg8KBWVtYWlsGAEgASgJSAASDQoDc21zGAIgASgJSAASGwoRcHVzaF9ub3RpZmljYXRpb24YAyABKAlIABIaCg1vcHRpb25hbF9ub3RlGAQgASgJSAGIAQESSwoOZXhlY3V0aW9uX21vZGUYBSABKA4yES5haS5ydWxlcy52MS5Nb2RlQiCqqSMcGhoKCU1PREVfRkFTVAoNTU9ERV9CQUxBTkNFRBI8Cg1maWx0ZXJlZF9tb2RlGAYgASgOMhEuYWkucnVsZXMudjEuTW9kZUISqqkjDhoMEgpNT0RFX0RFQlVHEmIKDHJhdGluZ19zbWFsbBgHIAEoBUJMqqkjSCJGCgwJAAAAAAAA8D8SATEKDAkAAAAAAAAAQBIBMgoMCQAAAAAAAAhAEgEzCgwJAAAAAAAAEEASATQKDAkAAAAAAAAUQBIBNRJHCg1yYXRpbmdfc3RyaWN0GAggASgFQjCqqSMsIioKDAkAAAAAAADwPxIBMQoMCQAAAAAAAABAEgEyCgwJAAAAAAAACEASATMSWgoNZGlzY3JldGVfY29kZRgJIAEoBUJDqqkjPyI9Cg0JAAAAAAAAJEASAjEwCg0JAAAAAAAANEASAjIwCg0JAAAAAAAASUASAjUwCg4JAAAAAAAAWUASAzEwMBJhCgtsYXJnZV9zY2FsZRgKIAEoA0JMqqkjSCJGCgMSATAKDgkAAAAAAEBvQBIDMjUwCg4JAAAAAABAf0ASAzUwMAoOCQAAAAAAcIdAEgM3NTAKDwkAAAAAAECPQBIEMTAwMBJyCgt0ZW1wZXJhdHVyZRgLIAEoAkJdqqkjWSJXChAJAAAAAAAARMASBS00MC4wChAJAAAAAAAALsASBS0xNS4wCg8JAAAAAAAAJEASBDEwLjAKDwkAAAAAAIBBQBIEMzUuMAoPCQAAAAAAAE5AEgQ2MC4wEk4KDmRpc2NyZXRlX3JhdGlvGAwgASgCQjaqqSMyIjAKDgmamZmZmZnJPxIDMC4yCg4JAAAAAAAA4D8SAzAuNQoOCZqZmZmZmek/EgMwLjgSPgoSc2VjdXJpdHlfY2xlYXJhbmNlGA0gASgJQiKqqSMeGhwKBlBVQkxJQwoGU0VDUkVUCgpUT1BfU0VDUkVUElYKDWRlY2lzaW9uX2ZsYWcYDiABKAlCP6qpIzsaORobCgdBUFBST1ZFEhBSZXF1ZXN0IGFwcHJvdmVkGhoKBlJFSkVDVBIQUmVxdWVzdCByZWplY3RlZBJ5ChRjdXN0b21fYm91bmRlZF9zY29yZRgPIAEoAkJbqqkjVyJVCg8JAAAAAAAAJEASBDEwLjAKDwkAAAAAAAA0QBIEMjAuMAoPCQAAAAAAAD5AEgQzMC4wCg8JAAAAAAAAREASBDQwLjAKDwkAAAAAAABJQBIENTAuMBIcCgxzZWNyZXRfdG9rZW4YECABKAlCBqqpIwIQARIcChRmcmVlZm9ybV9kZXNjcmlwdGlvbhgRIAEoCUIRCg9kZWxpdmVyeV9tZXRob2RCEAoOX29wdGlvbmFsX25vdGUqYQoETW9kZRIUChBNT0RFX1VOU1BFQ0lGSUVEEAASDQoJTU9ERV9GQVNUEAESEQoNTU9ERV9CQUxBTkNFRBACEhEKDU1PREVfQUNDVVJBVEUQAxIOCgpNT0RFX0RFQlVHEARCFVoTYWkvcnVsZXMvdjE7cnVsZXN2MWIGcHJvdG8z", [file_jev_v1_options]);

/**
 * @generated from message ai.rules.v1.RuleTestRecord
 */
export type RuleTestRecord = Message<"ai.rules.v1.RuleTestRecord"> & {
  /**
   * 1. Oneof mutual exclusion -> maps to Choice
   *
   * @generated from oneof ai.rules.v1.RuleTestRecord.delivery_method
   */
  deliveryMethod: {
    /**
     * @generated from field: string email = 1;
     */
    value: string;
    case: "email";
  } | {
    /**
     * @generated from field: string sms = 2;
     */
    value: string;
    case: "sms";
  } | {
    /**
     * @generated from field: string push_notification = 3;
     */
    value: string;
    case: "pushNotification";
  } | { case: undefined; value?: undefined };

  /**
   * 2. Proto3 optional (synthetic oneof) -> must NOT be treated as a oneof Choice!
   *
   * @generated from field: optional string optional_note = 4;
   */
  optionalNote?: string | undefined;

  /**
   * 3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]
   *
   * @generated from field: ai.rules.v1.Mode execution_mode = 5;
   */
  executionMode: Mode;

  /**
   * 4. Enum restricted by not_in -> Choice omitting MODE_DEBUG
   *
   * @generated from field: ai.rules.v1.Mode filtered_mode = 6;
   */
  filteredMode: Mode;

  /**
   * 5. Integer with small range (<= 10) -> exact sequence [1..5]
   *
   * @generated from field: int32 rating_small = 7;
   */
  ratingSmall: number;

  /**
   * 6. Integer with explicit scale -> [1, 2, 3]
   *
   * @generated from field: int32 rating_strict = 8;
   */
  ratingStrict: number;

  /**
   * 7. Integer with discrete allowed values -> ["10", "20", "50", "100"]
   *
   * @generated from field: int32 discrete_code = 9;
   */
  discreteCode: number;

  /**
   * 8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]
   *
   * @generated from field: int64 large_scale = 10;
   */
  largeScale: bigint;

  /**
   * 9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]
   *
   * @generated from field: float temperature = 11;
   */
  temperature: number;

  /**
   * 10. Float discrete values -> ["0.2", "0.5", "0.8"]
   *
   * @generated from field: float discrete_ratio = 12;
   */
  discreteRatio: number;

  /**
   * 11. String with allowed set of values -> Choice
   *
   * @generated from field: string security_clearance = 13;
   */
  securityClearance: string;

  /**
   * 12. String with custom Jev criteria options -> Choice
   *
   * @generated from field: string decision_flag = 14;
   */
  decisionFlag: string;

  /**
   * 13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]
   *
   * @generated from field: float custom_bounded_score = 15;
   */
  customBoundedScore: number;

  /**
   * 14. Explicitly skipped field -> MUST NOT appear in questions
   *
   * @generated from field: string secret_token = 16;
   */
  secretToken: string;

  /**
   * 15. Freeform text without rules -> omitted from Jev questions
   *
   * @generated from field: string freeform_description = 17;
   */
  freeformDescription: string;
};

/**
 * Describes the message ai.rules.v1.RuleTestRecord.
 * Use `create(RuleTestRecordSchema)` to create a new message.
 */
export const RuleTestRecordSchema: GenMessage<RuleTestRecord> = /*@__PURE__*/
  messageDesc(file_ai_rules_v1_rules, 0);

/**
 * @generated from enum ai.rules.v1.Mode
 */
export enum Mode {
  /**
   * @generated from enum value: MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODE_FAST = 1;
   */
  FAST = 1,

  /**
   * @generated from enum value: MODE_BALANCED = 2;
   */
  BALANCED = 2,

  /**
   * @generated from enum value: MODE_ACCURATE = 3;
   */
  ACCURATE = 3,

  /**
   * @generated from enum value: MODE_DEBUG = 4;
   */
  DEBUG = 4,
}

/**
 * Describes the enum ai.rules.v1.Mode.
 */
export const ModeSchema: GenEnum<Mode> = /*@__PURE__*/
  enumDesc(file_ai_rules_v1_rules, 0);

