"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score

class RuleTestRecordJevClient:
    """Typed Jev client for evaluating RuleTestRecord."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None  # Will lazy-init on evaluate() from env

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "delivery_method": Choice(
                instructions="1. Oneof mutual exclusion -> maps to Choice",
                criteria={"email": None, "push_notification": None, "sms": None},
            ),
            "executionMode": Choice(
                instructions="3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]",
                criteria={"MODE_BALANCED": None, "MODE_FAST": None},
            ),
            "filteredMode": Choice(
                instructions="4. Enum restricted by not_in -> Choice omitting MODE_DEBUG",
                criteria={"MODE_ACCURATE": None, "MODE_BALANCED": None, "MODE_FAST": None},
            ),
            "ratingSmall": Score(
                instructions="5. Integer with small range (<= 10) -> exact sequence [1..5]",
                criteria=["1", "2", "3", "4", "5"],
            ),
            "ratingStrict": Score(
                instructions="6. Integer with explicit scale -> [1, 2, 3]",
                criteria=["1", "2", "3"],
            ),
            "discreteCode": Score(
                instructions="7. Integer with discrete allowed values -> [\"10\", \"20\", \"50\", \"100\"]",
                criteria=["10", "20", "50", "100"],
            ),
            "largeScale": Score(
                instructions="8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]",
                criteria=["0", "250", "500", "750", "1000"],
            ),
            "temperature": Score(
                instructions="9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]",
                criteria=["-40.0", "-15.0", "10.0", "35.0", "60.0"],
            ),
            "discreteRatio": Score(
                instructions="10. Float discrete values -> [\"0.2\", \"0.5\", \"0.8\"]",
                criteria=["0.2", "0.5", "0.8"],
            ),
            "securityClearance": Choice(
                instructions="11. String with allowed set of values -> Choice",
                criteria={"PUBLIC": None, "SECRET": None, "TOP_SECRET": None},
            ),
            "decisionFlag": Choice(
                instructions="12. String with custom Jev criteria options -> Choice",
                criteria={"APPROVE": None, "REJECT": None},
            ),
            "customBoundedScore": Score(
                instructions="13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]",
                criteria=["10.0", "20.0", "30.0", "40.0", "50.0"],
            ),
        }

    def evaluate(self, state: Dict[str, Any] | str) -> Dict[str, Any]:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = {"text": state} if isinstance(state, str) else state
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = {}
        if "delivery_method" in resp.choices:
            out["delivery_method"] = resp.choices["delivery_method"].choice
        if "executionMode" in resp.choices:
            out["execution_mode"] = resp.choices["executionMode"].choice
        if "filteredMode" in resp.choices:
            out["filtered_mode"] = resp.choices["filteredMode"].choice
        if "ratingSmall" in resp.scores:
            out["rating_small"] = resp.scores["ratingSmall"].score
        if "ratingStrict" in resp.scores:
            out["rating_strict"] = resp.scores["ratingStrict"].score
        if "discreteCode" in resp.scores:
            out["discrete_code"] = resp.scores["discreteCode"].score
        if "largeScale" in resp.scores:
            out["large_scale"] = resp.scores["largeScale"].score
        if "temperature" in resp.scores:
            out["temperature"] = resp.scores["temperature"].score
        if "discreteRatio" in resp.scores:
            out["discrete_ratio"] = resp.scores["discreteRatio"].score
        if "securityClearance" in resp.choices:
            out["security_clearance"] = resp.choices["securityClearance"].choice
        if "decisionFlag" in resp.choices:
            out["decision_flag"] = resp.choices["decisionFlag"].choice
        if "customBoundedScore" in resp.scores:
            out["custom_bounded_score"] = resp.scores["customBoundedScore"].score
        return out

    def batch_evaluate(self, states: List[Dict[str, Any] | str]) -> List[Dict[str, Any]]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

