// Code generated by protoc-gen-jev. DO NOT EDIT.
import { TypeSafeClient, choice, score, noul } from "@typesafe-ai/sdk";
import { create, toJson, enumFromJson } from "@bufbuild/protobuf";
import {
  ModeSchema,
  RuleTestRecord,
  RuleTestRecordSchema,
} from "./rules_pb.js";

function interpolateScore(s: number, levels: number[]): number {
  if (levels.length === 0) return s;
  if (s <= 0) return levels[0];
  if (s >= levels.length - 1) return levels[levels.length - 1];
  const idx = Math.floor(s);
  const frac = s - idx;
  return levels[idx] + frac * (levels[idx + 1] - levels[idx]);
}

export class RuleTestRecordJevClient {
  private client: TypeSafeClient;

  constructor(client?: TypeSafeClient) {
    this.client = client ?? new TypeSafeClient();
  }

  buildQuestions() {
    return {
      delivery_method: choice(
        "1. Oneof mutual exclusion -> maps to Choice",
        { "email": "email", "push_notification": "push_notification", "sms": "sms" },
      ),
      executionMode: choice(
        "3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]",
        { "MODE_BALANCED": "", "MODE_FAST": "" },
      ),
      filteredMode: choice(
        "4. Enum restricted by not_in -> Choice omitting MODE_DEBUG",
        { "MODE_ACCURATE": "", "MODE_BALANCED": "", "MODE_FAST": "" },
      ),
      ratingSmall: score(
        "5. Integer with small range (<= 10) -> exact sequence [1..5]",
        ["1", "2", "3", "4", "5"],
      ),
      ratingStrict: score(
        "6. Integer with explicit scale -> [1, 2, 3]",
        ["1", "2", "3"],
      ),
      discreteCode: score(
        "7. Integer with discrete allowed values -> [\"10\", \"20\", \"50\", \"100\"]",
        ["10", "20", "50", "100"],
      ),
      largeScale: score(
        "8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]",
        ["0", "250", "500", "750", "1000"],
      ),
      temperature: score(
        "9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]",
        ["-40.0", "-15.0", "10.0", "35.0", "60.0"],
      ),
      discreteRatio: score(
        "10. Float discrete values -> [\"0.2\", \"0.5\", \"0.8\"]",
        ["0.2", "0.5", "0.8"],
      ),
      securityClearance: choice(
        "11. String with allowed set of values -> Choice",
        { "PUBLIC": "", "SECRET": "", "TOP_SECRET": "" },
      ),
      decisionFlag: choice(
        "12. String with custom Jev criteria options -> Choice",
        { "APPROVE": "Request approved", "REJECT": "Request rejected" },
      ),
      customBoundedScore: score(
        "13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]",
        ["10.0", "20.0", "30.0", "40.0", "50.0"],
      ),
    };
  }

  async evaluate(state: RuleTestRecord | Record<string, any> | string): Promise<RuleTestRecord> {
    const payloadState = (state && typeof state === "object" && "$typeName" in (state as any)) ? toJson(RuleTestRecordSchema, state as any) : (typeof state === "string" ? { text: state } : state);
    const resp = await this.client.systemOne({ state: payloadState as Record<string, any>, questions: this.buildQuestions() });
    const anyResp = resp as any;
    const result: Record<string, any> = {};
    const choice_delivery_method = anyResp.answers?.["delivery_method"]?.choice ?? anyResp.choices?.["delivery_method"]?.choice;
    if (choice_delivery_method) {
      switch (choice_delivery_method) {
        case "email":
          result["deliveryMethod"] = { case: "email", value: choice_delivery_method };
          break;
        case "push_notification":
          result["deliveryMethod"] = { case: "pushNotification", value: choice_delivery_method };
          break;
        case "sms":
          result["deliveryMethod"] = { case: "sms", value: choice_delivery_method };
          break;
      }
    }
    const choice_executionMode = anyResp.answers?.["executionMode"]?.choice ?? anyResp.choices?.["executionMode"]?.choice;
    if (choice_executionMode) {
      try { result["executionMode"] = enumFromJson(ModeSchema, choice_executionMode); } catch { /* ignore */ }
    }
    const choice_filteredMode = anyResp.answers?.["filteredMode"]?.choice ?? anyResp.choices?.["filteredMode"]?.choice;
    if (choice_filteredMode) {
      try { result["filteredMode"] = enumFromJson(ModeSchema, choice_filteredMode); } catch { /* ignore */ }
    }
    const score_ratingSmall = anyResp.answers?.["ratingSmall"]?.score ?? anyResp.scores?.["ratingSmall"]?.score;
    if (score_ratingSmall !== undefined) {
      const sVal_ratingSmall = interpolateScore(score_ratingSmall, [1, 2, 3, 4, 5]);
      result["ratingSmall"] = Math.round(sVal_ratingSmall);
    }
    const score_ratingStrict = anyResp.answers?.["ratingStrict"]?.score ?? anyResp.scores?.["ratingStrict"]?.score;
    if (score_ratingStrict !== undefined) {
      const sVal_ratingStrict = interpolateScore(score_ratingStrict, [1, 2, 3]);
      result["ratingStrict"] = Math.round(sVal_ratingStrict);
    }
    const score_discreteCode = anyResp.answers?.["discreteCode"]?.score ?? anyResp.scores?.["discreteCode"]?.score;
    if (score_discreteCode !== undefined) {
      const sVal_discreteCode = interpolateScore(score_discreteCode, [10, 20, 50, 100]);
      result["discreteCode"] = Math.round(sVal_discreteCode);
    }
    const score_largeScale = anyResp.answers?.["largeScale"]?.score ?? anyResp.scores?.["largeScale"]?.score;
    if (score_largeScale !== undefined) {
      const sVal_largeScale = interpolateScore(score_largeScale, [0, 250, 500, 750, 1000]);
      result["largeScale"] = Math.round(sVal_largeScale);
    }
    const score_temperature = anyResp.answers?.["temperature"]?.score ?? anyResp.scores?.["temperature"]?.score;
    if (score_temperature !== undefined) {
      const sVal_temperature = interpolateScore(score_temperature, [-40, -15, 10, 35, 60]);
      result["temperature"] = sVal_temperature;
    }
    const score_discreteRatio = anyResp.answers?.["discreteRatio"]?.score ?? anyResp.scores?.["discreteRatio"]?.score;
    if (score_discreteRatio !== undefined) {
      const sVal_discreteRatio = interpolateScore(score_discreteRatio, [0.2, 0.5, 0.8]);
      result["discreteRatio"] = sVal_discreteRatio;
    }
    const choice_securityClearance = anyResp.answers?.["securityClearance"]?.choice ?? anyResp.choices?.["securityClearance"]?.choice;
    if (choice_securityClearance) {
      result["securityClearance"] = choice_securityClearance;
    }
    const choice_decisionFlag = anyResp.answers?.["decisionFlag"]?.choice ?? anyResp.choices?.["decisionFlag"]?.choice;
    if (choice_decisionFlag) {
      result["decisionFlag"] = choice_decisionFlag;
    }
    const score_customBoundedScore = anyResp.answers?.["customBoundedScore"]?.score ?? anyResp.scores?.["customBoundedScore"]?.score;
    if (score_customBoundedScore !== undefined) {
      const sVal_customBoundedScore = interpolateScore(score_customBoundedScore, [10, 20, 30, 40, 50]);
      result["customBoundedScore"] = sVal_customBoundedScore;
    }
    return create(RuleTestRecordSchema, result as any) as RuleTestRecord;
  }

  async batchEvaluate(states: Array<RuleTestRecord | Record<string, any> | string>): Promise<RuleTestRecord[]> {
    return Promise.all(states.map(state => this.evaluate(state)));
  }
}

