// Code generated by protoc-gen-jev. DO NOT EDIT.
package rulesv1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

const DefaultJevEndpoint = "https://api.typesafe.ai/v1/systemone"

// RuleTestRecordJevDecisions holds structured decisions returned by Jev for RuleTestRecord.
type RuleTestRecordJevDecisions struct {
	DeliveryMethod     string  `json:"delivery_method"`
	ExecutionMode      string  `json:"executionMode"`
	FilteredMode       string  `json:"filteredMode"`
	RatingSmall        float64 `json:"ratingSmall"`
	RatingStrict       float64 `json:"ratingStrict"`
	DiscreteCode       float64 `json:"discreteCode"`
	LargeScale         float64 `json:"largeScale"`
	Temperature        float64 `json:"temperature"`
	DiscreteRatio      float64 `json:"discreteRatio"`
	SecurityClearance  string  `json:"securityClearance"`
	DecisionFlag       string  `json:"decisionFlag"`
	CustomBoundedScore float64 `json:"customBoundedScore"`
}

// RuleTestRecordJevClient is a typed client for evaluating RuleTestRecord decisions via Jev.
type RuleTestRecordJevClient struct {
	APIKey     string
	Endpoint   string
	HTTPClient *http.Client
}

func NewRuleTestRecordJevClient(apiKey string) *RuleTestRecordJevClient {
	if apiKey == "" {
		apiKey = os.Getenv("TYPESAFE_API_KEY")
	}
	return &RuleTestRecordJevClient{
		APIKey:     apiKey,
		Endpoint:   DefaultJevEndpoint,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *RuleTestRecordJevClient) BuildQuestions() map[string]any {
	return map[string]any{
		"delivery_method": map[string]any{
			"type":         "choice",
			"instructions": "1. Oneof mutual exclusion -> maps to Choice",
			"criteria":     map[string]any{"email": nil, "push_notification": nil, "sms": nil},
		},
		"executionMode": map[string]any{
			"type":         "choice",
			"instructions": "3. Enum restricted by enum.in -> Choice with only [MODE_FAST, MODE_BALANCED]",
			"criteria":     map[string]any{"MODE_BALANCED": nil, "MODE_FAST": nil},
		},
		"filteredMode": map[string]any{
			"type":         "choice",
			"instructions": "4. Enum restricted by enum.not_in -> Choice omitting MODE_DEBUG",
			"criteria":     map[string]any{"MODE_ACCURATE": nil, "MODE_BALANCED": nil, "MODE_FAST": nil},
		},
		"ratingSmall": map[string]any{
			"type":         "score",
			"instructions": "5. Integer with small range (<= 10) -> exact sequence [1..5]",
			"criteria":     []string{"1", "2", "3", "4", "5"},
		},
		"ratingStrict": map[string]any{
			"type":         "score",
			"instructions": "6. Integer with strict bounds (gt/lt) -> [1, 2, 3]",
			"criteria":     []string{"1", "2", "3"},
		},
		"discreteCode": map[string]any{
			"type":         "score",
			"instructions": "7. Integer with discrete allowed values -> [\"10\", \"20\", \"50\", \"100\"]",
			"criteria":     []string{"10", "20", "50", "100"},
		},
		"largeScale": map[string]any{
			"type":         "score",
			"instructions": "8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]",
			"criteria":     []string{"0", "250", "500", "750", "1000"},
		},
		"temperature": map[string]any{
			"type":         "score",
			"instructions": "9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]",
			"criteria":     []string{"-40.0", "-15.0", "10.0", "35.0", "60.0"},
		},
		"discreteRatio": map[string]any{
			"type":         "score",
			"instructions": "10. Float discrete values -> [\"0.2\", \"0.5\", \"0.8\"]",
			"criteria":     []string{"0.2", "0.5", "0.8"},
		},
		"securityClearance": map[string]any{
			"type":         "choice",
			"instructions": "11. String with allowed set of values -> Choice",
			"criteria":     map[string]any{"PUBLIC": nil, "SECRET": nil, "TOP_SECRET": nil},
		},
		"decisionFlag": map[string]any{
			"type":         "choice",
			"instructions": "12. String with custom Jev criteria options -> Choice",
			"criteria":     map[string]any{"APPROVE": nil, "REJECT": nil},
		},
		"customBoundedScore": map[string]any{
			"type":         "score",
			"instructions": "13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]",
			"criteria":     []string{"10.0", "20.0", "30.0", "40.0", "50.0"},
		},
	}
}

func (c *RuleTestRecordJevClient) Evaluate(ctx context.Context, state any) (*RuleTestRecordJevDecisions, error) {
	payload := map[string]any{
		"state":     state,
		"questions": c.BuildQuestions(),
	}
	bodyBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Jev payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.Endpoint, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Jev request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("Jev API returned error status %d: %s", resp.StatusCode, string(b))
	}
	var rawResp struct {
		Choices map[string]struct {
			Choice string `json:"choice"`
		} `json:"choices"`
		Nouls map[string]struct {
			Result bool `json:"result"`
		} `json:"nouls"`
		Scores map[string]struct {
			Score float64 `json:"score"`
		} `json:"scores"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rawResp); err != nil {
		return nil, fmt.Errorf("failed to decode Jev response: %w", err)
	}
	decisions := &RuleTestRecordJevDecisions{}
	if item, ok := rawResp.Choices["delivery_method"]; ok {
		decisions.DeliveryMethod = item.Choice
	}
	if item, ok := rawResp.Choices["executionMode"]; ok {
		decisions.ExecutionMode = item.Choice
	}
	if item, ok := rawResp.Choices["filteredMode"]; ok {
		decisions.FilteredMode = item.Choice
	}
	if item, ok := rawResp.Scores["ratingSmall"]; ok {
		decisions.RatingSmall = item.Score
	}
	if item, ok := rawResp.Scores["ratingStrict"]; ok {
		decisions.RatingStrict = item.Score
	}
	if item, ok := rawResp.Scores["discreteCode"]; ok {
		decisions.DiscreteCode = item.Score
	}
	if item, ok := rawResp.Scores["largeScale"]; ok {
		decisions.LargeScale = item.Score
	}
	if item, ok := rawResp.Scores["temperature"]; ok {
		decisions.Temperature = item.Score
	}
	if item, ok := rawResp.Scores["discreteRatio"]; ok {
		decisions.DiscreteRatio = item.Score
	}
	if item, ok := rawResp.Choices["securityClearance"]; ok {
		decisions.SecurityClearance = item.Choice
	}
	if item, ok := rawResp.Choices["decisionFlag"]; ok {
		decisions.DecisionFlag = item.Choice
	}
	if item, ok := rawResp.Scores["customBoundedScore"]; ok {
		decisions.CustomBoundedScore = item.Score
	}
	return decisions, nil
}

// BatchEvaluate evaluates multiple states against Jev sequentially.
func (c *RuleTestRecordJevClient) BatchEvaluate(ctx context.Context, states []any) ([]*RuleTestRecordJevDecisions, error) {
	results := make([]*RuleTestRecordJevDecisions, len(states))
	for i, s := range states {
		res, err := c.Evaluate(ctx, s)
		if err != nil {
			return nil, fmt.Errorf("failed evaluating state at index %d: %w", i, err)
		}
		results[i] = res
	}
	return results, nil
}
