"""Generated by protoc-gen-jev. DO NOT EDIT."""
from typing import Any, Dict, List, Optional
from google.protobuf.json_format import MessageToDict
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score
from .rules_pb2 import (
    RuleTestRecord,
)

def _interpolate_score(s: float, levels: List[float]) -> float:
    if not levels:
        return s
    if s <= 0:
        return levels[0]
    if s >= len(levels) - 1:
        return levels[-1]
    idx = int(s)
    frac = s - idx
    return levels[idx] + frac * (levels[idx + 1] - levels[idx])

class RuleTestRecordJevClient:
    """Typed Jev client for evaluating RuleTestRecord."""

    def __init__(self, client: Optional[TypeSafeClient] = None, api_key: Optional[str] = None):
        if client is not None:
            self._client = client
        elif api_key is not None:
            self._client = TypeSafeClient(api_key=api_key)
        else:
            self._client = None

    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient()
        return self._client

    def build_questions(self) -> Dict[str, Any]:
        """Constructs the native Jev question primitives from the Protobuf schema."""
        return {
            "delivery_method": Choice(
                instructions="1. Oneof mutual exclusion -> maps to Choice",
                criteria={"email": "email", "push_notification": "push_notification", "sms": "sms"},
            ),
            "executionMode": Choice(
                instructions="3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]",
                criteria={"MODE_BALANCED": "", "MODE_FAST": ""},
            ),
            "filteredMode": Choice(
                instructions="4. Enum restricted by not_in -> Choice omitting MODE_DEBUG",
                criteria={"MODE_ACCURATE": "", "MODE_BALANCED": "", "MODE_FAST": ""},
            ),
            "ratingSmall": Score(
                instructions="5. Integer with small range (<= 10) -> exact sequence [1..5]",
                criteria=["1", "2", "3", "4", "5"],
            ),
            "ratingStrict": Score(
                instructions="6. Integer with explicit scale -> [1, 2, 3]",
                criteria=["1", "2", "3"],
            ),
            "discreteCode": Score(
                instructions="7. Integer with discrete allowed values -> [\"10\", \"20\", \"50\", \"100\"]",
                criteria=["10", "20", "50", "100"],
            ),
            "largeScale": Score(
                instructions="8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]",
                criteria=["0", "250", "500", "750", "1000"],
            ),
            "temperature": Score(
                instructions="9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]",
                criteria=["-40.0", "-15.0", "10.0", "35.0", "60.0"],
            ),
            "discreteRatio": Score(
                instructions="10. Float discrete values -> [\"0.2\", \"0.5\", \"0.8\"]",
                criteria=["0.2", "0.5", "0.8"],
            ),
            "securityClearance": Choice(
                instructions="11. String with allowed set of values -> Choice",
                criteria={"PUBLIC": "", "SECRET": "", "TOP_SECRET": ""},
            ),
            "decisionFlag": Choice(
                instructions="12. String with custom Jev criteria options -> Choice",
                criteria={"APPROVE": "Request approved", "REJECT": "Request rejected"},
            ),
            "customBoundedScore": Score(
                instructions="13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]",
                criteria=["10.0", "20.0", "30.0", "40.0", "50.0"],
            ),
        }

    def evaluate(self, state: RuleTestRecord | Dict[str, Any] | str) -> RuleTestRecord:
        """Evaluates state against Jev System One questions and returns typed decisions."""
        payload_state = MessageToDict(state, preserving_proto_field_name=True) if hasattr(state, "DESCRIPTOR") else ({"text": state} if isinstance(state, str) else state)
        questions = self.build_questions()
        resp = self.client.system_one(state=payload_state, questions=questions)
        out = RuleTestRecord()
        choice_delivery_method = None
        if hasattr(resp, "answers") and "delivery_method" in resp.answers:
            choice_delivery_method = getattr(resp.answers["delivery_method"], "choice", None)
        elif "delivery_method" in resp.choices:
            choice_delivery_method = resp.choices["delivery_method"].choice
        if choice_delivery_method:
            _f_desc = out.DESCRIPTOR.fields_by_name.get(choice_delivery_method)
            if _f_desc and _f_desc.type == 12:
                setattr(out, choice_delivery_method, choice_delivery_method.encode("utf-8"))
            else:
                setattr(out, choice_delivery_method, choice_delivery_method)
        choice_executionMode = None
        if hasattr(resp, "answers") and "executionMode" in resp.answers:
            choice_executionMode = getattr(resp.answers["executionMode"], "choice", None)
        elif "executionMode" in resp.choices:
            choice_executionMode = resp.choices["executionMode"].choice
        if choice_executionMode:
            enum_desc = out.DESCRIPTOR.fields_by_name["execution_mode"].enum_type
            if enum_desc and choice_executionMode in enum_desc.values_by_name:
                setattr(out, "execution_mode", enum_desc.values_by_name[choice_executionMode].number)
            else:
                try:
                    setattr(out, "execution_mode", int(choice_executionMode))
                except (ValueError, TypeError):
                    pass
        choice_filteredMode = None
        if hasattr(resp, "answers") and "filteredMode" in resp.answers:
            choice_filteredMode = getattr(resp.answers["filteredMode"], "choice", None)
        elif "filteredMode" in resp.choices:
            choice_filteredMode = resp.choices["filteredMode"].choice
        if choice_filteredMode:
            enum_desc = out.DESCRIPTOR.fields_by_name["filtered_mode"].enum_type
            if enum_desc and choice_filteredMode in enum_desc.values_by_name:
                setattr(out, "filtered_mode", enum_desc.values_by_name[choice_filteredMode].number)
            else:
                try:
                    setattr(out, "filtered_mode", int(choice_filteredMode))
                except (ValueError, TypeError):
                    pass
        score_ratingSmall = None
        if hasattr(resp, "answers") and "ratingSmall" in resp.answers:
            score_ratingSmall = getattr(resp.answers["ratingSmall"], "score", None)
        elif "ratingSmall" in resp.scores:
            score_ratingSmall = resp.scores["ratingSmall"].score
        if score_ratingSmall is not None:
            _s_val = _interpolate_score(score_ratingSmall, [1, 2, 3, 4, 5])
            out.rating_small = int(round(_s_val))
        score_ratingStrict = None
        if hasattr(resp, "answers") and "ratingStrict" in resp.answers:
            score_ratingStrict = getattr(resp.answers["ratingStrict"], "score", None)
        elif "ratingStrict" in resp.scores:
            score_ratingStrict = resp.scores["ratingStrict"].score
        if score_ratingStrict is not None:
            _s_val = _interpolate_score(score_ratingStrict, [1, 2, 3])
            out.rating_strict = int(round(_s_val))
        score_discreteCode = None
        if hasattr(resp, "answers") and "discreteCode" in resp.answers:
            score_discreteCode = getattr(resp.answers["discreteCode"], "score", None)
        elif "discreteCode" in resp.scores:
            score_discreteCode = resp.scores["discreteCode"].score
        if score_discreteCode is not None:
            _s_val = _interpolate_score(score_discreteCode, [10, 20, 50, 100])
            out.discrete_code = int(round(_s_val))
        score_largeScale = None
        if hasattr(resp, "answers") and "largeScale" in resp.answers:
            score_largeScale = getattr(resp.answers["largeScale"], "score", None)
        elif "largeScale" in resp.scores:
            score_largeScale = resp.scores["largeScale"].score
        if score_largeScale is not None:
            _s_val = _interpolate_score(score_largeScale, [0, 250, 500, 750, 1000])
            out.large_scale = int(round(_s_val))
        score_temperature = None
        if hasattr(resp, "answers") and "temperature" in resp.answers:
            score_temperature = getattr(resp.answers["temperature"], "score", None)
        elif "temperature" in resp.scores:
            score_temperature = resp.scores["temperature"].score
        if score_temperature is not None:
            _s_val = _interpolate_score(score_temperature, [-40, -15, 10, 35, 60])
            out.temperature = _s_val
        score_discreteRatio = None
        if hasattr(resp, "answers") and "discreteRatio" in resp.answers:
            score_discreteRatio = getattr(resp.answers["discreteRatio"], "score", None)
        elif "discreteRatio" in resp.scores:
            score_discreteRatio = resp.scores["discreteRatio"].score
        if score_discreteRatio is not None:
            _s_val = _interpolate_score(score_discreteRatio, [0.2, 0.5, 0.8])
            out.discrete_ratio = _s_val
        choice_securityClearance = None
        if hasattr(resp, "answers") and "securityClearance" in resp.answers:
            choice_securityClearance = getattr(resp.answers["securityClearance"], "choice", None)
        elif "securityClearance" in resp.choices:
            choice_securityClearance = resp.choices["securityClearance"].choice
        if choice_securityClearance:
            setattr(out, "security_clearance", choice_securityClearance)
        choice_decisionFlag = None
        if hasattr(resp, "answers") and "decisionFlag" in resp.answers:
            choice_decisionFlag = getattr(resp.answers["decisionFlag"], "choice", None)
        elif "decisionFlag" in resp.choices:
            choice_decisionFlag = resp.choices["decisionFlag"].choice
        if choice_decisionFlag:
            setattr(out, "decision_flag", choice_decisionFlag)
        score_customBoundedScore = None
        if hasattr(resp, "answers") and "customBoundedScore" in resp.answers:
            score_customBoundedScore = getattr(resp.answers["customBoundedScore"], "score", None)
        elif "customBoundedScore" in resp.scores:
            score_customBoundedScore = resp.scores["customBoundedScore"].score
        if score_customBoundedScore is not None:
            _s_val = _interpolate_score(score_customBoundedScore, [10, 20, 30, 40, 50])
            out.custom_bounded_score = _s_val
        return out

    def batch_evaluate(self, states: List[RuleTestRecord | Dict[str, Any] | str]) -> List[RuleTestRecord]:
        """Evaluates a batch of states against Jev."""
        return [self.evaluate(s) for s in states]

